// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: marketing.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/marketing/rpc/internal/logic/marketing"
	"github.com/ZY0506/PrimeMall/apps/service/marketing/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/marketing/rpc/types/marketing"
)

type MarketingServer struct {
	svcCtx *svc.ServiceContext
	marketing.UnimplementedMarketingServer
}

func NewMarketingServer(svcCtx *svc.ServiceContext) *MarketingServer {
	return &MarketingServer{
		svcCtx: svcCtx,
	}
}

// 创建优惠券（管理后台）
func (s *MarketingServer) CreateCoupon(ctx context.Context, in *marketing.CreateCouponReq) (*marketing.Empty, error) {
	l := marketinglogic.NewCreateCouponLogic(ctx, s.svcCtx)
	return l.CreateCoupon(in)
}

// 更新优惠券（管理后台）
func (s *MarketingServer) UpdateCoupon(ctx context.Context, in *marketing.UpdateCouponReq) (*marketing.Empty, error) {
	l := marketinglogic.NewUpdateCouponLogic(ctx, s.svcCtx)
	return l.UpdateCoupon(in)
}

// 删除优惠券（管理后台）
func (s *MarketingServer) DeleteCoupon(ctx context.Context, in *marketing.IdReq) (*marketing.Empty, error) {
	l := marketinglogic.NewDeleteCouponLogic(ctx, s.svcCtx)
	return l.DeleteCoupon(in)
}

// 获取单个优惠券
func (s *MarketingServer) GetCoupon(ctx context.Context, in *marketing.IdReq) (*marketing.CouponResp, error) {
	l := marketinglogic.NewGetCouponLogic(ctx, s.svcCtx)
	return l.GetCoupon(in)
}

// 获取全部可领取优惠券（领券中心）
func (s *MarketingServer) ListCoupons(ctx context.Context, in *marketing.ListCouponsReq) (*marketing.ListCouponsResp, error) {
	l := marketinglogic.NewListCouponsLogic(ctx, s.svcCtx)
	return l.ListCoupons(in)
}

// 用户领取优惠券
func (s *MarketingServer) ClaimCoupon(ctx context.Context, in *marketing.ClaimCouponReq) (*marketing.ClaimCouponResp, error) {
	l := marketinglogic.NewClaimCouponLogic(ctx, s.svcCtx)
	return l.ClaimCoupon(in)
}

// 我的优惠券列表
func (s *MarketingServer) MyCoupons(ctx context.Context, in *marketing.MyCouponsReq) (*marketing.MyCouponsResp, error) {
	l := marketinglogic.NewMyCouponsLogic(ctx, s.svcCtx)
	return l.MyCoupons(in)
}

// 结算页获取可用/不可用优惠券
func (s *MarketingServer) AvailableCoupons(ctx context.Context, in *marketing.AvailableCouponsReq) (*marketing.AvailableCouponsResp, error) {
	l := marketinglogic.NewAvailableCouponsLogic(ctx, s.svcCtx)
	return l.AvailableCoupons(in)
}

// 内部：使用优惠券（锁定扣减）
func (s *MarketingServer) UseCoupon(ctx context.Context, in *marketing.UseCouponReq) (*marketing.UseCouponResp, error) {
	l := marketinglogic.NewUseCouponLogic(ctx, s.svcCtx)
	return l.UseCoupon(in)
}

// 内部：解锁优惠券（订单取消回滚）
func (s *MarketingServer) UnlockCoupon(ctx context.Context, in *marketing.UnlockCouponReq) (*marketing.UnlockCouponResp, error) {
	l := marketinglogic.NewUnlockCouponLogic(ctx, s.svcCtx)
	return l.UnlockCoupon(in)
}

// 内部：获取用户优惠券信息（含券定义）
func (s *MarketingServer) GetUserCoupon(ctx context.Context, in *marketing.GetUserCouponReq) (*marketing.GetUserCouponResp, error) {
	l := marketinglogic.NewGetUserCouponLogic(ctx, s.svcCtx)
	return l.GetUserCoupon(in)
}
