// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package search

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/search/rpc/types/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchSyncProductsReq  = search.BatchSyncProductsReq
	ClearSearchHistoryReq = search.ClearSearchHistoryReq
	DeleteProductReq      = search.DeleteProductReq
	Empty                 = search.Empty
	HotKeywordsResp       = search.HotKeywordsResp
	SearchHistoryReq      = search.SearchHistoryReq
	SearchHistoryResp     = search.SearchHistoryResp
	SearchProductsReq     = search.SearchProductsReq
	SearchProductsResp    = search.SearchProductsResp
	SuggestReq            = search.SuggestReq
	SuggestResp           = search.SuggestResp
	SyncProductReq        = search.SyncProductReq

	Search interface {
		// ES商品搜索
		SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error)
		// ES商品搜索建议（补全）
		SuggestProducts(ctx context.Context, in *SuggestReq, opts ...grpc.CallOption) (*SuggestResp, error)
		// 热搜词列表
		GetHotKeywords(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HotKeywordsResp, error)
		// 用户搜索历史
		GetSearchHistory(ctx context.Context, in *SearchHistoryReq, opts ...grpc.CallOption) (*SearchHistoryResp, error)
		// 清除搜索历史
		ClearSearchHistory(ctx context.Context, in *ClearSearchHistoryReq, opts ...grpc.CallOption) (*Empty, error)
		// 同步商品到ES
		SyncProductToES(ctx context.Context, in *SyncProductReq, opts ...grpc.CallOption) (*Empty, error)
		// 批量同步商品到ES
		BatchSyncProducts(ctx context.Context, in *BatchSyncProductsReq, opts ...grpc.CallOption) (*Empty, error)
		// 从ES删除商品
		DeleteProductFromES(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

// ES商品搜索
func (m *defaultSearch) SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.SearchProducts(ctx, in, opts...)
}

// ES商品搜索建议（补全）
func (m *defaultSearch) SuggestProducts(ctx context.Context, in *SuggestReq, opts ...grpc.CallOption) (*SuggestResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.SuggestProducts(ctx, in, opts...)
}

// 热搜词列表
func (m *defaultSearch) GetHotKeywords(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HotKeywordsResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.GetHotKeywords(ctx, in, opts...)
}

// 用户搜索历史
func (m *defaultSearch) GetSearchHistory(ctx context.Context, in *SearchHistoryReq, opts ...grpc.CallOption) (*SearchHistoryResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.GetSearchHistory(ctx, in, opts...)
}

// 清除搜索历史
func (m *defaultSearch) ClearSearchHistory(ctx context.Context, in *ClearSearchHistoryReq, opts ...grpc.CallOption) (*Empty, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.ClearSearchHistory(ctx, in, opts...)
}

// 同步商品到ES
func (m *defaultSearch) SyncProductToES(ctx context.Context, in *SyncProductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.SyncProductToES(ctx, in, opts...)
}

// 批量同步商品到ES
func (m *defaultSearch) BatchSyncProducts(ctx context.Context, in *BatchSyncProductsReq, opts ...grpc.CallOption) (*Empty, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.BatchSyncProducts(ctx, in, opts...)
}

// 从ES删除商品
func (m *defaultSearch) DeleteProductFromES(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.DeleteProductFromES(ctx, in, opts...)
}
