// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: order.proto

package orderinternal

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/order/rpc/types/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddressDetail                = order.AddressDetail
	AddressSnapshot              = order.AddressSnapshot
	AdminAfterSaleDetailResponse = order.AdminAfterSaleDetailResponse
	AdminAfterSaleListItem       = order.AdminAfterSaleListItem
	AdminGetAfterSaleRequest     = order.AdminGetAfterSaleRequest
	AdminGetOrderRequest         = order.AdminGetOrderRequest
	AdminHandleAfterSaleRequest  = order.AdminHandleAfterSaleRequest
	AdminListAfterSalesRequest   = order.AdminListAfterSalesRequest
	AdminListAfterSalesResponse  = order.AdminListAfterSalesResponse
	AdminListOrdersRequest       = order.AdminListOrdersRequest
	AdminListOrdersResponse      = order.AdminListOrdersResponse
	AdminOrderAddress            = order.AdminOrderAddress
	AdminOrderDetailResponse     = order.AdminOrderDetailResponse
	AdminOrderListItem           = order.AdminOrderListItem
	AdminOrderProductItem        = order.AdminOrderProductItem
	AdminShipOrderRequest        = order.AdminShipOrderRequest
	AfterSaleDetailRequest       = order.AfterSaleDetailRequest
	AfterSaleDetailResponse      = order.AfterSaleDetailResponse
	AfterSaleListItem            = order.AfterSaleListItem
	AfterSaleListRequest         = order.AfterSaleListRequest
	AfterSaleListResponse        = order.AfterSaleListResponse
	AfterSaleRequest             = order.AfterSaleRequest
	BatchSelectCartRequest       = order.BatchSelectCartRequest
	CancelAfterSaleRequest       = order.CancelAfterSaleRequest
	CancelOrderRequest           = order.CancelOrderRequest
	CartItem                     = order.CartItem
	CartListResponse             = order.CartListResponse
	CreateOrderRequest           = order.CreateOrderRequest
	CreateOrderResponse          = order.CreateOrderResponse
	Empty                        = order.Empty
	OrderDetailRequest           = order.OrderDetailRequest
	OrderDetailResponse          = order.OrderDetailResponse
	OrderItem                    = order.OrderItem
	OrderItemSimple              = order.OrderItemSimple
	OrderListItem                = order.OrderListItem
	OrderListRequest             = order.OrderListRequest
	OrderListResponse            = order.OrderListResponse
	OrderTimeoutMessage          = order.OrderTimeoutMessage
	OrderTimeoutNotifyRequest    = order.OrderTimeoutNotifyRequest
	PaymentSuccessNotifyRequest  = order.PaymentSuccessNotifyRequest
	PreOrderRequest              = order.PreOrderRequest
	PreOrderResponse             = order.PreOrderResponse
	RefundSuccessNotifyRequest   = order.RefundSuccessNotifyRequest
	RemoveCartRequest            = order.RemoveCartRequest
	SelectCartRequest            = order.SelectCartRequest
	SubmitReturnLogisticsRequest = order.SubmitReturnLogisticsRequest
	UpdateCartRequest            = order.UpdateCartRequest

	OrderInternal interface {
		// NotifyPaymentSuccess - 接收支付成功通知（由 Payment 服务调用）
		NotifyPaymentSuccess(ctx context.Context, in *PaymentSuccessNotifyRequest, opts ...grpc.CallOption) (*Empty, error)
		// NotifyRefundSuccess - 接收退款成功通知（由 Payment 服务调用）
		NotifyRefundSuccess(ctx context.Context, in *RefundSuccessNotifyRequest, opts ...grpc.CallOption) (*Empty, error)
		// NotifyOrderTimeout - 接收订单超时通知（由 MQ 消费者调用）
		NotifyOrderTimeout(ctx context.Context, in *OrderTimeoutNotifyRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultOrderInternal struct {
		cli zrpc.Client
	}
)

func NewOrderInternal(cli zrpc.Client) OrderInternal {
	return &defaultOrderInternal{
		cli: cli,
	}
}

// NotifyPaymentSuccess - 接收支付成功通知（由 Payment 服务调用）
func (m *defaultOrderInternal) NotifyPaymentSuccess(ctx context.Context, in *PaymentSuccessNotifyRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderInternalClient(m.cli.Conn())
	return client.NotifyPaymentSuccess(ctx, in, opts...)
}

// NotifyRefundSuccess - 接收退款成功通知（由 Payment 服务调用）
func (m *defaultOrderInternal) NotifyRefundSuccess(ctx context.Context, in *RefundSuccessNotifyRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderInternalClient(m.cli.Conn())
	return client.NotifyRefundSuccess(ctx, in, opts...)
}

// NotifyOrderTimeout - 接收订单超时通知（由 MQ 消费者调用）
func (m *defaultOrderInternal) NotifyOrderTimeout(ctx context.Context, in *OrderTimeoutNotifyRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderInternalClient(m.cli.Conn())
	return client.NotifyOrderTimeout(ctx, in, opts...)
}
