// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package cart

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/order/rpc/types/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchSelectCartRequest = order.BatchSelectCartRequest
	CartListResponse       = order.CartListResponse
	Empty                  = order.Empty
	RemoveCartRequest      = order.RemoveCartRequest
	SelectCartRequest      = order.SelectCartRequest
	UpdateCartRequest      = order.UpdateCartRequest

	Cart interface {
		// UpdateCart - 添加/更新购物车：quantity=0 时删除商品
		UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*Empty, error)
		// SelectCart - 修改单个商品选中状态
		SelectCart(ctx context.Context, in *SelectCartRequest, opts ...grpc.CallOption) (*Empty, error)
		// BatchSelectCart - 批量修改选中状态（支持全选/全不选）
		BatchSelectCart(ctx context.Context, in *BatchSelectCartRequest, opts ...grpc.CallOption) (*Empty, error)
		// CartList - 获取购物车列表（含选中状态、库存、价格）
		CartList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CartListResponse, error)
		// RemoveCart - 批量删除购物车商品
		RemoveCart(ctx context.Context, in *RemoveCartRequest, opts ...grpc.CallOption) (*Empty, error)
		// ClearCart - 清空当前用户购物车
		ClearCart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

// UpdateCart - 添加/更新购物车：quantity=0 时删除商品
func (m *defaultCart) UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewCartClient(m.cli.Conn())
	return client.UpdateCart(ctx, in, opts...)
}

// SelectCart - 修改单个商品选中状态
func (m *defaultCart) SelectCart(ctx context.Context, in *SelectCartRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewCartClient(m.cli.Conn())
	return client.SelectCart(ctx, in, opts...)
}

// BatchSelectCart - 批量修改选中状态（支持全选/全不选）
func (m *defaultCart) BatchSelectCart(ctx context.Context, in *BatchSelectCartRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewCartClient(m.cli.Conn())
	return client.BatchSelectCart(ctx, in, opts...)
}

// CartList - 获取购物车列表（含选中状态、库存、价格）
func (m *defaultCart) CartList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CartListResponse, error) {
	client := order.NewCartClient(m.cli.Conn())
	return client.CartList(ctx, in, opts...)
}

// RemoveCart - 批量删除购物车商品
func (m *defaultCart) RemoveCart(ctx context.Context, in *RemoveCartRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewCartClient(m.cli.Conn())
	return client.RemoveCart(ctx, in, opts...)
}

// ClearCart - 清空当前用户购物车
func (m *defaultCart) ClearCart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewCartClient(m.cli.Conn())
	return client.ClearCart(ctx, in, opts...)
}
