// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: product.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/product/rpc/internal/logic/productinternal"
	"github.com/ZY0506/PrimeMall/apps/service/product/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/product/rpc/types/product"
)

type ProductInternalServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductInternalServer
}

func NewProductInternalServer(svcCtx *svc.ServiceContext) *ProductInternalServer {
	return &ProductInternalServer{
		svcCtx: svcCtx,
	}
}

// 锁定库存（下单预占）
func (s *ProductInternalServer) LockStock(ctx context.Context, in *product.UpdateStockReq) (*product.StockChangeResp, error) {
	l := productinternallogic.NewLockStockLogic(ctx, s.svcCtx)
	return l.LockStock(in)
}

// 解锁库存（超时未支付）
func (s *ProductInternalServer) UnlockStock(ctx context.Context, in *product.UpdateStockReq) (*product.StockChangeResp, error) {
	l := productinternallogic.NewUnlockStockLogic(ctx, s.svcCtx)
	return l.UnlockStock(in)
}

// 扣减库存（支付成功）
func (s *ProductInternalServer) DeductStock(ctx context.Context, in *product.UpdateStockReq) (*product.StockChangeResp, error) {
	l := productinternallogic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

// 回滚库存（订单取消/退款）
func (s *ProductInternalServer) RollbackStock(ctx context.Context, in *product.UpdateStockReq) (*product.StockChangeResp, error) {
	l := productinternallogic.NewRollbackStockLogic(ctx, s.svcCtx)
	return l.RollbackStock(in)
}

// 回滚库存（订单取消/退款）
func (s *ProductInternalServer) RevertDeductStock(ctx context.Context, in *product.UpdateStockReq) (*product.StockChangeResp, error) {
	l := productinternallogic.NewRevertDeductStockLogic(ctx, s.svcCtx)
	return l.RevertDeductStock(in)
}

// 批量查询库存（订单服务校验，返回可用库存）
func (s *ProductInternalServer) BatchGetStock(ctx context.Context, in *product.SkuIdsReq) (*product.BatchStockResp, error) {
	l := productinternallogic.NewBatchGetStockLogic(ctx, s.svcCtx)
	return l.BatchGetStock(in)
}

// 批量获取Sku
func (s *ProductInternalServer) GetSkuListByIds(ctx context.Context, in *product.SkuIdsReq) (*product.SkuListResp, error) {
	l := productinternallogic.NewGetSkuListByIdsLogic(ctx, s.svcCtx)
	return l.GetSkuListByIds(in)
}

// 计算运费
func (s *ProductInternalServer) CalculateFreight(ctx context.Context, in *product.CalculateFreightReq) (*product.CalculatePriceResp, error) {
	l := productinternallogic.NewCalculateFreightLogic(ctx, s.svcCtx)
	return l.CalculateFreight(in)
}
