// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: order.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/order/rpc/internal/logic/orderadmin"
	"github.com/ZY0506/PrimeMall/apps/service/order/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/order/rpc/types/order"
)

type OrderAdminServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderAdminServer
}

func NewOrderAdminServer(svcCtx *svc.ServiceContext) *OrderAdminServer {
	return &OrderAdminServer{
		svcCtx: svcCtx,
	}
}

// ListOrders - 订单列表查询
func (s *OrderAdminServer) ListOrders(ctx context.Context, in *order.AdminListOrdersRequest) (*order.AdminListOrdersResponse, error) {
	l := orderadminlogic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

// GetOrder - 订单详情查询
func (s *OrderAdminServer) GetOrder(ctx context.Context, in *order.AdminGetOrderRequest) (*order.AdminOrderDetailResponse, error) {
	l := orderadminlogic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

// ShipOrder - 订单发货
func (s *OrderAdminServer) ShipOrder(ctx context.Context, in *order.AdminShipOrderRequest) (*order.Empty, error) {
	l := orderadminlogic.NewShipOrderLogic(ctx, s.svcCtx)
	return l.ShipOrder(in)
}

// ListAfterSales - 售后列表查询
func (s *OrderAdminServer) ListAfterSales(ctx context.Context, in *order.AdminListAfterSalesRequest) (*order.AdminListAfterSalesResponse, error) {
	l := orderadminlogic.NewListAfterSalesLogic(ctx, s.svcCtx)
	return l.ListAfterSales(in)
}

// GetAfterSale - 售后详情查询
func (s *OrderAdminServer) GetAfterSale(ctx context.Context, in *order.AdminGetAfterSaleRequest) (*order.AdminAfterSaleDetailResponse, error) {
	l := orderadminlogic.NewGetAfterSaleLogic(ctx, s.svcCtx)
	return l.GetAfterSale(in)
}

// HandleAfterSale - 处理售后（审核同意/拒绝）
func (s *OrderAdminServer) HandleAfterSale(ctx context.Context, in *order.AdminHandleAfterSaleRequest) (*order.Empty, error) {
	l := orderadminlogic.NewHandleAfterSaleLogic(ctx, s.svcCtx)
	return l.HandleAfterSale(in)
}
