// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: admin.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/internal/logic/adminuser"
	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"
)

type AdminUserServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminUserServer
}

func NewAdminUserServer(svcCtx *svc.ServiceContext) *AdminUserServer {
	return &AdminUserServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminUserServer) ListUsers(ctx context.Context, in *admin.AdminListUsersReq) (*admin.AdminListUsersResp, error) {
	l := adminuserlogic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *AdminUserServer) GetUserDetail(ctx context.Context, in *admin.AdminGetUserDetailReq) (*admin.AdminGetUserDetailResp, error) {
	l := adminuserlogic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}

func (s *AdminUserServer) BanUser(ctx context.Context, in *admin.AdminBanUserReq) (*admin.Empty, error) {
	l := adminuserlogic.NewBanUserLogic(ctx, s.svcCtx)
	return l.BanUser(in)
}

func (s *AdminUserServer) UnbanUser(ctx context.Context, in *admin.AdminUnbanUserReq) (*admin.Empty, error) {
	l := adminuserlogic.NewUnbanUserLogic(ctx, s.svcCtx)
	return l.UnbanUser(in)
}
