// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package user

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAddressReq          = user.AddAddressReq
	AddressDetail          = user.AddressDetail
	AddressItem            = user.AddressItem
	AddressListReq         = user.AddressListReq
	AddressListResp        = user.AddressListResp
	AdminResetPasswordReq  = user.AdminResetPasswordReq
	BanUserReq             = user.BanUserReq
	BatchGetUserByIdReq    = user.BatchGetUserByIdReq
	BatchUserBasicInfoResp = user.BatchUserBasicInfoResp
	CaptchaReq             = user.CaptchaReq
	CheckUserStatusReq     = user.CheckUserStatusReq
	CheckUserStatusResp    = user.CheckUserStatusResp
	DailyStat              = user.DailyStat
	DeleteAccountReq       = user.DeleteAccountReq
	EmptyReq               = user.EmptyReq
	EmptyResp              = user.EmptyResp
	ErrDetail              = user.ErrDetail
	GetAddressReq          = user.GetAddressReq
	GetUserByIdReq         = user.GetUserByIdReq
	GetUserDetailReq       = user.GetUserDetailReq
	GetUserDetailResp      = user.GetUserDetailResp
	GetUserStatisticsReq   = user.GetUserStatisticsReq
	GetUserStatisticsResp  = user.GetUserStatisticsResp
	IdPathReq              = user.IdPathReq
	ListLoginLogsReq       = user.ListLoginLogsReq
	ListLoginLogsResp      = user.ListLoginLogsResp
	ListPunishLogsReq      = user.ListPunishLogsReq
	ListPunishLogsResp     = user.ListPunishLogsResp
	ListUsersReq           = user.ListUsersReq
	ListUsersResp          = user.ListUsersResp
	LoginLogItem           = user.LoginLogItem
	LoginReq               = user.LoginReq
	LoginResp              = user.LoginResp
	LogoutReq              = user.LogoutReq
	MobileLoginReq         = user.MobileLoginReq
	OssTokenReq            = user.OssTokenReq
	OssTokenResp           = user.OssTokenResp
	PunishLogItem          = user.PunishLogItem
	RefreshTokenReq        = user.RefreshTokenReq
	RegisterReq            = user.RegisterReq
	ResetPasswordReq       = user.ResetPasswordReq
	UnbanUserReq           = user.UnbanUserReq
	UpdatePasswordReq      = user.UpdatePasswordReq
	UpdatePhoneReq         = user.UpdatePhoneReq
	UpdateUserInfoReq      = user.UpdateUserInfoReq
	UserBasicInfo          = user.UserBasicInfo
	UserInfoResp           = user.UserInfoResp
	UserListItem           = user.UserListItem

	User interface {
		// Captcha 获取短信验证码
		Captcha(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// Login 手机号密码登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// MobileLogin 手机号验证码登录
		MobileLogin(ctx context.Context, in *MobileLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// Register 用户注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*LoginResp, error)
		// ResetPassword 忘记密码重置
		ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// UpdatePassword 修改登录密码（已登录）
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// UpdatePhone 修改手机号
		UpdatePhone(ctx context.Context, in *UpdatePhoneReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// GetUserInfo 获取个人资料
		GetUserInfo(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		// UpdateUserInfo 更新个人资料
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// DeleteAccount 注销账号
		DeleteAccount(ctx context.Context, in *DeleteAccountReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// Logout 退出登录
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// RefreshToken token刷新
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginResp, error)
		// GetOssToken 获取OSS上传凭证
		GetOssToken(ctx context.Context, in *OssTokenReq, opts ...grpc.CallOption) (*OssTokenResp, error)
		// AddAddress 添加收货地址
		AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// UpdateAddress 更新收货地址
		UpdateAddress(ctx context.Context, in *AddressItem, opts ...grpc.CallOption) (*EmptyResp, error)
		// ListAddress 获取地址列表
		ListAddress(ctx context.Context, in *AddressListReq, opts ...grpc.CallOption) (*AddressListResp, error)
		// SetDefaultAddress 设置默认地址
		SetDefaultAddress(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// DeleteAddress 删除收货地址
		DeleteAddress(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// Captcha 获取短信验证码
func (m *defaultUser) Captcha(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Captcha(ctx, in, opts...)
}

// Login 手机号密码登录
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// MobileLogin 手机号验证码登录
func (m *defaultUser) MobileLogin(ctx context.Context, in *MobileLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.MobileLogin(ctx, in, opts...)
}

// Register 用户注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// ResetPassword 忘记密码重置
func (m *defaultUser) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

// UpdatePassword 修改登录密码（已登录）
func (m *defaultUser) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}

// UpdatePhone 修改手机号
func (m *defaultUser) UpdatePhone(ctx context.Context, in *UpdatePhoneReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdatePhone(ctx, in, opts...)
}

// GetUserInfo 获取个人资料
func (m *defaultUser) GetUserInfo(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// UpdateUserInfo 更新个人资料
func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

// DeleteAccount 注销账号
func (m *defaultUser) DeleteAccount(ctx context.Context, in *DeleteAccountReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteAccount(ctx, in, opts...)
}

// Logout 退出登录
func (m *defaultUser) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// RefreshToken token刷新
func (m *defaultUser) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// GetOssToken 获取OSS上传凭证
func (m *defaultUser) GetOssToken(ctx context.Context, in *OssTokenReq, opts ...grpc.CallOption) (*OssTokenResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetOssToken(ctx, in, opts...)
}

// AddAddress 添加收货地址
func (m *defaultUser) AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddAddress(ctx, in, opts...)
}

// UpdateAddress 更新收货地址
func (m *defaultUser) UpdateAddress(ctx context.Context, in *AddressItem, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateAddress(ctx, in, opts...)
}

// ListAddress 获取地址列表
func (m *defaultUser) ListAddress(ctx context.Context, in *AddressListReq, opts ...grpc.CallOption) (*AddressListResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ListAddress(ctx, in, opts...)
}

// SetDefaultAddress 设置默认地址
func (m *defaultUser) SetDefaultAddress(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SetDefaultAddress(ctx, in, opts...)
}

// DeleteAddress 删除收货地址
func (m *defaultUser) DeleteAddress(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteAddress(ctx, in, opts...)
}
