// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productSkuFieldNames          = builder.RawFieldNames(&ProductSku{})
	productSkuRows                = strings.Join(productSkuFieldNames, ",")
	productSkuRowsExpectAutoSet   = strings.Join(stringx.Remove(productSkuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productSkuRowsWithPlaceHolder = strings.Join(stringx.Remove(productSkuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productSkuModel interface {
		Insert(ctx context.Context, data *ProductSku) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductSku, error)
		FindOneBySkuCode(ctx context.Context, skuCode string) (*ProductSku, error)
		Update(ctx context.Context, data *ProductSku) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductSkuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductSku struct {
		Id          uint64         `db:"id"`           // SKU ID
		SpuId       uint64         `db:"spu_id"`       // 所属SPU ID
		SpuName     string         `db:"spu_name"`     // SPU名称
		SkuCode     string         `db:"sku_code"`     // SKU编码（唯一标识）
		Price       int64          `db:"price"`        // 销售价格
		MarketPrice int64          `db:"market_price"` // 市场价（划线价）
		CostPrice   int64          `db:"cost_price"`   // 成本价
		Stock       int64          `db:"stock"`        // 库存数量
		LockedStock int64          `db:"locked_stock"` // 锁定库存数量
		Version     uint64         `db:"version"`      // 乐观锁版本号（用于并发控制）
		SpecData    string         `db:"spec_data"`    // 规格数据（JSON格式）：{颜色:红色},{尺寸:XL}
		Images      sql.NullString `db:"images"`       // SKU专属图片列表（JSON数组）
		Weight      int64          `db:"weight"`       // SKU重量（kg）
		Status      int64          `db:"status"`       // 状态：1-启用，2-禁用
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		DeletedAt   sql.NullTime   `db:"deleted_at"`   // 删除时间
	}
)

func newProductSkuModel(conn sqlx.SqlConn) *defaultProductSkuModel {
	return &defaultProductSkuModel{
		conn:  conn,
		table: "`product_sku`",
	}
}

func (m *defaultProductSkuModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductSkuModel) FindOne(ctx context.Context, id uint64) (*ProductSku, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productSkuRows, m.table)
	var resp ProductSku
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSkuModel) FindOneBySkuCode(ctx context.Context, skuCode string) (*ProductSku, error) {
	var resp ProductSku
	query := fmt.Sprintf("select %s from %s where `sku_code` = ? limit 1", productSkuRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, skuCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSkuModel) Insert(ctx context.Context, data *ProductSku) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productSkuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SpuId, data.SpuName, data.SkuCode, data.Price, data.MarketPrice, data.CostPrice, data.Stock, data.LockedStock, data.Version, data.SpecData, data.Images, data.Weight, data.Status, data.DeletedAt)
	return ret, err
}

func (m *defaultProductSkuModel) Update(ctx context.Context, newData *ProductSku) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productSkuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SpuId, newData.SpuName, newData.SkuCode, newData.Price, newData.MarketPrice, newData.CostPrice, newData.Stock, newData.LockedStock, newData.Version, newData.SpecData, newData.Images, newData.Weight, newData.Status, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultProductSkuModel) tableName() string {
	return m.table
}
