// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stockLogFieldNames          = builder.RawFieldNames(&StockLog{})
	stockLogRows                = strings.Join(stockLogFieldNames, ",")
	stockLogRowsExpectAutoSet   = strings.Join(stringx.Remove(stockLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	stockLogRowsWithPlaceHolder = strings.Join(stringx.Remove(stockLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	stockLogModel interface {
		Insert(ctx context.Context, data *StockLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*StockLog, error)
		FindOneByOrderSnSkuIdChangeType(ctx context.Context, orderSn string, skuId uint64, changeType int64) (*StockLog, error)
		Update(ctx context.Context, data *StockLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultStockLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StockLog struct {
		Id          uint64    `db:"id"`           // 流水ID
		SkuId       uint64    `db:"sku_id"`       // SKU ID
		OrderSn     string    `db:"order_sn"`     // 订单号
		ChangeType  int64     `db:"change_type"`  // 变动类型：1-锁定库存，2-解锁库存，3-实际扣减，4-回滚库存(退货加回), 5-恢复库存(下单事务失败时回滚)
		Quantity    int64     `db:"quantity"`     // 变动数量（正数增加，负数减少）
		BeforeStock int64     `db:"before_stock"` // 变动前库存
		AfterStock  int64     `db:"after_stock"`  // 变动后库存
		Remark      string    `db:"remark"`       // 备注说明
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
	}
)

func newStockLogModel(conn sqlx.SqlConn) *defaultStockLogModel {
	return &defaultStockLogModel{
		conn:  conn,
		table: "`stock_log`",
	}
}

func (m *defaultStockLogModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStockLogModel) FindOne(ctx context.Context, id uint64) (*StockLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockLogRows, m.table)
	var resp StockLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockLogModel) FindOneByOrderSnSkuIdChangeType(ctx context.Context, orderSn string, skuId uint64, changeType int64) (*StockLog, error) {
	var resp StockLog
	query := fmt.Sprintf("select %s from %s where `order_sn` = ? and `sku_id` = ? and `change_type` = ? limit 1", stockLogRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderSn, skuId, changeType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockLogModel) Insert(ctx context.Context, data *StockLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, stockLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SkuId, data.OrderSn, data.ChangeType, data.Quantity, data.BeforeStock, data.AfterStock, data.Remark)
	return ret, err
}

func (m *defaultStockLogModel) Update(ctx context.Context, newData *StockLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, stockLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SkuId, newData.OrderSn, newData.ChangeType, newData.Quantity, newData.BeforeStock, newData.AfterStock, newData.Remark, newData.Id)
	return err
}

func (m *defaultStockLogModel) tableName() string {
	return m.table
}
