// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package adminorder

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminGetOrderReq     = admin.AdminGetOrderReq
	AdminListOrdersReq   = admin.AdminListOrdersReq
	AdminListOrdersResp  = admin.AdminListOrdersResp
	AdminOrderDetailResp = admin.AdminOrderDetailResp
	AdminShipOrderReq    = admin.AdminShipOrderReq
	Empty                = admin.Empty

	AdminOrder interface {
		ListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*AdminListOrdersResp, error)
		GetOrder(ctx context.Context, in *AdminGetOrderReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error)
		ShipOrder(ctx context.Context, in *AdminShipOrderReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAdminOrder struct {
		cli zrpc.Client
	}
)

func NewAdminOrder(cli zrpc.Client) AdminOrder {
	return &defaultAdminOrder{
		cli: cli,
	}
}

func (m *defaultAdminOrder) ListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*AdminListOrdersResp, error) {
	client := admin.NewAdminOrderClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultAdminOrder) GetOrder(ctx context.Context, in *AdminGetOrderReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error) {
	client := admin.NewAdminOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultAdminOrder) ShipOrder(ctx context.Context, in *AdminShipOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminOrderClient(m.cli.Conn())
	return client.ShipOrder(ctx, in, opts...)
}
