// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: admin.proto

package adminorder

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminAdjustStockReq           = admin.AdminAdjustStockReq
	AdminAfterSaleDetailResp      = admin.AdminAfterSaleDetailResp
	AdminAfterSaleItem            = admin.AdminAfterSaleItem
	AdminBanUserReq               = admin.AdminBanUserReq
	AdminCategoryItem             = admin.AdminCategoryItem
	AdminCategoryTreeResp         = admin.AdminCategoryTreeResp
	AdminCreateCategoryReq        = admin.AdminCreateCategoryReq
	AdminCreateFreightTemplateReq = admin.AdminCreateFreightTemplateReq
	AdminCreateProductReq         = admin.AdminCreateProductReq
	AdminFreightTemplateInfo      = admin.AdminFreightTemplateInfo
	AdminGetAfterSaleReq          = admin.AdminGetAfterSaleReq
	AdminGetOrderReq              = admin.AdminGetOrderReq
	AdminGetUserDetailReq         = admin.AdminGetUserDetailReq
	AdminGetUserDetailResp        = admin.AdminGetUserDetailResp
	AdminHandleAfterSaleReq       = admin.AdminHandleAfterSaleReq
	AdminInfo                     = admin.AdminInfo
	AdminListAfterSalesReq        = admin.AdminListAfterSalesReq
	AdminListAfterSalesResp       = admin.AdminListAfterSalesResp
	AdminListFreightTemplatesResp = admin.AdminListFreightTemplatesResp
	AdminListOrdersReq            = admin.AdminListOrdersReq
	AdminListOrdersResp           = admin.AdminListOrdersResp
	AdminListProductsReq          = admin.AdminListProductsReq
	AdminListProductsResp         = admin.AdminListProductsResp
	AdminListStockLogsReq         = admin.AdminListStockLogsReq
	AdminListStockLogsResp        = admin.AdminListStockLogsResp
	AdminListUsersReq             = admin.AdminListUsersReq
	AdminListUsersResp            = admin.AdminListUsersResp
	AdminLogInfo                  = admin.AdminLogInfo
	AdminLoginReq                 = admin.AdminLoginReq
	AdminLoginResp                = admin.AdminLoginResp
	AdminOrderAddress             = admin.AdminOrderAddress
	AdminOrderDetailResp          = admin.AdminOrderDetailResp
	AdminOrderItem                = admin.AdminOrderItem
	AdminOrderProductItem         = admin.AdminOrderProductItem
	AdminPageReq                  = admin.AdminPageReq
	AdminProductDetailResp        = admin.AdminProductDetailResp
	AdminProductItem              = admin.AdminProductItem
	AdminShipOrderReq             = admin.AdminShipOrderReq
	AdminSkuDetailItem            = admin.AdminSkuDetailItem
	AdminSkuItem                  = admin.AdminSkuItem
	AdminSkuStockItem             = admin.AdminSkuStockItem
	AdminSkuStockResult           = admin.AdminSkuStockResult
	AdminSpecItem                 = admin.AdminSpecItem
	AdminStockChangeResp          = admin.AdminStockChangeResp
	AdminStockLogItem             = admin.AdminStockLogItem
	AdminUnbanUserReq             = admin.AdminUnbanUserReq
	AdminUpdateCategoryReq        = admin.AdminUpdateCategoryReq
	AdminUpdateFreightTemplateReq = admin.AdminUpdateFreightTemplateReq
	AdminUpdateProductReq         = admin.AdminUpdateProductReq
	AdminUpdateProductStatusReq   = admin.AdminUpdateProductStatusReq
	AdminUserItem                 = admin.AdminUserItem
	CreateAdminReq                = admin.CreateAdminReq
	DeleteAdminReq                = admin.DeleteAdminReq
	Empty                         = admin.Empty
	GetAdminReq                   = admin.GetAdminReq
	GetAdminResp                  = admin.GetAdminResp
	GetCurrentAdminResp           = admin.GetCurrentAdminResp
	IdReq                         = admin.IdReq
	ListAdminLogReq               = admin.ListAdminLogReq
	ListAdminLogResp              = admin.ListAdminLogResp
	ListAdminReq                  = admin.ListAdminReq
	ListAdminResp                 = admin.ListAdminResp
	ListRoleResp                  = admin.ListRoleResp
	RoleInfo                      = admin.RoleInfo
	UpdateAdminReq                = admin.UpdateAdminReq
	UpdatePasswordReq             = admin.UpdatePasswordReq

	AdminOrder interface {
		ListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*AdminListOrdersResp, error)
		GetOrder(ctx context.Context, in *AdminGetOrderReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error)
		ShipOrder(ctx context.Context, in *AdminShipOrderReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAdminOrder struct {
		cli zrpc.Client
	}
)

func NewAdminOrder(cli zrpc.Client) AdminOrder {
	return &defaultAdminOrder{
		cli: cli,
	}
}

func (m *defaultAdminOrder) ListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*AdminListOrdersResp, error) {
	client := admin.NewAdminOrderClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultAdminOrder) GetOrder(ctx context.Context, in *AdminGetOrderReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error) {
	client := admin.NewAdminOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultAdminOrder) ShipOrder(ctx context.Context, in *AdminShipOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminOrderClient(m.cli.Conn())
	return client.ShipOrder(ctx, in, opts...)
}
