// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: apps/service/payment/rpc/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payment_CreatePayment_FullMethodName    = "/payment.Payment/CreatePayment"
	Payment_QueryPayment_FullMethodName     = "/payment.Payment/QueryPayment"
	Payment_GetPaymentDetail_FullMethodName = "/payment.Payment/GetPaymentDetail"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// C端用户支付服务
// 核心：创建支付、查询支付状态
type PaymentClient interface {
	// CreatePayment - 创建支付（订单提交后调用）：生成支付流水，返回支付参数
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// QueryPayment - 查询支付状态：前端轮询或展示支付结果
	QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error)
	// GetPaymentDetail - 获取支付详情：查看完整支付信息
	GetPaymentDetail(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*GetPaymentDetailResponse, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, Payment_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPaymentResponse)
	err := c.cc.Invoke(ctx, Payment_QueryPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetPaymentDetail(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*GetPaymentDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentDetailResponse)
	err := c.cc.Invoke(ctx, Payment_GetPaymentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility.
//
// *
// C端用户支付服务
// 核心：创建支付、查询支付状态
type PaymentServer interface {
	// CreatePayment - 创建支付（订单提交后调用）：生成支付流水，返回支付参数
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// QueryPayment - 查询支付状态：前端轮询或展示支付结果
	QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentResponse, error)
	// GetPaymentDetail - 获取支付详情：查看完整支付信息
	GetPaymentDetail(context.Context, *GetPaymentDetailRequest) (*GetPaymentDetailResponse, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServer struct{}

func (UnimplementedPaymentServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentServer) QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPayment not implemented")
}
func (UnimplementedPaymentServer) GetPaymentDetail(context.Context, *GetPaymentDetailRequest) (*GetPaymentDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentDetail not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}
func (UnimplementedPaymentServer) testEmbeddedByValue()                 {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_QueryPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).QueryPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_QueryPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).QueryPayment(ctx, req.(*QueryPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetPaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetPaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetPaymentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetPaymentDetail(ctx, req.(*GetPaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _Payment_CreatePayment_Handler,
		},
		{
			MethodName: "QueryPayment",
			Handler:    _Payment_QueryPayment_Handler,
		},
		{
			MethodName: "GetPaymentDetail",
			Handler:    _Payment_GetPaymentDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/payment/rpc/payment.proto",
}

const (
	PaymentAdmin_ListPayments_FullMethodName = "/payment.PaymentAdmin/ListPayments"
	PaymentAdmin_GetPayment_FullMethodName   = "/payment.PaymentAdmin/GetPayment"
)

// PaymentAdminClient is the client API for PaymentAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// 管理后台支付服务
// 提供支付记录查询等功能
type PaymentAdminClient interface {
	// ListPayments - 支付列表查询
	ListPayments(ctx context.Context, in *AdminListPaymentsRequest, opts ...grpc.CallOption) (*AdminListPaymentsResponse, error)
	// GetPayment - 支付详情查询
	GetPayment(ctx context.Context, in *AdminGetPaymentRequest, opts ...grpc.CallOption) (*AdminPaymentDetailResponse, error)
}

type paymentAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentAdminClient(cc grpc.ClientConnInterface) PaymentAdminClient {
	return &paymentAdminClient{cc}
}

func (c *paymentAdminClient) ListPayments(ctx context.Context, in *AdminListPaymentsRequest, opts ...grpc.CallOption) (*AdminListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPaymentsResponse)
	err := c.cc.Invoke(ctx, PaymentAdmin_ListPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentAdminClient) GetPayment(ctx context.Context, in *AdminGetPaymentRequest, opts ...grpc.CallOption) (*AdminPaymentDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPaymentDetailResponse)
	err := c.cc.Invoke(ctx, PaymentAdmin_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentAdminServer is the server API for PaymentAdmin service.
// All implementations must embed UnimplementedPaymentAdminServer
// for forward compatibility.
//
// *
// 管理后台支付服务
// 提供支付记录查询等功能
type PaymentAdminServer interface {
	// ListPayments - 支付列表查询
	ListPayments(context.Context, *AdminListPaymentsRequest) (*AdminListPaymentsResponse, error)
	// GetPayment - 支付详情查询
	GetPayment(context.Context, *AdminGetPaymentRequest) (*AdminPaymentDetailResponse, error)
	mustEmbedUnimplementedPaymentAdminServer()
}

// UnimplementedPaymentAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentAdminServer struct{}

func (UnimplementedPaymentAdminServer) ListPayments(context.Context, *AdminListPaymentsRequest) (*AdminListPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPayments not implemented")
}
func (UnimplementedPaymentAdminServer) GetPayment(context.Context, *AdminGetPaymentRequest) (*AdminPaymentDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentAdminServer) mustEmbedUnimplementedPaymentAdminServer() {}
func (UnimplementedPaymentAdminServer) testEmbeddedByValue()                      {}

// UnsafePaymentAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentAdminServer will
// result in compilation errors.
type UnsafePaymentAdminServer interface {
	mustEmbedUnimplementedPaymentAdminServer()
}

func RegisterPaymentAdminServer(s grpc.ServiceRegistrar, srv PaymentAdminServer) {
	// If the following call pancis, it indicates UnimplementedPaymentAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentAdmin_ServiceDesc, srv)
}

func _PaymentAdmin_ListPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAdminServer).ListPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentAdmin_ListPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAdminServer).ListPayments(ctx, req.(*AdminListPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentAdmin_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAdminServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentAdmin_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAdminServer).GetPayment(ctx, req.(*AdminGetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentAdmin_ServiceDesc is the grpc.ServiceDesc for PaymentAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentAdmin",
	HandlerType: (*PaymentAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPayments",
			Handler:    _PaymentAdmin_ListPayments_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _PaymentAdmin_GetPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/payment/rpc/payment.proto",
}

const (
	PaymentInternal_Refund_FullMethodName                = "/payment.PaymentInternal/Refund"
	PaymentInternal_QueryRefund_FullMethodName           = "/payment.PaymentInternal/QueryRefund"
	PaymentInternal_HandlePaymentCallback_FullMethodName = "/payment.PaymentInternal/HandlePaymentCallback"
	PaymentInternal_HandleRefundCallback_FullMethodName  = "/payment.PaymentInternal/HandleRefundCallback"
)

// PaymentInternalClient is the client API for PaymentInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// 内部微服务调用接口
// 供 Order、Marketing 等服务调用
type PaymentInternalClient interface {
	// Refund - 执行退款（Order 服务售后审核通过后调用）
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
	// QueryRefund - 查询退款状态
	QueryRefund(ctx context.Context, in *QueryRefundRequest, opts ...grpc.CallOption) (*QueryRefundResponse, error)
	// HandlePaymentCallback - 处理支付回调（第三方支付平台回调）
	HandlePaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error)
	// HandleRefundCallback - 处理退款回调（第三方支付平台回调）
	HandleRefundCallback(ctx context.Context, in *RefundCallbackRequest, opts ...grpc.CallOption) (*RefundCallbackResponse, error)
}

type paymentInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentInternalClient(cc grpc.ClientConnInterface) PaymentInternalClient {
	return &paymentInternalClient{cc}
}

func (c *paymentInternalClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, PaymentInternal_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentInternalClient) QueryRefund(ctx context.Context, in *QueryRefundRequest, opts ...grpc.CallOption) (*QueryRefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRefundResponse)
	err := c.cc.Invoke(ctx, PaymentInternal_QueryRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentInternalClient) HandlePaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentCallbackResponse)
	err := c.cc.Invoke(ctx, PaymentInternal_HandlePaymentCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentInternalClient) HandleRefundCallback(ctx context.Context, in *RefundCallbackRequest, opts ...grpc.CallOption) (*RefundCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundCallbackResponse)
	err := c.cc.Invoke(ctx, PaymentInternal_HandleRefundCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentInternalServer is the server API for PaymentInternal service.
// All implementations must embed UnimplementedPaymentInternalServer
// for forward compatibility.
//
// *
// 内部微服务调用接口
// 供 Order、Marketing 等服务调用
type PaymentInternalServer interface {
	// Refund - 执行退款（Order 服务售后审核通过后调用）
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	// QueryRefund - 查询退款状态
	QueryRefund(context.Context, *QueryRefundRequest) (*QueryRefundResponse, error)
	// HandlePaymentCallback - 处理支付回调（第三方支付平台回调）
	HandlePaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackResponse, error)
	// HandleRefundCallback - 处理退款回调（第三方支付平台回调）
	HandleRefundCallback(context.Context, *RefundCallbackRequest) (*RefundCallbackResponse, error)
	mustEmbedUnimplementedPaymentInternalServer()
}

// UnimplementedPaymentInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentInternalServer struct{}

func (UnimplementedPaymentInternalServer) Refund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedPaymentInternalServer) QueryRefund(context.Context, *QueryRefundRequest) (*QueryRefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRefund not implemented")
}
func (UnimplementedPaymentInternalServer) HandlePaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePaymentCallback not implemented")
}
func (UnimplementedPaymentInternalServer) HandleRefundCallback(context.Context, *RefundCallbackRequest) (*RefundCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleRefundCallback not implemented")
}
func (UnimplementedPaymentInternalServer) mustEmbedUnimplementedPaymentInternalServer() {}
func (UnimplementedPaymentInternalServer) testEmbeddedByValue()                         {}

// UnsafePaymentInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentInternalServer will
// result in compilation errors.
type UnsafePaymentInternalServer interface {
	mustEmbedUnimplementedPaymentInternalServer()
}

func RegisterPaymentInternalServer(s grpc.ServiceRegistrar, srv PaymentInternalServer) {
	// If the following call pancis, it indicates UnimplementedPaymentInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentInternal_ServiceDesc, srv)
}

func _PaymentInternal_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentInternal_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentInternal_QueryRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServer).QueryRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentInternal_QueryRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServer).QueryRefund(ctx, req.(*QueryRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentInternal_HandlePaymentCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServer).HandlePaymentCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentInternal_HandlePaymentCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServer).HandlePaymentCallback(ctx, req.(*PaymentCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentInternal_HandleRefundCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServer).HandleRefundCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentInternal_HandleRefundCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServer).HandleRefundCallback(ctx, req.(*RefundCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentInternal_ServiceDesc is the grpc.ServiceDesc for PaymentInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentInternal",
	HandlerType: (*PaymentInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refund",
			Handler:    _PaymentInternal_Refund_Handler,
		},
		{
			MethodName: "QueryRefund",
			Handler:    _PaymentInternal_QueryRefund_Handler,
		},
		{
			MethodName: "HandlePaymentCallback",
			Handler:    _PaymentInternal_HandlePaymentCallback_Handler,
		},
		{
			MethodName: "HandleRefundCallback",
			Handler:    _PaymentInternal_HandleRefundCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/payment/rpc/payment.proto",
}
