// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: apps/service/payment/rpc/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// 支付方式
type PayType int32

const (
	PayType_PAY_TYPE_UNKNOWN PayType = 0 // 未知支付方式
	PayType_PAY_TYPE_WECHAT  PayType = 1 // 微信支付
	PayType_PAY_TYPE_ALIPAY  PayType = 2 // 支付宝支付
)

// Enum value maps for PayType.
var (
	PayType_name = map[int32]string{
		0: "PAY_TYPE_UNKNOWN",
		1: "PAY_TYPE_WECHAT",
		2: "PAY_TYPE_ALIPAY",
	}
	PayType_value = map[string]int32{
		"PAY_TYPE_UNKNOWN": 0,
		"PAY_TYPE_WECHAT":  1,
		"PAY_TYPE_ALIPAY":  2,
	}
)

func (x PayType) Enum() *PayType {
	p := new(PayType)
	*p = x
	return p
}

func (x PayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_service_payment_rpc_payment_proto_enumTypes[0].Descriptor()
}

func (PayType) Type() protoreflect.EnumType {
	return &file_apps_service_payment_rpc_payment_proto_enumTypes[0]
}

func (x PayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayType.Descriptor instead.
func (PayType) EnumDescriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{0}
}

// *
// 支付状态
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNKNOWN   PaymentStatus = 0 // 未知状态
	PaymentStatus_PAYMENT_STATUS_PENDING   PaymentStatus = 1 // 待支付
	PaymentStatus_PAYMENT_STATUS_SUCCESS   PaymentStatus = 2 // 支付成功
	PaymentStatus_PAYMENT_STATUS_FAILED    PaymentStatus = 3 // 支付失败
	PaymentStatus_PAYMENT_STATUS_REFUNDING PaymentStatus = 4 // 退款中
	PaymentStatus_PAYMENT_STATUS_REFUNDED  PaymentStatus = 5 // 已退款
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNKNOWN",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCESS",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDING",
		5: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNKNOWN":   0,
		"PAYMENT_STATUS_PENDING":   1,
		"PAYMENT_STATUS_SUCCESS":   2,
		"PAYMENT_STATUS_FAILED":    3,
		"PAYMENT_STATUS_REFUNDING": 4,
		"PAYMENT_STATUS_REFUNDED":  5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_service_payment_rpc_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_apps_service_payment_rpc_payment_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{1}
}

// *
// 退款状态
type RefundStatus int32

const (
	RefundStatus_REFUND_STATUS_UNKNOWN    RefundStatus = 0 // 未知状态
	RefundStatus_REFUND_STATUS_PROCESSING RefundStatus = 1 // 处理中
	RefundStatus_REFUND_STATUS_SUCCESS    RefundStatus = 2 // 退款成功
	RefundStatus_REFUND_STATUS_FAILED     RefundStatus = 3 // 退款失败
)

// Enum value maps for RefundStatus.
var (
	RefundStatus_name = map[int32]string{
		0: "REFUND_STATUS_UNKNOWN",
		1: "REFUND_STATUS_PROCESSING",
		2: "REFUND_STATUS_SUCCESS",
		3: "REFUND_STATUS_FAILED",
	}
	RefundStatus_value = map[string]int32{
		"REFUND_STATUS_UNKNOWN":    0,
		"REFUND_STATUS_PROCESSING": 1,
		"REFUND_STATUS_SUCCESS":    2,
		"REFUND_STATUS_FAILED":     3,
	}
)

func (x RefundStatus) Enum() *RefundStatus {
	p := new(RefundStatus)
	*p = x
	return p
}

func (x RefundStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_service_payment_rpc_payment_proto_enumTypes[2].Descriptor()
}

func (RefundStatus) Type() protoreflect.EnumType {
	return &file_apps_service_payment_rpc_payment_proto_enumTypes[2]
}

func (x RefundStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundStatus.Descriptor instead.
func (RefundStatus) EnumDescriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{2}
}

// 空响应体
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{0}
}

// *
// 创建支付请求
type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderSn        string                 `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                       // 订单号
	PayType        PayType                `protobuf:"varint,2,opt,name=pay_type,json=payType,proto3,enum=payment.PayType" json:"pay_type,omitempty"` // 支付方式
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`  // 幂等键（防重复提交）
	ClientIp       string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                    // 客户端IP地址
	ExpireTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`              // 【必填】订单过期时间（由订单服务传入）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreatePaymentRequest) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_PAY_TYPE_UNKNOWN
}

func (x *CreatePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CreatePaymentRequest) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

// *
// 创建支付响应
type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`    // 支付流水号
	PayParams     string                 `protobuf:"bytes,2,opt,name=pay_params,json=payParams,proto3" json:"pay_params,omitempty"`    // 支付参数（JSON格式，前端直接调用第三方支付SDK）
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                          // 支付金额（单位：分）
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 支付过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *CreatePaymentResponse) GetPayParams() string {
	if x != nil {
		return x.PayParams
	}
	return ""
}

func (x *CreatePaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentResponse) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

// *
// 查询支付状态请求
type QueryPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"` // 支付流水号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentRequest) Reset() {
	*x = QueryPaymentRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentRequest) ProtoMessage() {}

func (x *QueryPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPaymentRequest) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

// *
// 查询支付状态响应
type QueryPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`      // 支付流水号
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`            // 订单号
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"` // 支付状态
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                            // 支付金额（单位：分）
	PayTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`            // 支付成功时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentResponse) Reset() {
	*x = QueryPaymentResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentResponse) ProtoMessage() {}

func (x *QueryPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentResponse.ProtoReflect.Descriptor instead.
func (*QueryPaymentResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{4}
}

func (x *QueryPaymentResponse) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *QueryPaymentResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *QueryPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNKNOWN
}

func (x *QueryPaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QueryPaymentResponse) GetPayTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PayTime
	}
	return nil
}

// *
// 获取支付详情请求
type GetPaymentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"` // 支付流水号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailRequest) Reset() {
	*x = GetPaymentDetailRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailRequest) ProtoMessage() {}

func (x *GetPaymentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentDetailRequest) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

// *
// 获取支付详情响应
type GetPaymentDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn      string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`                  // 支付流水号
	OrderSn        string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                        // 订单号
	UserId         uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // 用户ID
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                        // 支付金额（单位：分）
	PayType        PayType                `protobuf:"varint,5,opt,name=pay_type,json=payType,proto3,enum=payment.PayType" json:"pay_type,omitempty"`  // 支付方式
	Status         PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`             // 支付状态
	ChannelOrderSn string                 `protobuf:"bytes,7,opt,name=channel_order_sn,json=channelOrderSn,proto3" json:"channel_order_sn,omitempty"` // 第三方支付平台订单号
	TransactionId  string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`      // 第三方支付交易流水号
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // 创建时间
	PayTime        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`                       // 支付成功时间
	ErrorMsg       string                 `protobuf:"bytes,11,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                    // 错误信息（失败时）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentDetailResponse) Reset() {
	*x = GetPaymentDetailResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailResponse) ProtoMessage() {}

func (x *GetPaymentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentDetailResponse) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *GetPaymentDetailResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *GetPaymentDetailResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPaymentDetailResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPaymentDetailResponse) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_PAY_TYPE_UNKNOWN
}

func (x *GetPaymentDetailResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNKNOWN
}

func (x *GetPaymentDetailResponse) GetChannelOrderSn() string {
	if x != nil {
		return x.ChannelOrderSn
	}
	return ""
}

func (x *GetPaymentDetailResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetPaymentDetailResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetPaymentDetailResponse) GetPayTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PayTime
	}
	return nil
}

func (x *GetPaymentDetailResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// *
// 退款请求（内部 RPC）
type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundSn      string                 `protobuf:"bytes,1,opt,name=refund_sn,json=refundSn,proto3" json:"refund_sn,omitempty"`                    // 退款单号（业务唯一标识，幂等键）
	PaymentSn     string                 `protobuf:"bytes,2,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`                 // 原支付流水号
	OrderSn       string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                       // 原订单号
	AfterSaleId   uint64                 `protobuf:"varint,4,opt,name=after_sale_id,json=afterSaleId,proto3" json:"after_sale_id,omitempty"`        // 售后单ID
	RefundAmount  int64                  `protobuf:"varint,5,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`       // 退款金额（单位：分）
	PayType       PayType                `protobuf:"varint,6,opt,name=pay_type,json=payType,proto3,enum=payment.PayType" json:"pay_type,omitempty"` // 原支付方式
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`                                        // 退款原因
	Operator      string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`                                    // 操作人（管理员ID或系统）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{7}
}

func (x *RefundRequest) GetRefundSn() string {
	if x != nil {
		return x.RefundSn
	}
	return ""
}

func (x *RefundRequest) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *RefundRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *RefundRequest) GetAfterSaleId() uint64 {
	if x != nil {
		return x.AfterSaleId
	}
	return 0
}

func (x *RefundRequest) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *RefundRequest) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_PAY_TYPE_UNKNOWN
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// *
// 退款响应
type RefundResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RefundSn           string                 `protobuf:"bytes,1,opt,name=refund_sn,json=refundSn,proto3" json:"refund_sn,omitempty"`                                   // 退款单号
	ThirdPartyRefundNo string                 `protobuf:"bytes,2,opt,name=third_party_refund_no,json=thirdPartyRefundNo,proto3" json:"third_party_refund_no,omitempty"` // 第三方支付平台退款流水号
	Status             RefundStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=payment.RefundStatus" json:"status,omitempty"`                            // 退款状态
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{8}
}

func (x *RefundResponse) GetRefundSn() string {
	if x != nil {
		return x.RefundSn
	}
	return ""
}

func (x *RefundResponse) GetThirdPartyRefundNo() string {
	if x != nil {
		return x.ThirdPartyRefundNo
	}
	return ""
}

func (x *RefundResponse) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNKNOWN
}

// *
// 查询退款状态请求
type QueryRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundSn      string                 `protobuf:"bytes,1,opt,name=refund_sn,json=refundSn,proto3" json:"refund_sn,omitempty"` // 退款单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRefundRequest) Reset() {
	*x = QueryRefundRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRefundRequest) ProtoMessage() {}

func (x *QueryRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRefundRequest.ProtoReflect.Descriptor instead.
func (*QueryRefundRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRefundRequest) GetRefundSn() string {
	if x != nil {
		return x.RefundSn
	}
	return ""
}

// *
// 查询退款状态响应
type QueryRefundResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RefundSn           string                 `protobuf:"bytes,1,opt,name=refund_sn,json=refundSn,proto3" json:"refund_sn,omitempty"`                                   // 退款单号
	PaymentSn          string                 `protobuf:"bytes,2,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`                                // 原支付流水号
	OrderSn            string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                                      // 原订单号
	AfterSaleId        uint64                 `protobuf:"varint,4,opt,name=after_sale_id,json=afterSaleId,proto3" json:"after_sale_id,omitempty"`                       // 售后单ID
	RefundAmount       int64                  `protobuf:"varint,5,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`                      // 退款金额（单位：分）
	Status             RefundStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=payment.RefundStatus" json:"status,omitempty"`                            // 退款状态
	ThirdPartyRefundNo string                 `protobuf:"bytes,7,opt,name=third_party_refund_no,json=thirdPartyRefundNo,proto3" json:"third_party_refund_no,omitempty"` // 第三方退款流水号
	RefundTime         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=refund_time,json=refundTime,proto3" json:"refund_time,omitempty"`                             // 退款成功时间
	ErrorMsg           string                 `protobuf:"bytes,9,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                                   // 错误信息（失败时）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryRefundResponse) Reset() {
	*x = QueryRefundResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRefundResponse) ProtoMessage() {}

func (x *QueryRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRefundResponse.ProtoReflect.Descriptor instead.
func (*QueryRefundResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRefundResponse) GetRefundSn() string {
	if x != nil {
		return x.RefundSn
	}
	return ""
}

func (x *QueryRefundResponse) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *QueryRefundResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *QueryRefundResponse) GetAfterSaleId() uint64 {
	if x != nil {
		return x.AfterSaleId
	}
	return 0
}

func (x *QueryRefundResponse) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *QueryRefundResponse) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNKNOWN
}

func (x *QueryRefundResponse) GetThirdPartyRefundNo() string {
	if x != nil {
		return x.ThirdPartyRefundNo
	}
	return ""
}

func (x *QueryRefundResponse) GetRefundTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundTime
	}
	return nil
}

func (x *QueryRefundResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// *
// 支付回调请求（第三方支付平台回调）
type PaymentCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`          // 支付流水号
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                // 订单号
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`                               // 支付渠道：wechat/alipay
	RawData       string                 `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                // 回调原始数据（JSON格式）
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                           // 签名
	CallbackTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=callback_time,json=callbackTime,proto3" json:"callback_time,omitempty"` // 回调时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentCallbackRequest) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *PaymentCallbackRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PaymentCallbackRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentCallbackRequest) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *PaymentCallbackRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *PaymentCallbackRequest) GetCallbackTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CallbackTime
	}
	return nil
}

// *
// 支付回调响应
type PaymentCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否处理成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackResponse) Reset() {
	*x = PaymentCallbackResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackResponse) ProtoMessage() {}

func (x *PaymentCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackResponse.ProtoReflect.Descriptor instead.
func (*PaymentCallbackResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{12}
}

func (x *PaymentCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentCallbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// *
// 退款回调请求（第三方支付平台回调）
type RefundCallbackRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RefundSn           string                 `protobuf:"bytes,1,opt,name=refund_sn,json=refundSn,proto3" json:"refund_sn,omitempty"`                                        // 退款单号
	PaymentSn          string                 `protobuf:"bytes,2,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`                                     // 原支付流水号
	OrderSn            string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                                           // 原订单号
	Channel            string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`                                                          // 支付渠道：wechat/alipay
	RawData            string                 `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                           // 回调原始数据（JSON格式）
	Signature          string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                                                      // 签名
	RefundStatus       RefundStatus           `protobuf:"varint,7,opt,name=refund_status,json=refundStatus,proto3,enum=payment.RefundStatus" json:"refund_status,omitempty"` // 退款状态
	ThirdPartyRefundNo string                 `protobuf:"bytes,8,opt,name=third_party_refund_no,json=thirdPartyRefundNo,proto3" json:"third_party_refund_no,omitempty"`      // 第三方退款流水号
	CallbackTime       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=callback_time,json=callbackTime,proto3" json:"callback_time,omitempty"`                            // 回调时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefundCallbackRequest) Reset() {
	*x = RefundCallbackRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundCallbackRequest) ProtoMessage() {}

func (x *RefundCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundCallbackRequest.ProtoReflect.Descriptor instead.
func (*RefundCallbackRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{13}
}

func (x *RefundCallbackRequest) GetRefundSn() string {
	if x != nil {
		return x.RefundSn
	}
	return ""
}

func (x *RefundCallbackRequest) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *RefundCallbackRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *RefundCallbackRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RefundCallbackRequest) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *RefundCallbackRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RefundCallbackRequest) GetRefundStatus() RefundStatus {
	if x != nil {
		return x.RefundStatus
	}
	return RefundStatus_REFUND_STATUS_UNKNOWN
}

func (x *RefundCallbackRequest) GetThirdPartyRefundNo() string {
	if x != nil {
		return x.ThirdPartyRefundNo
	}
	return ""
}

func (x *RefundCallbackRequest) GetCallbackTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CallbackTime
	}
	return nil
}

// *
// 退款回调响应
type RefundCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否处理成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundCallbackResponse) Reset() {
	*x = RefundCallbackResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundCallbackResponse) ProtoMessage() {}

func (x *RefundCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundCallbackResponse.ProtoReflect.Descriptor instead.
func (*RefundCallbackResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{14}
}

func (x *RefundCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefundCallbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// *
// 管理后台支付列表请求
type AdminListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`        // 每页条数
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"` // 支付状态（0=全部）
	OrderSn       string                 `protobuf:"bytes,4,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`            // 订单号（模糊搜索）
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`      // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`            // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsRequest) Reset() {
	*x = AdminListPaymentsRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsRequest) ProtoMessage() {}

func (x *AdminListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{15}
}

func (x *AdminListPaymentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNKNOWN
}

func (x *AdminListPaymentsRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *AdminListPaymentsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AdminListPaymentsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// *
// 管理后台支付列表项
type AdminPaymentListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`                 // 支付流水号
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                       // 订单号
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户ID
	UserPhone     string                 `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`                 // 用户手机号
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                       // 支付金额（单位：分）
	PayType       PayType                `protobuf:"varint,6,opt,name=pay_type,json=payType,proto3,enum=payment.PayType" json:"pay_type,omitempty"` // 支付方式
	PayTypeDesc   string                 `protobuf:"bytes,7,opt,name=pay_type_desc,json=payTypeDesc,proto3" json:"pay_type_desc,omitempty"`         // 支付方式描述
	Status        PaymentStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`            // 支付状态
	StatusDesc    string                 `protobuf:"bytes,9,opt,name=status_desc,json=statusDesc,proto3" json:"status_desc,omitempty"`              // 状态描述
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 创建时间
	PayTime       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`                      // 支付成功时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPaymentListItem) Reset() {
	*x = AdminPaymentListItem{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPaymentListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPaymentListItem) ProtoMessage() {}

func (x *AdminPaymentListItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPaymentListItem.ProtoReflect.Descriptor instead.
func (*AdminPaymentListItem) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{16}
}

func (x *AdminPaymentListItem) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *AdminPaymentListItem) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *AdminPaymentListItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminPaymentListItem) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *AdminPaymentListItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdminPaymentListItem) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_PAY_TYPE_UNKNOWN
}

func (x *AdminPaymentListItem) GetPayTypeDesc() string {
	if x != nil {
		return x.PayTypeDesc
	}
	return ""
}

func (x *AdminPaymentListItem) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNKNOWN
}

func (x *AdminPaymentListItem) GetStatusDesc() string {
	if x != nil {
		return x.StatusDesc
	}
	return ""
}

func (x *AdminPaymentListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminPaymentListItem) GetPayTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PayTime
	}
	return nil
}

// *
// 管理后台支付列表响应
type AdminListPaymentsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int64                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总条数
	List          []*AdminPaymentListItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    // 支付列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsResponse) Reset() {
	*x = AdminListPaymentsResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsResponse) ProtoMessage() {}

func (x *AdminListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{17}
}

func (x *AdminListPaymentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminListPaymentsResponse) GetList() []*AdminPaymentListItem {
	if x != nil {
		return x.List
	}
	return nil
}

// *
// 管理后台支付详情请求
type AdminGetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn     string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"` // 支付流水号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetPaymentRequest) Reset() {
	*x = AdminGetPaymentRequest{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetPaymentRequest) ProtoMessage() {}

func (x *AdminGetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetPaymentRequest.ProtoReflect.Descriptor instead.
func (*AdminGetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{18}
}

func (x *AdminGetPaymentRequest) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

// *
// 管理后台支付详情响应
type AdminPaymentDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentSn      string                 `protobuf:"bytes,1,opt,name=payment_sn,json=paymentSn,proto3" json:"payment_sn,omitempty"`                   // 支付流水号
	OrderSn        string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`                         // 订单号
	UserId         uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           // 用户ID
	UserPhone      string                 `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`                   // 用户手机号
	Amount         int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                         // 支付金额（单位：分）
	PayType        PayType                `protobuf:"varint,6,opt,name=pay_type,json=payType,proto3,enum=payment.PayType" json:"pay_type,omitempty"`   // 支付方式
	PayTypeDesc    string                 `protobuf:"bytes,7,opt,name=pay_type_desc,json=payTypeDesc,proto3" json:"pay_type_desc,omitempty"`           // 支付方式描述
	Status         PaymentStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`              // 支付状态
	StatusDesc     string                 `protobuf:"bytes,9,opt,name=status_desc,json=statusDesc,proto3" json:"status_desc,omitempty"`                // 状态描述
	ChannelOrderSn string                 `protobuf:"bytes,10,opt,name=channel_order_sn,json=channelOrderSn,proto3" json:"channel_order_sn,omitempty"` // 第三方支付平台订单号
	TransactionId  string                 `protobuf:"bytes,11,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`      // 第三方支付交易流水号
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // 创建时间
	PayTime        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`                        // 支付成功时间
	CallbackData   string                 `protobuf:"bytes,14,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`         // 支付回调数据快照（JSON格式）
	ErrorMsg       string                 `protobuf:"bytes,15,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                     // 错误信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminPaymentDetailResponse) Reset() {
	*x = AdminPaymentDetailResponse{}
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPaymentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPaymentDetailResponse) ProtoMessage() {}

func (x *AdminPaymentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_payment_rpc_payment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPaymentDetailResponse.ProtoReflect.Descriptor instead.
func (*AdminPaymentDetailResponse) Descriptor() ([]byte, []int) {
	return file_apps_service_payment_rpc_payment_proto_rawDescGZIP(), []int{19}
}

func (x *AdminPaymentDetailResponse) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminPaymentDetailResponse) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdminPaymentDetailResponse) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_PAY_TYPE_UNKNOWN
}

func (x *AdminPaymentDetailResponse) GetPayTypeDesc() string {
	if x != nil {
		return x.PayTypeDesc
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNKNOWN
}

func (x *AdminPaymentDetailResponse) GetStatusDesc() string {
	if x != nil {
		return x.StatusDesc
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetChannelOrderSn() string {
	if x != nil {
		return x.ChannelOrderSn
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminPaymentDetailResponse) GetPayTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PayTime
	}
	return nil
}

func (x *AdminPaymentDetailResponse) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *AdminPaymentDetailResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_apps_service_payment_rpc_payment_proto protoreflect.FileDescriptor

const file_apps_service_payment_rpc_payment_proto_rawDesc = "" +
	"\n" +
	"&apps/service/payment/rpc/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xe1\x01\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_sn\x18\x01 \x01(\tR\aorderSn\x12+\n" +
	"\bpay_type\x18\x02 \x01(\x0e2\x10.payment.PayTypeR\apayType\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12;\n" +
	"\vexpire_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\"\xaa\x01\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\x12\x1d\n" +
	"\n" +
	"pay_params\x18\x02 \x01(\tR\tpayParams\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12;\n" +
	"\vexpire_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\"4\n" +
	"\x13QueryPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\"\xcf\x01\n" +
	"\x14QueryPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x125\n" +
	"\bpay_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\apayTime\"8\n" +
	"\x17GetPaymentDetailRequest\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\"\xc2\x03\n" +
	"\x18GetPaymentDetailResponse\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12+\n" +
	"\bpay_type\x18\x05 \x01(\x0e2\x10.payment.PayTypeR\apayType\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12(\n" +
	"\x10channel_order_sn\x18\a \x01(\tR\x0echannelOrderSn\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\bpay_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\apayTime\x12\x1b\n" +
	"\terror_msg\x18\v \x01(\tR\berrorMsg\"\x90\x02\n" +
	"\rRefundRequest\x12\x1b\n" +
	"\trefund_sn\x18\x01 \x01(\tR\brefundSn\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x02 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x03 \x01(\tR\aorderSn\x12\"\n" +
	"\rafter_sale_id\x18\x04 \x01(\x04R\vafterSaleId\x12#\n" +
	"\rrefund_amount\x18\x05 \x01(\x03R\frefundAmount\x12+\n" +
	"\bpay_type\x18\x06 \x01(\x0e2\x10.payment.PayTypeR\apayType\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\"\x8f\x01\n" +
	"\x0eRefundResponse\x12\x1b\n" +
	"\trefund_sn\x18\x01 \x01(\tR\brefundSn\x121\n" +
	"\x15third_party_refund_no\x18\x02 \x01(\tR\x12thirdPartyRefundNo\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.payment.RefundStatusR\x06status\"1\n" +
	"\x12QueryRefundRequest\x12\x1b\n" +
	"\trefund_sn\x18\x01 \x01(\tR\brefundSn\"\xf1\x02\n" +
	"\x13QueryRefundResponse\x12\x1b\n" +
	"\trefund_sn\x18\x01 \x01(\tR\brefundSn\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x02 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x03 \x01(\tR\aorderSn\x12\"\n" +
	"\rafter_sale_id\x18\x04 \x01(\x04R\vafterSaleId\x12#\n" +
	"\rrefund_amount\x18\x05 \x01(\x03R\frefundAmount\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.payment.RefundStatusR\x06status\x121\n" +
	"\x15third_party_refund_no\x18\a \x01(\tR\x12thirdPartyRefundNo\x12;\n" +
	"\vrefund_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundTime\x12\x1b\n" +
	"\terror_msg\x18\t \x01(\tR\berrorMsg\"\xe6\x01\n" +
	"\x16PaymentCallbackRequest\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x19\n" +
	"\braw_data\x18\x04 \x01(\tR\arawData\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12?\n" +
	"\rcallback_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcallbackTime\"M\n" +
	"\x17PaymentCallbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf1\x02\n" +
	"\x15RefundCallbackRequest\x12\x1b\n" +
	"\trefund_sn\x18\x01 \x01(\tR\brefundSn\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x02 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x19\n" +
	"\braw_data\x18\x05 \x01(\tR\arawData\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12:\n" +
	"\rrefund_status\x18\a \x01(\x0e2\x15.payment.RefundStatusR\frefundStatus\x121\n" +
	"\x15third_party_refund_no\x18\b \x01(\tR\x12thirdPartyRefundNo\x12?\n" +
	"\rcallback_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fcallbackTime\"L\n" +
	"\x16RefundCallbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x02\n" +
	"\x18AdminListPaymentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x19\n" +
	"\border_sn\x18\x04 \x01(\tR\aorderSn\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xb4\x03\n" +
	"\x14AdminPaymentListItem\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x04 \x01(\tR\tuserPhone\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12+\n" +
	"\bpay_type\x18\x06 \x01(\x0e2\x10.payment.PayTypeR\apayType\x12\"\n" +
	"\rpay_type_desc\x18\a \x01(\tR\vpayTypeDesc\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x1f\n" +
	"\vstatus_desc\x18\t \x01(\tR\n" +
	"statusDesc\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\bpay_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\apayTime\"d\n" +
	"\x19AdminListPaymentsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x121\n" +
	"\x04list\x18\x02 \x03(\v2\x1d.payment.AdminPaymentListItemR\x04list\"7\n" +
	"\x16AdminGetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\"\xcd\x04\n" +
	"\x1aAdminPaymentDetailResponse\x12\x1d\n" +
	"\n" +
	"payment_sn\x18\x01 \x01(\tR\tpaymentSn\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x04 \x01(\tR\tuserPhone\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12+\n" +
	"\bpay_type\x18\x06 \x01(\x0e2\x10.payment.PayTypeR\apayType\x12\"\n" +
	"\rpay_type_desc\x18\a \x01(\tR\vpayTypeDesc\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x1f\n" +
	"\vstatus_desc\x18\t \x01(\tR\n" +
	"statusDesc\x12(\n" +
	"\x10channel_order_sn\x18\n" +
	" \x01(\tR\x0echannelOrderSn\x12%\n" +
	"\x0etransaction_id\x18\v \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\bpay_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\apayTime\x12#\n" +
	"\rcallback_data\x18\x0e \x01(\tR\fcallbackData\x12\x1b\n" +
	"\terror_msg\x18\x0f \x01(\tR\berrorMsg*I\n" +
	"\aPayType\x12\x14\n" +
	"\x10PAY_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPAY_TYPE_WECHAT\x10\x01\x12\x13\n" +
	"\x0fPAY_TYPE_ALIPAY\x10\x02*\xb9\x01\n" +
	"\rPaymentStatus\x12\x1a\n" +
	"\x16PAYMENT_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18PAYMENT_STATUS_REFUNDING\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x05*|\n" +
	"\fRefundStatus\x12\x19\n" +
	"\x15REFUND_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18REFUND_STATUS_PROCESSING\x10\x01\x12\x19\n" +
	"\x15REFUND_STATUS_SUCCESS\x10\x02\x12\x18\n" +
	"\x14REFUND_STATUS_FAILED\x10\x032\xff\x01\n" +
	"\aPayment\x12N\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponse\x12K\n" +
	"\fQueryPayment\x12\x1c.payment.QueryPaymentRequest\x1a\x1d.payment.QueryPaymentResponse\x12W\n" +
	"\x10GetPaymentDetail\x12 .payment.GetPaymentDetailRequest\x1a!.payment.GetPaymentDetailResponse2\xb9\x01\n" +
	"\fPaymentAdmin\x12U\n" +
	"\fListPayments\x12!.payment.AdminListPaymentsRequest\x1a\".payment.AdminListPaymentsResponse\x12R\n" +
	"\n" +
	"GetPayment\x12\x1f.payment.AdminGetPaymentRequest\x1a#.payment.AdminPaymentDetailResponse2\xcb\x02\n" +
	"\x0fPaymentInternal\x129\n" +
	"\x06Refund\x12\x16.payment.RefundRequest\x1a\x17.payment.RefundResponse\x12H\n" +
	"\vQueryRefund\x12\x1b.payment.QueryRefundRequest\x1a\x1c.payment.QueryRefundResponse\x12Z\n" +
	"\x15HandlePaymentCallback\x12\x1f.payment.PaymentCallbackRequest\x1a .payment.PaymentCallbackResponse\x12W\n" +
	"\x14HandleRefundCallback\x12\x1e.payment.RefundCallbackRequest\x1a\x1f.payment.RefundCallbackResponseB\vZ\t./paymentb\x06proto3"

var (
	file_apps_service_payment_rpc_payment_proto_rawDescOnce sync.Once
	file_apps_service_payment_rpc_payment_proto_rawDescData []byte
)

func file_apps_service_payment_rpc_payment_proto_rawDescGZIP() []byte {
	file_apps_service_payment_rpc_payment_proto_rawDescOnce.Do(func() {
		file_apps_service_payment_rpc_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_service_payment_rpc_payment_proto_rawDesc), len(file_apps_service_payment_rpc_payment_proto_rawDesc)))
	})
	return file_apps_service_payment_rpc_payment_proto_rawDescData
}

var file_apps_service_payment_rpc_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_apps_service_payment_rpc_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_apps_service_payment_rpc_payment_proto_goTypes = []any{
	(PayType)(0),                       // 0: payment.PayType
	(PaymentStatus)(0),                 // 1: payment.PaymentStatus
	(RefundStatus)(0),                  // 2: payment.RefundStatus
	(*Empty)(nil),                      // 3: payment.Empty
	(*CreatePaymentRequest)(nil),       // 4: payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),      // 5: payment.CreatePaymentResponse
	(*QueryPaymentRequest)(nil),        // 6: payment.QueryPaymentRequest
	(*QueryPaymentResponse)(nil),       // 7: payment.QueryPaymentResponse
	(*GetPaymentDetailRequest)(nil),    // 8: payment.GetPaymentDetailRequest
	(*GetPaymentDetailResponse)(nil),   // 9: payment.GetPaymentDetailResponse
	(*RefundRequest)(nil),              // 10: payment.RefundRequest
	(*RefundResponse)(nil),             // 11: payment.RefundResponse
	(*QueryRefundRequest)(nil),         // 12: payment.QueryRefundRequest
	(*QueryRefundResponse)(nil),        // 13: payment.QueryRefundResponse
	(*PaymentCallbackRequest)(nil),     // 14: payment.PaymentCallbackRequest
	(*PaymentCallbackResponse)(nil),    // 15: payment.PaymentCallbackResponse
	(*RefundCallbackRequest)(nil),      // 16: payment.RefundCallbackRequest
	(*RefundCallbackResponse)(nil),     // 17: payment.RefundCallbackResponse
	(*AdminListPaymentsRequest)(nil),   // 18: payment.AdminListPaymentsRequest
	(*AdminPaymentListItem)(nil),       // 19: payment.AdminPaymentListItem
	(*AdminListPaymentsResponse)(nil),  // 20: payment.AdminListPaymentsResponse
	(*AdminGetPaymentRequest)(nil),     // 21: payment.AdminGetPaymentRequest
	(*AdminPaymentDetailResponse)(nil), // 22: payment.AdminPaymentDetailResponse
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
}
var file_apps_service_payment_rpc_payment_proto_depIdxs = []int32{
	0,  // 0: payment.CreatePaymentRequest.pay_type:type_name -> payment.PayType
	23, // 1: payment.CreatePaymentRequest.expire_time:type_name -> google.protobuf.Timestamp
	23, // 2: payment.CreatePaymentResponse.expire_time:type_name -> google.protobuf.Timestamp
	1,  // 3: payment.QueryPaymentResponse.status:type_name -> payment.PaymentStatus
	23, // 4: payment.QueryPaymentResponse.pay_time:type_name -> google.protobuf.Timestamp
	0,  // 5: payment.GetPaymentDetailResponse.pay_type:type_name -> payment.PayType
	1,  // 6: payment.GetPaymentDetailResponse.status:type_name -> payment.PaymentStatus
	23, // 7: payment.GetPaymentDetailResponse.created_at:type_name -> google.protobuf.Timestamp
	23, // 8: payment.GetPaymentDetailResponse.pay_time:type_name -> google.protobuf.Timestamp
	0,  // 9: payment.RefundRequest.pay_type:type_name -> payment.PayType
	2,  // 10: payment.RefundResponse.status:type_name -> payment.RefundStatus
	2,  // 11: payment.QueryRefundResponse.status:type_name -> payment.RefundStatus
	23, // 12: payment.QueryRefundResponse.refund_time:type_name -> google.protobuf.Timestamp
	23, // 13: payment.PaymentCallbackRequest.callback_time:type_name -> google.protobuf.Timestamp
	2,  // 14: payment.RefundCallbackRequest.refund_status:type_name -> payment.RefundStatus
	23, // 15: payment.RefundCallbackRequest.callback_time:type_name -> google.protobuf.Timestamp
	1,  // 16: payment.AdminListPaymentsRequest.status:type_name -> payment.PaymentStatus
	23, // 17: payment.AdminListPaymentsRequest.start_time:type_name -> google.protobuf.Timestamp
	23, // 18: payment.AdminListPaymentsRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 19: payment.AdminPaymentListItem.pay_type:type_name -> payment.PayType
	1,  // 20: payment.AdminPaymentListItem.status:type_name -> payment.PaymentStatus
	23, // 21: payment.AdminPaymentListItem.created_at:type_name -> google.protobuf.Timestamp
	23, // 22: payment.AdminPaymentListItem.pay_time:type_name -> google.protobuf.Timestamp
	19, // 23: payment.AdminListPaymentsResponse.list:type_name -> payment.AdminPaymentListItem
	0,  // 24: payment.AdminPaymentDetailResponse.pay_type:type_name -> payment.PayType
	1,  // 25: payment.AdminPaymentDetailResponse.status:type_name -> payment.PaymentStatus
	23, // 26: payment.AdminPaymentDetailResponse.created_at:type_name -> google.protobuf.Timestamp
	23, // 27: payment.AdminPaymentDetailResponse.pay_time:type_name -> google.protobuf.Timestamp
	4,  // 28: payment.Payment.CreatePayment:input_type -> payment.CreatePaymentRequest
	6,  // 29: payment.Payment.QueryPayment:input_type -> payment.QueryPaymentRequest
	8,  // 30: payment.Payment.GetPaymentDetail:input_type -> payment.GetPaymentDetailRequest
	18, // 31: payment.PaymentAdmin.ListPayments:input_type -> payment.AdminListPaymentsRequest
	21, // 32: payment.PaymentAdmin.GetPayment:input_type -> payment.AdminGetPaymentRequest
	10, // 33: payment.PaymentInternal.Refund:input_type -> payment.RefundRequest
	12, // 34: payment.PaymentInternal.QueryRefund:input_type -> payment.QueryRefundRequest
	14, // 35: payment.PaymentInternal.HandlePaymentCallback:input_type -> payment.PaymentCallbackRequest
	16, // 36: payment.PaymentInternal.HandleRefundCallback:input_type -> payment.RefundCallbackRequest
	5,  // 37: payment.Payment.CreatePayment:output_type -> payment.CreatePaymentResponse
	7,  // 38: payment.Payment.QueryPayment:output_type -> payment.QueryPaymentResponse
	9,  // 39: payment.Payment.GetPaymentDetail:output_type -> payment.GetPaymentDetailResponse
	20, // 40: payment.PaymentAdmin.ListPayments:output_type -> payment.AdminListPaymentsResponse
	22, // 41: payment.PaymentAdmin.GetPayment:output_type -> payment.AdminPaymentDetailResponse
	11, // 42: payment.PaymentInternal.Refund:output_type -> payment.RefundResponse
	13, // 43: payment.PaymentInternal.QueryRefund:output_type -> payment.QueryRefundResponse
	15, // 44: payment.PaymentInternal.HandlePaymentCallback:output_type -> payment.PaymentCallbackResponse
	17, // 45: payment.PaymentInternal.HandleRefundCallback:output_type -> payment.RefundCallbackResponse
	37, // [37:46] is the sub-list for method output_type
	28, // [28:37] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_apps_service_payment_rpc_payment_proto_init() }
func file_apps_service_payment_rpc_payment_proto_init() {
	if File_apps_service_payment_rpc_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_service_payment_rpc_payment_proto_rawDesc), len(file_apps_service_payment_rpc_payment_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_apps_service_payment_rpc_payment_proto_goTypes,
		DependencyIndexes: file_apps_service_payment_rpc_payment_proto_depIdxs,
		EnumInfos:         file_apps_service_payment_rpc_payment_proto_enumTypes,
		MessageInfos:      file_apps_service_payment_rpc_payment_proto_msgTypes,
	}.Build()
	File_apps_service_payment_rpc_payment_proto = out.File
	file_apps_service_payment_rpc_payment_proto_goTypes = nil
	file_apps_service_payment_rpc_payment_proto_depIdxs = nil
}
