// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressFieldNames          = builder.RawFieldNames(&UserAddress{})
	userAddressRows                = strings.Join(userAddressFieldNames, ",")
	userAddressRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAddressRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAddressModel interface {
		Insert(ctx context.Context, data *UserAddress) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAddress, error)
		Update(ctx context.Context, data *UserAddress) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAddressModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAddress struct {
		Id            uint64    `db:"id"`             // 地址ID
		UserId        uint64    `db:"user_id"`        // 用户ID
		Tag           string    `db:"tag"`            // 地址标签：HOME-家，OFFICE-公司，SCHOOL-学校
		ReceiverName  string    `db:"receiver_name"`  // 收货人姓名
		ReceiverPhone string    `db:"receiver_phone"` // 收货人电话
		IsDefault     int64     `db:"is_default"`     // 是否默认地址：0-否，1-是
		Info          string    `db:"info"`           // 地址详细信息：{province-省份, city-城市, district-区县, detail-详细地址, postal_code-邮编}
		CreatedAt     time.Time `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`     // 更新时间
	}
)

func newUserAddressModel(conn sqlx.SqlConn) *defaultUserAddressModel {
	return &defaultUserAddressModel{
		conn:  conn,
		table: "`user_address`",
	}
}

func (m *defaultUserAddressModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAddressModel) FindOne(ctx context.Context, id uint64) (*UserAddress, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressRows, m.table)
	var resp UserAddress
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressModel) Insert(ctx context.Context, data *UserAddress) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userAddressRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Tag, data.ReceiverName, data.ReceiverPhone, data.IsDefault, data.Info)
	return ret, err
}

func (m *defaultUserAddressModel) Update(ctx context.Context, data *UserAddress) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAddressRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Tag, data.ReceiverName, data.ReceiverPhone, data.IsDefault, data.Info, data.Id)
	return err
}

func (m *defaultUserAddressModel) tableName() string {
	return m.table
}
