// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLoginLogFieldNames          = builder.RawFieldNames(&UserLoginLog{})
	userLoginLogRows                = strings.Join(userLoginLogFieldNames, ",")
	userLoginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(userLoginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userLoginLogRowsWithPlaceHolder = strings.Join(stringx.Remove(userLoginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userLoginLogModel interface {
		Insert(ctx context.Context, data *UserLoginLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserLoginLog, error)
		Update(ctx context.Context, data *UserLoginLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserLoginLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserLoginLog struct {
		Id         uint64    `db:"id"`          // 日志ID
		UserId     uint64    `db:"user_id"`     // 用户ID
		LoginType  string    `db:"login_type"`  // 登录方式：password-密码登录，captcha-短信登录
		LoginIp    string    `db:"login_ip"`    // 登录IP地址
		UserAgent  string    `db:"user_agent"`  // 用户代理（浏览器信息）
		Status     int64     `db:"status"`      // 登录状态：1-成功，2-失败
		FailReason string    `db:"fail_reason"` // 失败原因
		CreatedAt  time.Time `db:"created_at"`  // 登录时间
	}
)

func newUserLoginLogModel(conn sqlx.SqlConn) *defaultUserLoginLogModel {
	return &defaultUserLoginLogModel{
		conn:  conn,
		table: "`user_login_log`",
	}
}

func (m *defaultUserLoginLogModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserLoginLogModel) FindOne(ctx context.Context, id uint64) (*UserLoginLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userLoginLogRows, m.table)
	var resp UserLoginLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLoginLogModel) Insert(ctx context.Context, data *UserLoginLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userLoginLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.LoginType, data.LoginIp, data.UserAgent, data.Status, data.FailReason)
	return ret, err
}

func (m *defaultUserLoginLogModel) Update(ctx context.Context, data *UserLoginLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userLoginLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.LoginType, data.LoginIp, data.UserAgent, data.Status, data.FailReason, data.Id)
	return err
}

func (m *defaultUserLoginLogModel) tableName() string {
	return m.table
}
