// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package admincoupon

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CouponDetailResp = admin.CouponDetailResp
	IdReq            = admin.IdReq

	AdminCoupon interface {
		GetCouponDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CouponDetailResp, error)
	}

	defaultAdminCoupon struct {
		cli zrpc.Client
	}
)

func NewAdminCoupon(cli zrpc.Client) AdminCoupon {
	return &defaultAdminCoupon{
		cli: cli,
	}
}

func (m *defaultAdminCoupon) GetCouponDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CouponDetailResp, error) {
	client := admin.NewAdminCouponClient(m.cli.Conn())
	return client.GetCouponDetail(ctx, in, opts...)
}
