// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package admincoupon

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminCreateCouponReq       = admin.AdminCreateCouponReq
	AdminListCouponsReq        = admin.AdminListCouponsReq
	AdminListCouponsResp       = admin.AdminListCouponsResp
	AdminUpdateCouponReq       = admin.AdminUpdateCouponReq
	AdminUpdateCouponStatusReq = admin.AdminUpdateCouponStatusReq
	CouponDetailResp           = admin.CouponDetailResp
	Empty                      = admin.Empty
	IdReq                      = admin.IdReq

	AdminCoupon interface {
		GetCouponDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CouponDetailResp, error)
		ListCoupons(ctx context.Context, in *AdminListCouponsReq, opts ...grpc.CallOption) (*AdminListCouponsResp, error)
		CreateCoupon(ctx context.Context, in *AdminCreateCouponReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateCoupon(ctx context.Context, in *AdminUpdateCouponReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateCouponStatus(ctx context.Context, in *AdminUpdateCouponStatusReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAdminCoupon struct {
		cli zrpc.Client
	}
)

func NewAdminCoupon(cli zrpc.Client) AdminCoupon {
	return &defaultAdminCoupon{
		cli: cli,
	}
}

func (m *defaultAdminCoupon) GetCouponDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CouponDetailResp, error) {
	client := admin.NewAdminCouponClient(m.cli.Conn())
	return client.GetCouponDetail(ctx, in, opts...)
}

func (m *defaultAdminCoupon) ListCoupons(ctx context.Context, in *AdminListCouponsReq, opts ...grpc.CallOption) (*AdminListCouponsResp, error) {
	client := admin.NewAdminCouponClient(m.cli.Conn())
	return client.ListCoupons(ctx, in, opts...)
}

func (m *defaultAdminCoupon) CreateCoupon(ctx context.Context, in *AdminCreateCouponReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminCouponClient(m.cli.Conn())
	return client.CreateCoupon(ctx, in, opts...)
}

func (m *defaultAdminCoupon) UpdateCoupon(ctx context.Context, in *AdminUpdateCouponReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminCouponClient(m.cli.Conn())
	return client.UpdateCoupon(ctx, in, opts...)
}

func (m *defaultAdminCoupon) UpdateCouponStatus(ctx context.Context, in *AdminUpdateCouponStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminCouponClient(m.cli.Conn())
	return client.UpdateCouponStatus(ctx, in, opts...)
}
