Name: product.rpc
ListenOn: 0.0.0.0:8082

Etcd:
  Hosts:
    - ${ETCD_HOST}:${ETCD_PORT}
  Key: product.rpc

DB:
  DSN: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/shop_product?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 50
  MaxOpenConns: 200

RDB:
  Addr: ${REDIS_HOST}:${REDIS_PORT}
  RedisPassword: "${REDIS_PASSWORD}"
  RedisDB: 0
  RedisPoolSize: 100
  RedisMinIdleConns: 20

SearchRpc:
  Etcd:
    Hosts:
      - ${ETCD_HOST}:${ETCD_PORT}
    Key: search.rpc
  Timeout: 5000
