// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: admin.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/internal/logic/admin"
	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// 登录认证
func (s *AdminServer) AdminLogin(ctx context.Context, in *admin.AdminLoginReq) (*admin.AdminLoginResp, error) {
	l := adminlogic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}

func (s *AdminServer) GetCurrentAdmin(ctx context.Context, in *admin.Empty) (*admin.GetCurrentAdminResp, error) {
	l := adminlogic.NewGetCurrentAdminLogic(ctx, s.svcCtx)
	return l.GetCurrentAdmin(in)
}

func (s *AdminServer) UpdatePassword(ctx context.Context, in *admin.UpdatePasswordReq) (*admin.Empty, error) {
	l := adminlogic.NewUpdatePasswordLogic(ctx, s.svcCtx)
	return l.UpdatePassword(in)
}

// 管理员 CRUD
func (s *AdminServer) CreateAdmin(ctx context.Context, in *admin.CreateAdminReq) (*admin.Empty, error) {
	l := adminlogic.NewCreateAdminLogic(ctx, s.svcCtx)
	return l.CreateAdmin(in)
}

func (s *AdminServer) UpdateAdmin(ctx context.Context, in *admin.UpdateAdminReq) (*admin.Empty, error) {
	l := adminlogic.NewUpdateAdminLogic(ctx, s.svcCtx)
	return l.UpdateAdmin(in)
}

func (s *AdminServer) DeleteAdmin(ctx context.Context, in *admin.DeleteAdminReq) (*admin.Empty, error) {
	l := adminlogic.NewDeleteAdminLogic(ctx, s.svcCtx)
	return l.DeleteAdmin(in)
}

func (s *AdminServer) GetAdmin(ctx context.Context, in *admin.GetAdminReq) (*admin.GetAdminResp, error) {
	l := adminlogic.NewGetAdminLogic(ctx, s.svcCtx)
	return l.GetAdmin(in)
}

func (s *AdminServer) ListAdmin(ctx context.Context, in *admin.ListAdminReq) (*admin.ListAdminResp, error) {
	l := adminlogic.NewListAdminLogic(ctx, s.svcCtx)
	return l.ListAdmin(in)
}

// 角色查询（只读，角色由系统初始化预置）
func (s *AdminServer) ListRole(ctx context.Context, in *admin.Empty) (*admin.ListRoleResp, error) {
	l := adminlogic.NewListRoleLogic(ctx, s.svcCtx)
	return l.ListRole(in)
}

// 操作日志
func (s *AdminServer) ListAdminLog(ctx context.Context, in *admin.ListAdminLogReq) (*admin.ListAdminLogResp, error) {
	l := adminlogic.NewListAdminLogLogic(ctx, s.svcCtx)
	return l.ListAdminLog(in)
}
