// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: payment.proto

package paymentadmin

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/payment/rpc/types/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminGetPaymentRequest     = payment.AdminGetPaymentRequest
	AdminListPaymentsRequest   = payment.AdminListPaymentsRequest
	AdminListPaymentsResponse  = payment.AdminListPaymentsResponse
	AdminPaymentDetailResponse = payment.AdminPaymentDetailResponse
	AdminPaymentListItem       = payment.AdminPaymentListItem
	CreatePaymentRequest       = payment.CreatePaymentRequest
	CreatePaymentResponse      = payment.CreatePaymentResponse
	Empty                      = payment.Empty
	GetPaymentDetailRequest    = payment.GetPaymentDetailRequest
	GetPaymentDetailResponse   = payment.GetPaymentDetailResponse
	PaymentCallbackRequest     = payment.PaymentCallbackRequest
	PaymentCallbackResponse    = payment.PaymentCallbackResponse
	QueryPaymentRequest        = payment.QueryPaymentRequest
	QueryPaymentResponse       = payment.QueryPaymentResponse
	QueryRefundRequest         = payment.QueryRefundRequest
	QueryRefundResponse        = payment.QueryRefundResponse
	RefundCallbackRequest      = payment.RefundCallbackRequest
	RefundCallbackResponse     = payment.RefundCallbackResponse
	RefundRequest              = payment.RefundRequest
	RefundResponse             = payment.RefundResponse

	PaymentAdmin interface {
		// ListPayments - 支付列表查询
		ListPayments(ctx context.Context, in *AdminListPaymentsRequest, opts ...grpc.CallOption) (*AdminListPaymentsResponse, error)
		// GetPayment - 支付详情查询
		GetPayment(ctx context.Context, in *AdminGetPaymentRequest, opts ...grpc.CallOption) (*AdminPaymentDetailResponse, error)
	}

	defaultPaymentAdmin struct {
		cli zrpc.Client
	}
)

func NewPaymentAdmin(cli zrpc.Client) PaymentAdmin {
	return &defaultPaymentAdmin{
		cli: cli,
	}
}

// ListPayments - 支付列表查询
func (m *defaultPaymentAdmin) ListPayments(ctx context.Context, in *AdminListPaymentsRequest, opts ...grpc.CallOption) (*AdminListPaymentsResponse, error) {
	client := payment.NewPaymentAdminClient(m.cli.Conn())
	return client.ListPayments(ctx, in, opts...)
}

// GetPayment - 支付详情查询
func (m *defaultPaymentAdmin) GetPayment(ctx context.Context, in *AdminGetPaymentRequest, opts ...grpc.CallOption) (*AdminPaymentDetailResponse, error) {
	client := payment.NewPaymentAdminClient(m.cli.Conn())
	return client.GetPayment(ctx, in, opts...)
}
