// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/internal/logic/user"
	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// Captcha 获取短信验证码
func (s *UserServer) Captcha(ctx context.Context, in *user.CaptchaReq) (*user.EmptyResp, error) {
	l := userlogic.NewCaptchaLogic(ctx, s.svcCtx)
	return l.Captcha(in)
}

// Login 手机号密码登录
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// MobileLogin 手机号验证码登录
func (s *UserServer) MobileLogin(ctx context.Context, in *user.MobileLoginReq) (*user.LoginResp, error) {
	l := userlogic.NewMobileLoginLogic(ctx, s.svcCtx)
	return l.MobileLogin(in)
}

// Register 用户注册
func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.LoginResp, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// ResetPassword 忘记密码重置
func (s *UserServer) ResetPassword(ctx context.Context, in *user.ResetPasswordReq) (*user.EmptyResp, error) {
	l := userlogic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

// UpdatePassword 修改登录密码（已登录）
func (s *UserServer) UpdatePassword(ctx context.Context, in *user.UpdatePasswordReq) (*user.EmptyResp, error) {
	l := userlogic.NewUpdatePasswordLogic(ctx, s.svcCtx)
	return l.UpdatePassword(in)
}

// UpdatePhone 修改手机号
func (s *UserServer) UpdatePhone(ctx context.Context, in *user.UpdatePhoneReq) (*user.EmptyResp, error) {
	l := userlogic.NewUpdatePhoneLogic(ctx, s.svcCtx)
	return l.UpdatePhone(in)
}

// GetUserInfo 获取个人资料
func (s *UserServer) GetUserInfo(ctx context.Context, in *user.EmptyReq) (*user.UserInfoResp, error) {
	l := userlogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// UpdateUserInfo 更新个人资料
func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.UpdateUserInfoReq) (*user.EmptyResp, error) {
	l := userlogic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

// DeleteAccount 注销账号
func (s *UserServer) DeleteAccount(ctx context.Context, in *user.DeleteAccountReq) (*user.EmptyResp, error) {
	l := userlogic.NewDeleteAccountLogic(ctx, s.svcCtx)
	return l.DeleteAccount(in)
}

// Logout 退出登录
func (s *UserServer) Logout(ctx context.Context, in *user.LogoutReq) (*user.EmptyResp, error) {
	l := userlogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// RefreshToken token刷新
func (s *UserServer) RefreshToken(ctx context.Context, in *user.RefreshTokenReq) (*user.LoginResp, error) {
	l := userlogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// GetOssToken 获取OSS上传凭证
func (s *UserServer) GetOssToken(ctx context.Context, in *user.OssTokenReq) (*user.OssTokenResp, error) {
	l := userlogic.NewGetOssTokenLogic(ctx, s.svcCtx)
	return l.GetOssToken(in)
}

// AddAddress 添加收货地址
func (s *UserServer) AddAddress(ctx context.Context, in *user.AddAddressReq) (*user.EmptyResp, error) {
	l := userlogic.NewAddAddressLogic(ctx, s.svcCtx)
	return l.AddAddress(in)
}

// UpdateAddress 更新收货地址
func (s *UserServer) UpdateAddress(ctx context.Context, in *user.AddressItem) (*user.EmptyResp, error) {
	l := userlogic.NewUpdateAddressLogic(ctx, s.svcCtx)
	return l.UpdateAddress(in)
}

// ListAddress 获取地址列表
func (s *UserServer) ListAddress(ctx context.Context, in *user.AddressListReq) (*user.AddressListResp, error) {
	l := userlogic.NewListAddressLogic(ctx, s.svcCtx)
	return l.ListAddress(in)
}

// SetDefaultAddress 设置默认地址
func (s *UserServer) SetDefaultAddress(ctx context.Context, in *user.IdPathReq) (*user.EmptyResp, error) {
	l := userlogic.NewSetDefaultAddressLogic(ctx, s.svcCtx)
	return l.SetDefaultAddress(in)
}

// DeleteAddress 删除收货地址
func (s *UserServer) DeleteAddress(ctx context.Context, in *user.IdPathReq) (*user.EmptyResp, error) {
	l := userlogic.NewDeleteAddressLogic(ctx, s.svcCtx)
	return l.DeleteAddress(in)
}
