// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/auth"
	marketingcoupon "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/marketing/coupon"
	marketinginternal_api "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/marketing/internal_api"
	orderaftersale "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/order/aftersale"
	ordercart "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/order/cart"
	ordercore "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/order/core"
	orderdelivery "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/order/delivery"
	paymentcallback "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/payment/callback"
	paymentcore "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/payment/core"
	productcategory "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/product/category"
	productlist "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/product/list"
	search "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/search"
	useraddress "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/user/address"
	userprofile "github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/handler/user/profile"
	"github.com/ZY0506/PrimeMall/apps/gateway/shop/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 热搜词列表
				Method:  http.MethodGet,
				Path:    "/hot-keywords",
				Handler: search.GetHotKeywordsHandler(serverCtx),
			},
			{
				// ES商品搜索
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: search.SearchProductsHandler(serverCtx),
			},
			{
				// ES搜索建议
				Method:  http.MethodGet,
				Path:    "/suggest",
				Handler: search.SearchSuggestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/search"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 查询搜索历史
					Method:  http.MethodGet,
					Path:    "/history",
					Handler: search.GetSearchHistoryHandler(serverCtx),
				},
				{
					// 清除搜索历史
					Method:  http.MethodDelete,
					Path:    "/history",
					Handler: search.ClearSearchHistoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/search"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取短信验证码（幂等）
				Method:  http.MethodPost,
				Path:    "/captcha",
				Handler: auth.CaptchaHandler(serverCtx),
			},
			{
				// 手机号密码登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 手机号验证码登录
				Method:  http.MethodPost,
				Path:    "/login/mobile",
				Handler: auth.MobileLoginHandler(serverCtx),
			},
			{
				// 忘记密码重置（幂等）
				Method:  http.MethodPost,
				Path:    "/password/reset",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				// 用户注册（幂等）
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// token刷新
				Method:  http.MethodPost,
				Path:    "/token/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				// OSS上传回调（服务端自行幂等）
				Method:  http.MethodPost,
				Path:    "/upload/avatar/callback",
				Handler: auth.OssCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 结算页：根据订单金额获取可用优惠券
					Method:  http.MethodPost,
					Path:    "/available",
					Handler: marketingcoupon.AvailableCouponsHandler(serverCtx),
				},
				{
					// 用户领取优惠券（幂等）
					Method:  http.MethodPost,
					Path:    "/claim",
					Handler: marketingcoupon.ClaimCouponHandler(serverCtx),
				},
				{
					// 领券中心：获取全场可领取优惠券
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: marketingcoupon.CouponListHandler(serverCtx),
				},
				{
					// 我的优惠券：查看个人卡券包
					Method:  http.MethodGet,
					Path:    "/mine",
					Handler: marketingcoupon.MyCouponsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/marketing/coupon"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 订单服务：解锁优惠券（订单取消时回滚）
					Method:  http.MethodPost,
					Path:    "/unlock",
					Handler: marketinginternal_api.UnlockCouponHandler(serverCtx),
				},
				{
					// 订单服务：使用优惠券（锁定并扣减）
					Method:  http.MethodPost,
					Path:    "/use",
					Handler: marketinginternal_api.UseCouponHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/internal/v1/coupon"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 申请售后（幂等）
				Method:  http.MethodPost,
				Path:    "/apply",
				Handler: orderaftersale.ApplyAfterSaleHandler(serverCtx),
			},
			{
				// 取消售后申请（仅待审核状态可取消）
				Method:  http.MethodPost,
				Path:    "/cancel/:id",
				Handler: orderaftersale.CancelAfterSaleHandler(serverCtx),
			},
			{
				// 查询售后详情
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: orderaftersale.AfterSaleDetailHandler(serverCtx),
			},
			{
				// 获取我的售后单列表（分页）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: orderaftersale.AfterSaleListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/order/aftersale"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 清空购物车
					Method:  http.MethodDelete,
					Path:    "/clear",
					Handler: ordercart.ClearCartHandler(serverCtx),
				},
				{
					// 获取购物车列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: ordercart.CartListHandler(serverCtx),
				},
				{
					// 批量删除购物车商品
					Method:  http.MethodDelete,
					Path:    "/remove",
					Handler: ordercart.RemoveCartHandler(serverCtx),
				},
				{
					// 修改购物车商品的勾选状态
					Method:  http.MethodPost,
					Path:    "/select",
					Handler: ordercart.SelectCartHandler(serverCtx),
				},
				{
					// 添加/更新购物车商品（数量为0则删除，幂等）
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: ordercart.UpdateCartHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/order/cart"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 取消订单（仅待支付状态可取消）
				Method:  http.MethodPost,
				Path:    "/cancel/:order_sn",
				Handler: ordercore.CancelOrderHandler(serverCtx),
			},
			{
				// 确认收货
				Method:  http.MethodPost,
				Path:    "/confirm/:order_sn",
				Handler: ordercore.ConfirmReceiptHandler(serverCtx),
			},
			{
				// 正式提交订单（幂等）
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: ordercore.CreateOrderHandler(serverCtx),
			},
			{
				// 订单详情
				Method:  http.MethodGet,
				Path:    "/detail/:order_sn",
				Handler: ordercore.OrderDetailHandler(serverCtx),
			},
			{
				// 订单列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ordercore.OrderListHandler(serverCtx),
			},
			{
				// 预下单（确认订单页，生成结算令牌）
				Method:  http.MethodPost,
				Path:    "/pre-order",
				Handler: ordercore.PreOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/order"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 查询物流轨迹
					Method:  http.MethodGet,
					Path:    "/track/:order_sn",
					Handler: orderdelivery.TrackHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/order/delivery"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 支付宝异步回调（服务端自行幂等）
				Method:  http.MethodPost,
				Path:    "/alipay",
				Handler: paymentcallback.AlipayCallbackHandler(serverCtx),
			},
			{
				// 微信支付异步回调（服务端自行幂等）
				Method:  http.MethodPost,
				Path:    "/wechat",
				Handler: paymentcallback.WechatCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/payment/callback"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 关闭支付单（未支付时）
					Method:  http.MethodPost,
					Path:    "/close/:payment_sn",
					Handler: paymentcore.ClosePaymentHandler(serverCtx),
				},
				{
					// 创建支付单（获取第三方支付拉起参数，幂等）
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: paymentcore.CreatePaymentHandler(serverCtx),
				},
				{
					// 申请退款（由订单服务售后调用，幂等）
					Method:  http.MethodPost,
					Path:    "/refund/apply",
					Handler: paymentcore.RefundApplyHandler(serverCtx),
				},
				{
					// 查询退款详情
					Method:  http.MethodGet,
					Path:    "/refund/detail/:order_sn",
					Handler: paymentcore.RefundDetailHandler(serverCtx),
				},
				{
					// 根据订单号查询支付状态
					Method:  http.MethodGet,
					Path:    "/status/order/:order_sn",
					Handler: paymentcore.StatusByOrderSnHandler(serverCtx),
				},
				{
					// 根据支付流水号查询支付状态
					Method:  http.MethodGet,
					Path:    "/status/payment/:payment_sn",
					Handler: paymentcore.StatusByPaymentSnHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/payment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取单个分类详情
				Method:  http.MethodGet,
				Path:    "/category/:id",
				Handler: productcategory.CategoryInfoHandler(serverCtx),
			},
			{
				// 获取商品全部分类树
				Method:  http.MethodGet,
				Path:    "/category/tree",
				Handler: productcategory.CategoryTreeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/product"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 商品详情
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: productlist.ProductDetailHandler(serverCtx),
			},
			{
				// 商品列表与筛选
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: productlist.ListHandler(serverCtx),
			},
			{
				// 个性化推荐
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: productlist.RecommendHandler(serverCtx),
			},
			{
				// 批量获取SKU信息（价格、库存）
				Method:  http.MethodPost,
				Path:    "/skus/batch",
				Handler: productlist.BatchSkuHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/product"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 添加收货地址（幂等）
				Method:  http.MethodPost,
				Path:    "/",
				Handler: useraddress.AddAddressHandler(serverCtx),
			},
			{
				// 更新收货地址
				Method:  http.MethodPut,
				Path:    "/",
				Handler: useraddress.UpdateAddressHandler(serverCtx),
			},
			{
				// 删除收货地址
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: useraddress.DeleteAddressHandler(serverCtx),
			},
			{
				// 设置默认收货地址
				Method:  http.MethodPatch,
				Path:    "/default/:id",
				Handler: useraddress.SetDefaultAddressHandler(serverCtx),
			},
			{
				// 获取地址列表（分页）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: useraddress.ListAddressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenBlacklistMiddleware},
			[]rest.Route{
				{
					// 注销账号
					Method:  http.MethodDelete,
					Path:    "/account",
					Handler: userprofile.DeleteAccountHandler(serverCtx),
				},
				{
					// 获取个人资料
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: userprofile.DetailHandler(serverCtx),
				},
				{
					// 更新个人资料
					Method:  http.MethodPut,
					Path:    "/info",
					Handler: userprofile.UpdateInfoHandler(serverCtx),
				},
				{
					// 退出登录
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: userprofile.LogoutHandler(serverCtx),
				},
				{
					// 修改登录密码
					Method:  http.MethodPut,
					Path:    "/password/update",
					Handler: userprofile.UpdatePasswordHandler(serverCtx),
				},
				{
					// 修改手机号（幂等）
					Method:  http.MethodPut,
					Path:    "/phone",
					Handler: userprofile.UpdatePhoneHandler(serverCtx),
				},
				{
					// 获取OSS上传凭证
					Method:  http.MethodPost,
					Path:    "/upload/avatar/token",
					Handler: userprofile.GetOssTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
