// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: order.proto

package order

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/order/rpc/types/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddressDetail                = order.AddressDetail
	AddressSnapshot              = order.AddressSnapshot
	AdminAfterSaleDetailResponse = order.AdminAfterSaleDetailResponse
	AdminAfterSaleListItem       = order.AdminAfterSaleListItem
	AdminGetAfterSaleRequest     = order.AdminGetAfterSaleRequest
	AdminGetOrderRequest         = order.AdminGetOrderRequest
	AdminHandleAfterSaleRequest  = order.AdminHandleAfterSaleRequest
	AdminListAfterSalesRequest   = order.AdminListAfterSalesRequest
	AdminListAfterSalesResponse  = order.AdminListAfterSalesResponse
	AdminListOrdersRequest       = order.AdminListOrdersRequest
	AdminListOrdersResponse      = order.AdminListOrdersResponse
	AdminOrderAddress            = order.AdminOrderAddress
	AdminOrderDetailResponse     = order.AdminOrderDetailResponse
	AdminOrderListItem           = order.AdminOrderListItem
	AdminOrderProductItem        = order.AdminOrderProductItem
	AdminShipOrderRequest        = order.AdminShipOrderRequest
	AfterSaleDetailRequest       = order.AfterSaleDetailRequest
	AfterSaleDetailResponse      = order.AfterSaleDetailResponse
	AfterSaleListItem            = order.AfterSaleListItem
	AfterSaleListRequest         = order.AfterSaleListRequest
	AfterSaleListResponse        = order.AfterSaleListResponse
	AfterSaleRequest             = order.AfterSaleRequest
	BatchSelectCartRequest       = order.BatchSelectCartRequest
	CancelAfterSaleRequest       = order.CancelAfterSaleRequest
	CancelOrderRequest           = order.CancelOrderRequest
	CartItem                     = order.CartItem
	CartListResponse             = order.CartListResponse
	CreateOrderRequest           = order.CreateOrderRequest
	CreateOrderResponse          = order.CreateOrderResponse
	Empty                        = order.Empty
	OrderDetailRequest           = order.OrderDetailRequest
	OrderDetailResponse          = order.OrderDetailResponse
	OrderItem                    = order.OrderItem
	OrderItemSimple              = order.OrderItemSimple
	OrderListItem                = order.OrderListItem
	OrderListRequest             = order.OrderListRequest
	OrderListResponse            = order.OrderListResponse
	OrderTimeoutMessage          = order.OrderTimeoutMessage
	OrderTimeoutNotifyRequest    = order.OrderTimeoutNotifyRequest
	PaymentSuccessNotifyRequest  = order.PaymentSuccessNotifyRequest
	PreOrderRequest              = order.PreOrderRequest
	PreOrderResponse             = order.PreOrderResponse
	RefundSuccessNotifyRequest   = order.RefundSuccessNotifyRequest
	RemoveCartRequest            = order.RemoveCartRequest
	SelectCartRequest            = order.SelectCartRequest
	SubmitReturnLogisticsRequest = order.SubmitReturnLogisticsRequest
	UpdateCartRequest            = order.UpdateCartRequest

	Order interface {
		// PreOrder - 预下单（结算页接口）：校验信息、计算价格、生成结算token
		PreOrder(ctx context.Context, in *PreOrderRequest, opts ...grpc.CallOption) (*PreOrderResponse, error)
		// CreateOrder - 创建订单（提交订单接口）：基于结算token，锁库存、生成正式订单
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		// OrderList - 订单列表：查询用户所有订单/按状态筛选
		OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
		// OrderDetail - 订单详情：查询订单完整信息
		OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailResponse, error)
		// CancelOrder - 取消订单：仅待支付订单可取消
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*Empty, error)
		// ConfirmReceipt - 确认收货：已发货订单确认完成
		ConfirmReceipt(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*Empty, error)
		// ApplyAfterSale - 申请售后：订单内商品申请退款/退货退款
		ApplyAfterSale(ctx context.Context, in *AfterSaleRequest, opts ...grpc.CallOption) (*Empty, error)
		// CancelAfterSale - 取消售后：撤销售后申请
		CancelAfterSale(ctx context.Context, in *CancelAfterSaleRequest, opts ...grpc.CallOption) (*Empty, error)
		// AfterSaleList - 售后列表：查询用户所有售后单
		AfterSaleList(ctx context.Context, in *AfterSaleListRequest, opts ...grpc.CallOption) (*AfterSaleListResponse, error)
		// AfterSaleDetail - 售后详情：查询售后单完整信息
		AfterSaleDetail(ctx context.Context, in *AfterSaleDetailRequest, opts ...grpc.CallOption) (*AfterSaleDetailResponse, error)
		// SubmitReturnLogistics - 提交退货物流：退货退款场景填写退货快递信息
		SubmitReturnLogistics(ctx context.Context, in *SubmitReturnLogisticsRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// PreOrder - 预下单（结算页接口）：校验信息、计算价格、生成结算token
func (m *defaultOrder) PreOrder(ctx context.Context, in *PreOrderRequest, opts ...grpc.CallOption) (*PreOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.PreOrder(ctx, in, opts...)
}

// CreateOrder - 创建订单（提交订单接口）：基于结算token，锁库存、生成正式订单
func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// OrderList - 订单列表：查询用户所有订单/按状态筛选
func (m *defaultOrder) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

// OrderDetail - 订单详情：查询订单完整信息
func (m *defaultOrder) OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderDetail(ctx, in, opts...)
}

// CancelOrder - 取消订单：仅待支付订单可取消
func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// ConfirmReceipt - 确认收货：已发货订单确认完成
func (m *defaultOrder) ConfirmReceipt(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ConfirmReceipt(ctx, in, opts...)
}

// ApplyAfterSale - 申请售后：订单内商品申请退款/退货退款
func (m *defaultOrder) ApplyAfterSale(ctx context.Context, in *AfterSaleRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ApplyAfterSale(ctx, in, opts...)
}

// CancelAfterSale - 取消售后：撤销售后申请
func (m *defaultOrder) CancelAfterSale(ctx context.Context, in *CancelAfterSaleRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelAfterSale(ctx, in, opts...)
}

// AfterSaleList - 售后列表：查询用户所有售后单
func (m *defaultOrder) AfterSaleList(ctx context.Context, in *AfterSaleListRequest, opts ...grpc.CallOption) (*AfterSaleListResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.AfterSaleList(ctx, in, opts...)
}

// AfterSaleDetail - 售后详情：查询售后单完整信息
func (m *defaultOrder) AfterSaleDetail(ctx context.Context, in *AfterSaleDetailRequest, opts ...grpc.CallOption) (*AfterSaleDetailResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.AfterSaleDetail(ctx, in, opts...)
}

// SubmitReturnLogistics - 提交退货物流：退货退款场景填写退货快递信息
func (m *defaultOrder) SubmitReturnLogistics(ctx context.Context, in *SubmitReturnLogisticsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.SubmitReturnLogistics(ctx, in, opts...)
}
