// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/internal/logic/admin"
	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/types/user"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// ListUsers 获取用户列表（分页、筛选、搜索）
func (s *AdminServer) ListUsers(ctx context.Context, in *user.ListUsersReq) (*user.ListUsersResp, error) {
	l := adminlogic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

// GetUserDetail 获取用户详情（含扩展信息、最近登录、处罚记录）
func (s *AdminServer) GetUserDetail(ctx context.Context, in *user.GetUserDetailReq) (*user.GetUserDetailResp, error) {
	l := adminlogic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}

// BanUser 封禁用户（限制下单/封禁账号）
func (s *AdminServer) BanUser(ctx context.Context, in *user.BanUserReq) (*user.EmptyResp, error) {
	l := adminlogic.NewBanUserLogic(ctx, s.svcCtx)
	return l.BanUser(in)
}

// UnbanUser 解封用户（恢复为正常状态）
func (s *AdminServer) UnbanUser(ctx context.Context, in *user.UnbanUserReq) (*user.EmptyResp, error) {
	l := adminlogic.NewUnbanUserLogic(ctx, s.svcCtx)
	return l.UnbanUser(in)
}

// GetUserStatistics 获取用户统计数据
func (s *AdminServer) GetUserStatistics(ctx context.Context, in *user.GetUserStatisticsReq) (*user.GetUserStatisticsResp, error) {
	l := adminlogic.NewGetUserStatisticsLogic(ctx, s.svcCtx)
	return l.GetUserStatistics(in)
}

// ListLoginLogs 获取登录日志列表
func (s *AdminServer) ListLoginLogs(ctx context.Context, in *user.ListLoginLogsReq) (*user.ListLoginLogsResp, error) {
	l := adminlogic.NewListLoginLogsLogic(ctx, s.svcCtx)
	return l.ListLoginLogs(in)
}

// ListPunishLogs 获取风控处罚日志列表
func (s *AdminServer) ListPunishLogs(ctx context.Context, in *user.ListPunishLogsReq) (*user.ListPunishLogsResp, error) {
	l := adminlogic.NewListPunishLogsLogic(ctx, s.svcCtx)
	return l.ListPunishLogs(in)
}

// AdminResetPassword 重置用户密码（管理员强制重置）
func (s *AdminServer) AdminResetPassword(ctx context.Context, in *user.AdminResetPasswordReq) (*user.EmptyResp, error) {
	l := adminlogic.NewAdminResetPasswordLogic(ctx, s.svcCtx)
	return l.AdminResetPassword(in)
}
