// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentCallbackLogFieldNames          = builder.RawFieldNames(&PaymentCallbackLog{})
	paymentCallbackLogRows                = strings.Join(paymentCallbackLogFieldNames, ",")
	paymentCallbackLogRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentCallbackLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	paymentCallbackLogRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentCallbackLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	paymentCallbackLogModel interface {
		Insert(ctx context.Context, data *PaymentCallbackLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PaymentCallbackLog, error)
		Update(ctx context.Context, data *PaymentCallbackLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPaymentCallbackLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PaymentCallbackLog struct {
		Id           uint64         `db:"id"`            // 日志ID
		PaymentSn    string         `db:"payment_sn"`    // 支付流水号
		OrderSn      string         `db:"order_sn"`      // 订单号
		Channel      string         `db:"channel"`       // 支付渠道：wechat-微信支付，alipay-支付宝
		RequestBody  sql.NullString `db:"request_body"`  // 回调请求原始数据
		ResponseBody sql.NullString `db:"response_body"` // 回调响应数据
		Status       int64          `db:"status"`        // 处理状态：0-处理中，1-处理成功，2-处理失败
		ErrorMsg     string         `db:"error_msg"`     // 错误信息
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
	}
)

func newPaymentCallbackLogModel(conn sqlx.SqlConn) *defaultPaymentCallbackLogModel {
	return &defaultPaymentCallbackLogModel{
		conn:  conn,
		table: "`payment_callback_log`",
	}
}

func (m *defaultPaymentCallbackLogModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaymentCallbackLogModel) FindOne(ctx context.Context, id uint64) (*PaymentCallbackLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentCallbackLogRows, m.table)
	var resp PaymentCallbackLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentCallbackLogModel) Insert(ctx context.Context, data *PaymentCallbackLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, paymentCallbackLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PaymentSn, data.OrderSn, data.Channel, data.RequestBody, data.ResponseBody, data.Status, data.ErrorMsg)
	return ret, err
}

func (m *defaultPaymentCallbackLogModel) Update(ctx context.Context, data *PaymentCallbackLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentCallbackLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.PaymentSn, data.OrderSn, data.Channel, data.RequestBody, data.ResponseBody, data.Status, data.ErrorMsg, data.Id)
	return err
}

func (m *defaultPaymentCallbackLogModel) tableName() string {
	return m.table
}
