// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	afterSaleFieldNames          = builder.RawFieldNames(&AfterSale{})
	afterSaleRows                = strings.Join(afterSaleFieldNames, ",")
	afterSaleRowsExpectAutoSet   = strings.Join(stringx.Remove(afterSaleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	afterSaleRowsWithPlaceHolder = strings.Join(stringx.Remove(afterSaleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	afterSaleModel interface {
		Insert(ctx context.Context, data *AfterSale) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AfterSale, error)
		FindOneByAfterSaleSn(ctx context.Context, afterSaleSn string) (*AfterSale, error)
		FindOneByRefundSn(ctx context.Context, refundSn string) (*AfterSale, error)
		FindOneByUserIdIdempotencyKey(ctx context.Context, userId uint64, idempotencyKey string) (*AfterSale, error)
		Update(ctx context.Context, data *AfterSale) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAfterSaleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AfterSale struct {
		Id                 uint64         `db:"id"`                   // 售后单ID
		AfterSaleSn        string         `db:"after_sale_sn"`        // 售后单号
		IdempotencyKey     string         `db:"idempotency_key"`      // 幂等键（同一用户下唯一）
		OrderId            uint64         `db:"order_id"`             // 订单ID
		OrderSn            string         `db:"order_sn"`             // 订单号
		UserId             uint64         `db:"user_id"`              // 用户ID
		Type               int64          `db:"type"`                 // 售后类型：1仅退款 2退货退款
		Status             int64          `db:"status"`               // 状态：10待审核 20待商家收货 30退款中 40已完成 50已拒绝 60已取消
		RefundStatus       int64          `db:"refund_status"`        // 退款状态：0未退款 10退款中 20退款成功 30退款失败
		ApplyAmount        int64          `db:"apply_amount"`         // 申请退款金额（分）
		ApprovedAmount     int64          `db:"approved_amount"`      // 审核通过金额（分）
		RealRefundAmount   int64          `db:"real_refund_amount"`   // 实际退款金额（分）
		Reason             string         `db:"reason"`               // 售后原因
		AuditRemark        string         `db:"audit_remark"`         // 审核备注
		AuditTime          sql.NullTime   `db:"audit_time"`           // 审核时间
		Images             sql.NullString `db:"images"`               // 凭证图片URL数组
		ReturnTrackingSn   string         `db:"return_tracking_sn"`   // 退货物流单号
		ReturnTrackingCorp string         `db:"return_tracking_corp"` // 退货物流公司
		ReturnReceivedTime sql.NullTime   `db:"return_received_time"` // 商家收货时间
		RefundSn           string         `db:"refund_sn"`            // 商户退款单号（唯一）
		RefundTime         sql.NullTime   `db:"refund_time"`          // 退款时间
		ThirdRefundSn      string         `db:"third_refund_sn"`      // 第三方退款单号
		CancelTime         sql.NullTime   `db:"cancel_time"`          // 取消时间
		CreatedAt          time.Time      `db:"created_at"`
		UpdatedAt          time.Time      `db:"updated_at"`
	}
)

func newAfterSaleModel(conn sqlx.SqlConn) *defaultAfterSaleModel {
	return &defaultAfterSaleModel{
		conn:  conn,
		table: "`after_sale`",
	}
}

func (m *defaultAfterSaleModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAfterSaleModel) FindOne(ctx context.Context, id uint64) (*AfterSale, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", afterSaleRows, m.table)
	var resp AfterSale
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAfterSaleModel) FindOneByAfterSaleSn(ctx context.Context, afterSaleSn string) (*AfterSale, error) {
	var resp AfterSale
	query := fmt.Sprintf("select %s from %s where `after_sale_sn` = ? limit 1", afterSaleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, afterSaleSn)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAfterSaleModel) FindOneByRefundSn(ctx context.Context, refundSn string) (*AfterSale, error) {
	var resp AfterSale
	query := fmt.Sprintf("select %s from %s where `refund_sn` = ? limit 1", afterSaleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, refundSn)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAfterSaleModel) FindOneByUserIdIdempotencyKey(ctx context.Context, userId uint64, idempotencyKey string) (*AfterSale, error) {
	var resp AfterSale
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `idempotency_key` = ? limit 1", afterSaleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, idempotencyKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAfterSaleModel) Insert(ctx context.Context, data *AfterSale) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, afterSaleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AfterSaleSn, data.IdempotencyKey, data.OrderId, data.OrderSn, data.UserId, data.Type, data.Status, data.RefundStatus, data.ApplyAmount, data.ApprovedAmount, data.RealRefundAmount, data.Reason, data.AuditRemark, data.AuditTime, data.Images, data.ReturnTrackingSn, data.ReturnTrackingCorp, data.ReturnReceivedTime, data.RefundSn, data.RefundTime, data.ThirdRefundSn, data.CancelTime)
	return ret, err
}

func (m *defaultAfterSaleModel) Update(ctx context.Context, newData *AfterSale) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, afterSaleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AfterSaleSn, newData.IdempotencyKey, newData.OrderId, newData.OrderSn, newData.UserId, newData.Type, newData.Status, newData.RefundStatus, newData.ApplyAmount, newData.ApprovedAmount, newData.RealRefundAmount, newData.Reason, newData.AuditRemark, newData.AuditTime, newData.Images, newData.ReturnTrackingSn, newData.ReturnTrackingCorp, newData.ReturnReceivedTime, newData.RefundSn, newData.RefundTime, newData.ThirdRefundSn, newData.CancelTime, newData.Id)
	return err
}

func (m *defaultAfterSaleModel) tableName() string {
	return m.table
}
