// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	afterSaleItemFieldNames          = builder.RawFieldNames(&AfterSaleItem{})
	afterSaleItemRows                = strings.Join(afterSaleItemFieldNames, ",")
	afterSaleItemRowsExpectAutoSet   = strings.Join(stringx.Remove(afterSaleItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	afterSaleItemRowsWithPlaceHolder = strings.Join(stringx.Remove(afterSaleItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	afterSaleItemModel interface {
		Insert(ctx context.Context, data *AfterSaleItem) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AfterSaleItem, error)
		Update(ctx context.Context, data *AfterSaleItem) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAfterSaleItemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AfterSaleItem struct {
		Id           uint64    `db:"id"`
		AfterSaleSn  string    `db:"after_sale_sn"` // 售后单号
		OrderItemId  uint64    `db:"order_item_id"` // 原订单商品项ID
		SkuId        uint64    `db:"sku_id"`
		SpuId        uint64    `db:"spu_id"`
		ProductName  string    `db:"product_name"`
		SkuName      string    `db:"sku_name"`
		SkuPic       string    `db:"sku_pic"`
		Price        int64     `db:"price"`         // 原成交单价（分）
		Quantity     int64     `db:"quantity"`      // 售后数量
		TotalAmount  int64     `db:"total_amount"`  // 原小计金额（单价×数量，单位：分）
		RefundAmount int64     `db:"refund_amount"` // 该项退款金额（分）
		CreatedAt    time.Time `db:"created_at"`
	}
)

func newAfterSaleItemModel(conn sqlx.SqlConn) *defaultAfterSaleItemModel {
	return &defaultAfterSaleItemModel{
		conn:  conn,
		table: "`after_sale_item`",
	}
}

func (m *defaultAfterSaleItemModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAfterSaleItemModel) FindOne(ctx context.Context, id uint64) (*AfterSaleItem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", afterSaleItemRows, m.table)
	var resp AfterSaleItem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAfterSaleItemModel) Insert(ctx context.Context, data *AfterSaleItem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, afterSaleItemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AfterSaleSn, data.OrderItemId, data.SkuId, data.SpuId, data.ProductName, data.SkuName, data.SkuPic, data.Price, data.Quantity, data.TotalAmount, data.RefundAmount)
	return ret, err
}

func (m *defaultAfterSaleItemModel) Update(ctx context.Context, data *AfterSaleItem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, afterSaleItemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AfterSaleSn, data.OrderItemId, data.SkuId, data.SpuId, data.ProductName, data.SkuName, data.SkuPic, data.Price, data.Quantity, data.TotalAmount, data.RefundAmount, data.Id)
	return err
}

func (m *defaultAfterSaleItemModel) tableName() string {
	return m.table
}
