// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: apps/service/search/rpc/search.proto

package search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Search_SearchProducts_FullMethodName      = "/search.Search/SearchProducts"
	Search_SuggestProducts_FullMethodName     = "/search.Search/SuggestProducts"
	Search_GetHotKeywords_FullMethodName      = "/search.Search/GetHotKeywords"
	Search_GetSearchHistory_FullMethodName    = "/search.Search/GetSearchHistory"
	Search_ClearSearchHistory_FullMethodName  = "/search.Search/ClearSearchHistory"
	Search_SyncProductToES_FullMethodName     = "/search.Search/SyncProductToES"
	Search_BatchSyncProducts_FullMethodName   = "/search.Search/BatchSyncProducts"
	Search_DeleteProductFromES_FullMethodName = "/search.Search/DeleteProductFromES"
)

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== RPC ====================
type SearchClient interface {
	// ES商品搜索
	SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error)
	// ES商品搜索建议（补全）
	SuggestProducts(ctx context.Context, in *SuggestReq, opts ...grpc.CallOption) (*SuggestResp, error)
	// 热搜词列表
	GetHotKeywords(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HotKeywordsResp, error)
	// 用户搜索历史
	GetSearchHistory(ctx context.Context, in *SearchHistoryReq, opts ...grpc.CallOption) (*SearchHistoryResp, error)
	// 清除搜索历史
	ClearSearchHistory(ctx context.Context, in *ClearSearchHistoryReq, opts ...grpc.CallOption) (*Empty, error)
	// 同步商品到ES
	SyncProductToES(ctx context.Context, in *SyncProductReq, opts ...grpc.CallOption) (*Empty, error)
	// 批量同步商品到ES
	BatchSyncProducts(ctx context.Context, in *BatchSyncProductsReq, opts ...grpc.CallOption) (*Empty, error)
	// 从ES删除商品
	DeleteProductFromES(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*Empty, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResp)
	err := c.cc.Invoke(ctx, Search_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SuggestProducts(ctx context.Context, in *SuggestReq, opts ...grpc.CallOption) (*SuggestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestResp)
	err := c.cc.Invoke(ctx, Search_SuggestProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetHotKeywords(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HotKeywordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotKeywordsResp)
	err := c.cc.Invoke(ctx, Search_GetHotKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetSearchHistory(ctx context.Context, in *SearchHistoryReq, opts ...grpc.CallOption) (*SearchHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchHistoryResp)
	err := c.cc.Invoke(ctx, Search_GetSearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ClearSearchHistory(ctx context.Context, in *ClearSearchHistoryReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Search_ClearSearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SyncProductToES(ctx context.Context, in *SyncProductReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Search_SyncProductToES_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) BatchSyncProducts(ctx context.Context, in *BatchSyncProductsReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Search_BatchSyncProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) DeleteProductFromES(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Search_DeleteProductFromES_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility.
//
// ==================== RPC ====================
type SearchServer interface {
	// ES商品搜索
	SearchProducts(context.Context, *SearchProductsReq) (*SearchProductsResp, error)
	// ES商品搜索建议（补全）
	SuggestProducts(context.Context, *SuggestReq) (*SuggestResp, error)
	// 热搜词列表
	GetHotKeywords(context.Context, *Empty) (*HotKeywordsResp, error)
	// 用户搜索历史
	GetSearchHistory(context.Context, *SearchHistoryReq) (*SearchHistoryResp, error)
	// 清除搜索历史
	ClearSearchHistory(context.Context, *ClearSearchHistoryReq) (*Empty, error)
	// 同步商品到ES
	SyncProductToES(context.Context, *SyncProductReq) (*Empty, error)
	// 批量同步商品到ES
	BatchSyncProducts(context.Context, *BatchSyncProductsReq) (*Empty, error)
	// 从ES删除商品
	DeleteProductFromES(context.Context, *DeleteProductReq) (*Empty, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServer struct{}

func (UnimplementedSearchServer) SearchProducts(context.Context, *SearchProductsReq) (*SearchProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedSearchServer) SuggestProducts(context.Context, *SuggestReq) (*SuggestResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestProducts not implemented")
}
func (UnimplementedSearchServer) GetHotKeywords(context.Context, *Empty) (*HotKeywordsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotKeywords not implemented")
}
func (UnimplementedSearchServer) GetSearchHistory(context.Context, *SearchHistoryReq) (*SearchHistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchHistory not implemented")
}
func (UnimplementedSearchServer) ClearSearchHistory(context.Context, *ClearSearchHistoryReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSearchHistory not implemented")
}
func (UnimplementedSearchServer) SyncProductToES(context.Context, *SyncProductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncProductToES not implemented")
}
func (UnimplementedSearchServer) BatchSyncProducts(context.Context, *BatchSyncProductsReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSyncProducts not implemented")
}
func (UnimplementedSearchServer) DeleteProductFromES(context.Context, *DeleteProductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductFromES not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}
func (UnimplementedSearchServer) testEmbeddedByValue()                {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	// If the following call pancis, it indicates UnimplementedSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchProducts(ctx, req.(*SearchProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SuggestProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SuggestProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SuggestProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SuggestProducts(ctx, req.(*SuggestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetHotKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetHotKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetHotKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetHotKeywords(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetSearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetSearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetSearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetSearchHistory(ctx, req.(*SearchHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ClearSearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSearchHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ClearSearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ClearSearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ClearSearchHistory(ctx, req.(*ClearSearchHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SyncProductToES_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SyncProductToES(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SyncProductToES_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SyncProductToES(ctx, req.(*SyncProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_BatchSyncProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSyncProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).BatchSyncProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_BatchSyncProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).BatchSyncProducts(ctx, req.(*BatchSyncProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_DeleteProductFromES_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DeleteProductFromES(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_DeleteProductFromES_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DeleteProductFromES(ctx, req.(*DeleteProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchProducts",
			Handler:    _Search_SearchProducts_Handler,
		},
		{
			MethodName: "SuggestProducts",
			Handler:    _Search_SuggestProducts_Handler,
		},
		{
			MethodName: "GetHotKeywords",
			Handler:    _Search_GetHotKeywords_Handler,
		},
		{
			MethodName: "GetSearchHistory",
			Handler:    _Search_GetSearchHistory_Handler,
		},
		{
			MethodName: "ClearSearchHistory",
			Handler:    _Search_ClearSearchHistory_Handler,
		},
		{
			MethodName: "SyncProductToES",
			Handler:    _Search_SyncProductToES_Handler,
		},
		{
			MethodName: "BatchSyncProducts",
			Handler:    _Search_BatchSyncProducts_Handler,
		},
		{
			MethodName: "DeleteProductFromES",
			Handler:    _Search_DeleteProductFromES_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/search/rpc/search.proto",
}
