// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: apps/service/marketing/rpc/marketing.proto

package marketing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 优惠券 ====================
type CouponType int32

const (
	CouponType_COUPON_TYPE_UNKNOWN      CouponType = 0
	CouponType_COUPON_TYPE_FULL_REDUCE  CouponType = 1 // 满减券
	CouponType_COUPON_TYPE_DISCOUNT     CouponType = 2 // 折扣券
	CouponType_COUPON_TYPE_NO_THRESHOLD CouponType = 3 // 无门槛券
)

// Enum value maps for CouponType.
var (
	CouponType_name = map[int32]string{
		0: "COUPON_TYPE_UNKNOWN",
		1: "COUPON_TYPE_FULL_REDUCE",
		2: "COUPON_TYPE_DISCOUNT",
		3: "COUPON_TYPE_NO_THRESHOLD",
	}
	CouponType_value = map[string]int32{
		"COUPON_TYPE_UNKNOWN":      0,
		"COUPON_TYPE_FULL_REDUCE":  1,
		"COUPON_TYPE_DISCOUNT":     2,
		"COUPON_TYPE_NO_THRESHOLD": 3,
	}
)

func (x CouponType) Enum() *CouponType {
	p := new(CouponType)
	*p = x
	return p
}

func (x CouponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_service_marketing_rpc_marketing_proto_enumTypes[0].Descriptor()
}

func (CouponType) Type() protoreflect.EnumType {
	return &file_apps_service_marketing_rpc_marketing_proto_enumTypes[0]
}

func (x CouponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponType.Descriptor instead.
func (CouponType) EnumDescriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{0}
}

// ==================== 通用结构 ====================
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{0}
}

type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{1}
}

func (x *IdReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{2}
}

func (x *PageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{3}
}

func (x *PageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CreateCouponReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type              CouponType             `protobuf:"varint,2,opt,name=type,proto3,enum=marketing.CouponType" json:"type,omitempty"`
	ThresholdAmount   int64                  `protobuf:"varint,3,opt,name=threshold_amount,json=thresholdAmount,proto3" json:"threshold_amount,omitempty"`         // 门槛（分）
	ReduceAmount      int64                  `protobuf:"varint,4,opt,name=reduce_amount,json=reduceAmount,proto3" json:"reduce_amount,omitempty"`                  // 减免金额（分）
	DiscountRate      int32                  `protobuf:"varint,5,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`                  // 折扣率（万分比）
	MaxDiscountAmount int64                  `protobuf:"varint,6,opt,name=max_discount_amount,json=maxDiscountAmount,proto3" json:"max_discount_amount,omitempty"` // 折扣封顶（分）
	TotalQuantity     int32                  `protobuf:"varint,7,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	PerUserLimit      int32                  `protobuf:"varint,8,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`
	StartTime         int64                  `protobuf:"varint,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix秒
	EndTime           int64                  `protobuf:"varint,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description       string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCouponReq) Reset() {
	*x = CreateCouponReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponReq) ProtoMessage() {}

func (x *CreateCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponReq.ProtoReflect.Descriptor instead.
func (*CreateCouponReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCouponReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCouponReq) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNKNOWN
}

func (x *CreateCouponReq) GetThresholdAmount() int64 {
	if x != nil {
		return x.ThresholdAmount
	}
	return 0
}

func (x *CreateCouponReq) GetReduceAmount() int64 {
	if x != nil {
		return x.ReduceAmount
	}
	return 0
}

func (x *CreateCouponReq) GetDiscountRate() int32 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *CreateCouponReq) GetMaxDiscountAmount() int64 {
	if x != nil {
		return x.MaxDiscountAmount
	}
	return 0
}

func (x *CreateCouponReq) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *CreateCouponReq) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CreateCouponReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateCouponReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateCouponReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateCouponReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type              CouponType             `protobuf:"varint,3,opt,name=type,proto3,enum=marketing.CouponType" json:"type,omitempty"`
	ThresholdAmount   int64                  `protobuf:"varint,4,opt,name=threshold_amount,json=thresholdAmount,proto3" json:"threshold_amount,omitempty"`
	ReduceAmount      int64                  `protobuf:"varint,5,opt,name=reduce_amount,json=reduceAmount,proto3" json:"reduce_amount,omitempty"`
	DiscountRate      int32                  `protobuf:"varint,6,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	MaxDiscountAmount int64                  `protobuf:"varint,7,opt,name=max_discount_amount,json=maxDiscountAmount,proto3" json:"max_discount_amount,omitempty"`
	TotalQuantity     int32                  `protobuf:"varint,8,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	PerUserLimit      int32                  `protobuf:"varint,9,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`
	StartTime         int64                  `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           int64                  `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description       string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Status            int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"` // 1-启用 2-禁用
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateCouponReq) Reset() {
	*x = UpdateCouponReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCouponReq) ProtoMessage() {}

func (x *UpdateCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCouponReq.ProtoReflect.Descriptor instead.
func (*UpdateCouponReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCouponReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCouponReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCouponReq) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNKNOWN
}

func (x *UpdateCouponReq) GetThresholdAmount() int64 {
	if x != nil {
		return x.ThresholdAmount
	}
	return 0
}

func (x *UpdateCouponReq) GetReduceAmount() int64 {
	if x != nil {
		return x.ReduceAmount
	}
	return 0
}

func (x *UpdateCouponReq) GetDiscountRate() int32 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *UpdateCouponReq) GetMaxDiscountAmount() int64 {
	if x != nil {
		return x.MaxDiscountAmount
	}
	return 0
}

func (x *UpdateCouponReq) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *UpdateCouponReq) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *UpdateCouponReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateCouponReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpdateCouponReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCouponReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CouponInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type              CouponType             `protobuf:"varint,3,opt,name=type,proto3,enum=marketing.CouponType" json:"type,omitempty"`
	ThresholdAmount   int64                  `protobuf:"varint,4,opt,name=threshold_amount,json=thresholdAmount,proto3" json:"threshold_amount,omitempty"`
	ReduceAmount      int64                  `protobuf:"varint,5,opt,name=reduce_amount,json=reduceAmount,proto3" json:"reduce_amount,omitempty"`
	DiscountRate      int32                  `protobuf:"varint,6,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	MaxDiscountAmount int64                  `protobuf:"varint,7,opt,name=max_discount_amount,json=maxDiscountAmount,proto3" json:"max_discount_amount,omitempty"`
	TotalQuantity     int32                  `protobuf:"varint,8,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	UsedQuantity      int32                  `protobuf:"varint,9,opt,name=used_quantity,json=usedQuantity,proto3" json:"used_quantity,omitempty"`
	PerUserLimit      int32                  `protobuf:"varint,10,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`
	StartTime         int64                  `protobuf:"varint,11,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           int64                  `protobuf:"varint,12,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status            int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Description       string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserClaimCount    int32                  `protobuf:"varint,16,opt,name=user_claim_count,json=userClaimCount,proto3" json:"user_claim_count,omitempty"` // 当前用户已领取次数
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CouponInfo) Reset() {
	*x = CouponInfo{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfo) ProtoMessage() {}

func (x *CouponInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfo.ProtoReflect.Descriptor instead.
func (*CouponInfo) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{6}
}

func (x *CouponInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponInfo) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNKNOWN
}

func (x *CouponInfo) GetThresholdAmount() int64 {
	if x != nil {
		return x.ThresholdAmount
	}
	return 0
}

func (x *CouponInfo) GetReduceAmount() int64 {
	if x != nil {
		return x.ReduceAmount
	}
	return 0
}

func (x *CouponInfo) GetDiscountRate() int32 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *CouponInfo) GetMaxDiscountAmount() int64 {
	if x != nil {
		return x.MaxDiscountAmount
	}
	return 0
}

func (x *CouponInfo) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *CouponInfo) GetUsedQuantity() int32 {
	if x != nil {
		return x.UsedQuantity
	}
	return 0
}

func (x *CouponInfo) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CouponInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CouponInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CouponInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CouponInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CouponInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CouponInfo) GetUserClaimCount() int32 {
	if x != nil {
		return x.UserClaimCount
	}
	return 0
}

type CouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupon        *CouponInfo            `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponResp) Reset() {
	*x = CouponResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponResp) ProtoMessage() {}

func (x *CouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponResp.ProtoReflect.Descriptor instead.
func (*CouponResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{7}
}

func (x *CouponResp) GetCoupon() *CouponInfo {
	if x != nil {
		return x.Coupon
	}
	return nil
}

type ListCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageReq               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsReq) Reset() {
	*x = ListCouponsReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsReq) ProtoMessage() {}

func (x *ListCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsReq.ProtoReflect.Descriptor instead.
func (*ListCouponsReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{8}
}

func (x *ListCouponsReq) GetPage() *PageReq {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResp              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	List          []*CouponInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsResp) Reset() {
	*x = ListCouponsResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsResp) ProtoMessage() {}

func (x *ListCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsResp.ProtoReflect.Descriptor instead.
func (*ListCouponsResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{9}
}

func (x *ListCouponsResp) GetPage() *PageResp {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListCouponsResp) GetList() []*CouponInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 用户优惠券 ====================
type ClaimCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      uint64                 `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponReq) Reset() {
	*x = ClaimCouponReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponReq) ProtoMessage() {}

func (x *ClaimCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponReq.ProtoReflect.Descriptor instead.
func (*ClaimCouponReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimCouponReq) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

type ClaimCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId  uint64                 `protobuf:"varint,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponResp) Reset() {
	*x = ClaimCouponResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponResp) ProtoMessage() {}

func (x *ClaimCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponResp.ProtoReflect.Descriptor instead.
func (*ClaimCouponResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimCouponResp) GetUserCouponId() uint64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *ClaimCouponResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type MyCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0-未使用 1-已使用 2-已过期
	Page          *PageReq               `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyCouponsReq) Reset() {
	*x = MyCouponsReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCouponsReq) ProtoMessage() {}

func (x *MyCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCouponsReq.ProtoReflect.Descriptor instead.
func (*MyCouponsReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{12}
}

func (x *MyCouponsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MyCouponsReq) GetPage() *PageReq {
	if x != nil {
		return x.Page
	}
	return nil
}

type UserCouponInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponId          uint64                 `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	UserId            uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type              CouponType             `protobuf:"varint,5,opt,name=type,proto3,enum=marketing.CouponType" json:"type,omitempty"`
	Status            int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 0-未使用 1-已使用 2-已过期
	ExpireTime        int64                  `protobuf:"varint,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	OrderSn           string                 `protobuf:"bytes,8,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"` // 使用的订单号
	UnavailableReason string                 `protobuf:"bytes,9,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	ThresholdAmount   int64                  `protobuf:"varint,10,opt,name=threshold_amount,json=thresholdAmount,proto3" json:"threshold_amount,omitempty"`
	ReduceAmount      int64                  `protobuf:"varint,11,opt,name=reduce_amount,json=reduceAmount,proto3" json:"reduce_amount,omitempty"`
	DiscountRate      int32                  `protobuf:"varint,12,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	MaxDiscountAmount int64                  `protobuf:"varint,13,opt,name=max_discount_amount,json=maxDiscountAmount,proto3" json:"max_discount_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserCouponInfo) Reset() {
	*x = UserCouponInfo{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfo) ProtoMessage() {}

func (x *UserCouponInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfo.ProtoReflect.Descriptor instead.
func (*UserCouponInfo) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{13}
}

func (x *UserCouponInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCouponInfo) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UserCouponInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCouponInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCouponInfo) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNKNOWN
}

func (x *UserCouponInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCouponInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *UserCouponInfo) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UserCouponInfo) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

func (x *UserCouponInfo) GetThresholdAmount() int64 {
	if x != nil {
		return x.ThresholdAmount
	}
	return 0
}

func (x *UserCouponInfo) GetReduceAmount() int64 {
	if x != nil {
		return x.ReduceAmount
	}
	return 0
}

func (x *UserCouponInfo) GetDiscountRate() int32 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *UserCouponInfo) GetMaxDiscountAmount() int64 {
	if x != nil {
		return x.MaxDiscountAmount
	}
	return 0
}

type MyCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResp              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	List          []*UserCouponInfo      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyCouponsResp) Reset() {
	*x = MyCouponsResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCouponsResp) ProtoMessage() {}

func (x *MyCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCouponsResp.ProtoReflect.Descriptor instead.
func (*MyCouponsResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{14}
}

func (x *MyCouponsResp) GetPage() *PageResp {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *MyCouponsResp) GetList() []*UserCouponInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type AvailableCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderAmount   int64                  `protobuf:"varint,1,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"` // 订单金额（分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableCouponsReq) Reset() {
	*x = AvailableCouponsReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCouponsReq) ProtoMessage() {}

func (x *AvailableCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCouponsReq.ProtoReflect.Descriptor instead.
func (*AvailableCouponsReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{15}
}

func (x *AvailableCouponsReq) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

type AvailableCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     []*UserCouponInfo      `protobuf:"bytes,1,rep,name=available,proto3" json:"available,omitempty"`
	Unavailable   []*UserCouponInfo      `protobuf:"bytes,2,rep,name=unavailable,proto3" json:"unavailable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableCouponsResp) Reset() {
	*x = AvailableCouponsResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCouponsResp) ProtoMessage() {}

func (x *AvailableCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCouponsResp.ProtoReflect.Descriptor instead.
func (*AvailableCouponsResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{16}
}

func (x *AvailableCouponsResp) GetAvailable() []*UserCouponInfo {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *AvailableCouponsResp) GetUnavailable() []*UserCouponInfo {
	if x != nil {
		return x.Unavailable
	}
	return nil
}

type UseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId  uint64                 `protobuf:"varint,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	OrderAmount   int64                  `protobuf:"varint,3,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"` // 订单金额（分），用于折扣券精确计算
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponReq) Reset() {
	*x = UseCouponReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponReq) ProtoMessage() {}

func (x *UseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponReq.ProtoReflect.Descriptor instead.
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{17}
}

func (x *UseCouponReq) GetUserCouponId() uint64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *UseCouponReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UseCouponReq) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

type UseCouponResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,2,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UseCouponResp) Reset() {
	*x = UseCouponResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResp) ProtoMessage() {}

func (x *UseCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResp.ProtoReflect.Descriptor instead.
func (*UseCouponResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{18}
}

func (x *UseCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseCouponResp) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *UseCouponResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UnlockCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId  uint64                 `protobuf:"varint,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockCouponReq) Reset() {
	*x = UnlockCouponReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockCouponReq) ProtoMessage() {}

func (x *UnlockCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockCouponReq.ProtoReflect.Descriptor instead.
func (*UnlockCouponReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{19}
}

func (x *UnlockCouponReq) GetUserCouponId() uint64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *UnlockCouponReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type UnlockCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockCouponResp) Reset() {
	*x = UnlockCouponResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockCouponResp) ProtoMessage() {}

func (x *UnlockCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockCouponResp.ProtoReflect.Descriptor instead.
func (*UnlockCouponResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{20}
}

func (x *UnlockCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockCouponResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetUserCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId  uint64                 `protobuf:"varint,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"` // 用户优惠券ID（优先）
	CouponId      uint64                 `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`               // 优惠券定义ID（与上下文userId组合查询用户已领取的实例）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCouponReq) Reset() {
	*x = GetUserCouponReq{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCouponReq) ProtoMessage() {}

func (x *GetUserCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCouponReq.ProtoReflect.Descriptor instead.
func (*GetUserCouponReq) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserCouponReq) GetUserCouponId() uint64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *GetUserCouponReq) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

type GetUserCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupon        *UserCouponInfo        `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCouponResp) Reset() {
	*x = GetUserCouponResp{}
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCouponResp) ProtoMessage() {}

func (x *GetUserCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_service_marketing_rpc_marketing_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCouponResp.ProtoReflect.Descriptor instead.
func (*GetUserCouponResp) Descriptor() ([]byte, []int) {
	return file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserCouponResp) GetCoupon() *UserCouponInfo {
	if x != nil {
		return x.Coupon
	}
	return nil
}

var File_apps_service_marketing_rpc_marketing_proto protoreflect.FileDescriptor

const file_apps_service_marketing_rpc_marketing_proto_rawDesc = "" +
	"\n" +
	"*apps/service/marketing/rpc/marketing.proto\x12\tmarketing\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"1\n" +
	"\aPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"H\n" +
	"\bPageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x9e\x03\n" +
	"\x0fCreateCouponReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.marketing.CouponTypeR\x04type\x12)\n" +
	"\x10threshold_amount\x18\x03 \x01(\x03R\x0fthresholdAmount\x12#\n" +
	"\rreduce_amount\x18\x04 \x01(\x03R\freduceAmount\x12#\n" +
	"\rdiscount_rate\x18\x05 \x01(\x05R\fdiscountRate\x12.\n" +
	"\x13max_discount_amount\x18\x06 \x01(\x03R\x11maxDiscountAmount\x12%\n" +
	"\x0etotal_quantity\x18\a \x01(\x05R\rtotalQuantity\x12$\n" +
	"\x0eper_user_limit\x18\b \x01(\x05R\fperUserLimit\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\n" +
	" \x01(\x03R\aendTime\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\"\xc6\x03\n" +
	"\x0fUpdateCouponReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.marketing.CouponTypeR\x04type\x12)\n" +
	"\x10threshold_amount\x18\x04 \x01(\x03R\x0fthresholdAmount\x12#\n" +
	"\rreduce_amount\x18\x05 \x01(\x03R\freduceAmount\x12#\n" +
	"\rdiscount_rate\x18\x06 \x01(\x05R\fdiscountRate\x12.\n" +
	"\x13max_discount_amount\x18\a \x01(\x03R\x11maxDiscountAmount\x12%\n" +
	"\x0etotal_quantity\x18\b \x01(\x05R\rtotalQuantity\x12$\n" +
	"\x0eper_user_limit\x18\t \x01(\x05R\fperUserLimit\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\"\xaf\x04\n" +
	"\n" +
	"CouponInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.marketing.CouponTypeR\x04type\x12)\n" +
	"\x10threshold_amount\x18\x04 \x01(\x03R\x0fthresholdAmount\x12#\n" +
	"\rreduce_amount\x18\x05 \x01(\x03R\freduceAmount\x12#\n" +
	"\rdiscount_rate\x18\x06 \x01(\x05R\fdiscountRate\x12.\n" +
	"\x13max_discount_amount\x18\a \x01(\x03R\x11maxDiscountAmount\x12%\n" +
	"\x0etotal_quantity\x18\b \x01(\x05R\rtotalQuantity\x12#\n" +
	"\rused_quantity\x18\t \x01(\x05R\fusedQuantity\x12$\n" +
	"\x0eper_user_limit\x18\n" +
	" \x01(\x05R\fperUserLimit\x12\x1d\n" +
	"\n" +
	"start_time\x18\v \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\f \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12(\n" +
	"\x10user_claim_count\x18\x10 \x01(\x05R\x0euserClaimCount\";\n" +
	"\n" +
	"CouponResp\x12-\n" +
	"\x06coupon\x18\x01 \x01(\v2\x15.marketing.CouponInfoR\x06coupon\"8\n" +
	"\x0eListCouponsReq\x12&\n" +
	"\x04page\x18\x01 \x01(\v2\x12.marketing.PageReqR\x04page\"e\n" +
	"\x0fListCouponsResp\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.marketing.PageRespR\x04page\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.marketing.CouponInfoR\x04list\"-\n" +
	"\x0eClaimCouponReq\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x04R\bcouponId\"X\n" +
	"\x0fClaimCouponResp\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\x04R\fuserCouponId\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\x03R\n" +
	"expireTime\"N\n" +
	"\fMyCouponsReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.marketing.PageReqR\x04page\"\xbd\x03\n" +
	"\x0eUserCouponInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\x04R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.marketing.CouponTypeR\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vexpire_time\x18\a \x01(\x03R\n" +
	"expireTime\x12\x19\n" +
	"\border_sn\x18\b \x01(\tR\aorderSn\x12-\n" +
	"\x12unavailable_reason\x18\t \x01(\tR\x11unavailableReason\x12)\n" +
	"\x10threshold_amount\x18\n" +
	" \x01(\x03R\x0fthresholdAmount\x12#\n" +
	"\rreduce_amount\x18\v \x01(\x03R\freduceAmount\x12#\n" +
	"\rdiscount_rate\x18\f \x01(\x05R\fdiscountRate\x12.\n" +
	"\x13max_discount_amount\x18\r \x01(\x03R\x11maxDiscountAmount\"g\n" +
	"\rMyCouponsResp\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.marketing.PageRespR\x04page\x12-\n" +
	"\x04list\x18\x02 \x03(\v2\x19.marketing.UserCouponInfoR\x04list\"8\n" +
	"\x13AvailableCouponsReq\x12!\n" +
	"\forder_amount\x18\x01 \x01(\x03R\vorderAmount\"\x8c\x01\n" +
	"\x14AvailableCouponsResp\x127\n" +
	"\tavailable\x18\x01 \x03(\v2\x19.marketing.UserCouponInfoR\tavailable\x12;\n" +
	"\vunavailable\x18\x02 \x03(\v2\x19.marketing.UserCouponInfoR\vunavailable\"r\n" +
	"\fUseCouponReq\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\x04R\fuserCouponId\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\x12!\n" +
	"\forder_amount\x18\x03 \x01(\x03R\vorderAmount\"o\n" +
	"\rUseCouponResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fdiscount_amount\x18\x02 \x01(\x03R\x0ediscountAmount\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"R\n" +
	"\x0fUnlockCouponReq\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\x04R\fuserCouponId\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\"I\n" +
	"\x10UnlockCouponResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"U\n" +
	"\x10GetUserCouponReq\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\x04R\fuserCouponId\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\x04R\bcouponId\"F\n" +
	"\x11GetUserCouponResp\x121\n" +
	"\x06coupon\x18\x01 \x01(\v2\x19.marketing.UserCouponInfoR\x06coupon*z\n" +
	"\n" +
	"CouponType\x12\x17\n" +
	"\x13COUPON_TYPE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17COUPON_TYPE_FULL_REDUCE\x10\x01\x12\x18\n" +
	"\x14COUPON_TYPE_DISCOUNT\x10\x02\x12\x1c\n" +
	"\x18COUPON_TYPE_NO_THRESHOLD\x10\x032\xe7\x05\n" +
	"\tMarketing\x12<\n" +
	"\fCreateCoupon\x12\x1a.marketing.CreateCouponReq\x1a\x10.marketing.Empty\x12<\n" +
	"\fUpdateCoupon\x12\x1a.marketing.UpdateCouponReq\x1a\x10.marketing.Empty\x122\n" +
	"\fDeleteCoupon\x12\x10.marketing.IdReq\x1a\x10.marketing.Empty\x124\n" +
	"\tGetCoupon\x12\x10.marketing.IdReq\x1a\x15.marketing.CouponResp\x12D\n" +
	"\vListCoupons\x12\x19.marketing.ListCouponsReq\x1a\x1a.marketing.ListCouponsResp\x12D\n" +
	"\vClaimCoupon\x12\x19.marketing.ClaimCouponReq\x1a\x1a.marketing.ClaimCouponResp\x12>\n" +
	"\tMyCoupons\x12\x17.marketing.MyCouponsReq\x1a\x18.marketing.MyCouponsResp\x12S\n" +
	"\x10AvailableCoupons\x12\x1e.marketing.AvailableCouponsReq\x1a\x1f.marketing.AvailableCouponsResp\x12>\n" +
	"\tUseCoupon\x12\x17.marketing.UseCouponReq\x1a\x18.marketing.UseCouponResp\x12G\n" +
	"\fUnlockCoupon\x12\x1a.marketing.UnlockCouponReq\x1a\x1b.marketing.UnlockCouponResp\x12J\n" +
	"\rGetUserCoupon\x12\x1b.marketing.GetUserCouponReq\x1a\x1c.marketing.GetUserCouponRespB\rZ\v./marketingb\x06proto3"

var (
	file_apps_service_marketing_rpc_marketing_proto_rawDescOnce sync.Once
	file_apps_service_marketing_rpc_marketing_proto_rawDescData []byte
)

func file_apps_service_marketing_rpc_marketing_proto_rawDescGZIP() []byte {
	file_apps_service_marketing_rpc_marketing_proto_rawDescOnce.Do(func() {
		file_apps_service_marketing_rpc_marketing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_service_marketing_rpc_marketing_proto_rawDesc), len(file_apps_service_marketing_rpc_marketing_proto_rawDesc)))
	})
	return file_apps_service_marketing_rpc_marketing_proto_rawDescData
}

var file_apps_service_marketing_rpc_marketing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_service_marketing_rpc_marketing_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_apps_service_marketing_rpc_marketing_proto_goTypes = []any{
	(CouponType)(0),              // 0: marketing.CouponType
	(*Empty)(nil),                // 1: marketing.Empty
	(*IdReq)(nil),                // 2: marketing.IdReq
	(*PageReq)(nil),              // 3: marketing.PageReq
	(*PageResp)(nil),             // 4: marketing.PageResp
	(*CreateCouponReq)(nil),      // 5: marketing.CreateCouponReq
	(*UpdateCouponReq)(nil),      // 6: marketing.UpdateCouponReq
	(*CouponInfo)(nil),           // 7: marketing.CouponInfo
	(*CouponResp)(nil),           // 8: marketing.CouponResp
	(*ListCouponsReq)(nil),       // 9: marketing.ListCouponsReq
	(*ListCouponsResp)(nil),      // 10: marketing.ListCouponsResp
	(*ClaimCouponReq)(nil),       // 11: marketing.ClaimCouponReq
	(*ClaimCouponResp)(nil),      // 12: marketing.ClaimCouponResp
	(*MyCouponsReq)(nil),         // 13: marketing.MyCouponsReq
	(*UserCouponInfo)(nil),       // 14: marketing.UserCouponInfo
	(*MyCouponsResp)(nil),        // 15: marketing.MyCouponsResp
	(*AvailableCouponsReq)(nil),  // 16: marketing.AvailableCouponsReq
	(*AvailableCouponsResp)(nil), // 17: marketing.AvailableCouponsResp
	(*UseCouponReq)(nil),         // 18: marketing.UseCouponReq
	(*UseCouponResp)(nil),        // 19: marketing.UseCouponResp
	(*UnlockCouponReq)(nil),      // 20: marketing.UnlockCouponReq
	(*UnlockCouponResp)(nil),     // 21: marketing.UnlockCouponResp
	(*GetUserCouponReq)(nil),     // 22: marketing.GetUserCouponReq
	(*GetUserCouponResp)(nil),    // 23: marketing.GetUserCouponResp
}
var file_apps_service_marketing_rpc_marketing_proto_depIdxs = []int32{
	0,  // 0: marketing.CreateCouponReq.type:type_name -> marketing.CouponType
	0,  // 1: marketing.UpdateCouponReq.type:type_name -> marketing.CouponType
	0,  // 2: marketing.CouponInfo.type:type_name -> marketing.CouponType
	7,  // 3: marketing.CouponResp.coupon:type_name -> marketing.CouponInfo
	3,  // 4: marketing.ListCouponsReq.page:type_name -> marketing.PageReq
	4,  // 5: marketing.ListCouponsResp.page:type_name -> marketing.PageResp
	7,  // 6: marketing.ListCouponsResp.list:type_name -> marketing.CouponInfo
	3,  // 7: marketing.MyCouponsReq.page:type_name -> marketing.PageReq
	0,  // 8: marketing.UserCouponInfo.type:type_name -> marketing.CouponType
	4,  // 9: marketing.MyCouponsResp.page:type_name -> marketing.PageResp
	14, // 10: marketing.MyCouponsResp.list:type_name -> marketing.UserCouponInfo
	14, // 11: marketing.AvailableCouponsResp.available:type_name -> marketing.UserCouponInfo
	14, // 12: marketing.AvailableCouponsResp.unavailable:type_name -> marketing.UserCouponInfo
	14, // 13: marketing.GetUserCouponResp.coupon:type_name -> marketing.UserCouponInfo
	5,  // 14: marketing.Marketing.CreateCoupon:input_type -> marketing.CreateCouponReq
	6,  // 15: marketing.Marketing.UpdateCoupon:input_type -> marketing.UpdateCouponReq
	2,  // 16: marketing.Marketing.DeleteCoupon:input_type -> marketing.IdReq
	2,  // 17: marketing.Marketing.GetCoupon:input_type -> marketing.IdReq
	9,  // 18: marketing.Marketing.ListCoupons:input_type -> marketing.ListCouponsReq
	11, // 19: marketing.Marketing.ClaimCoupon:input_type -> marketing.ClaimCouponReq
	13, // 20: marketing.Marketing.MyCoupons:input_type -> marketing.MyCouponsReq
	16, // 21: marketing.Marketing.AvailableCoupons:input_type -> marketing.AvailableCouponsReq
	18, // 22: marketing.Marketing.UseCoupon:input_type -> marketing.UseCouponReq
	20, // 23: marketing.Marketing.UnlockCoupon:input_type -> marketing.UnlockCouponReq
	22, // 24: marketing.Marketing.GetUserCoupon:input_type -> marketing.GetUserCouponReq
	1,  // 25: marketing.Marketing.CreateCoupon:output_type -> marketing.Empty
	1,  // 26: marketing.Marketing.UpdateCoupon:output_type -> marketing.Empty
	1,  // 27: marketing.Marketing.DeleteCoupon:output_type -> marketing.Empty
	8,  // 28: marketing.Marketing.GetCoupon:output_type -> marketing.CouponResp
	10, // 29: marketing.Marketing.ListCoupons:output_type -> marketing.ListCouponsResp
	12, // 30: marketing.Marketing.ClaimCoupon:output_type -> marketing.ClaimCouponResp
	15, // 31: marketing.Marketing.MyCoupons:output_type -> marketing.MyCouponsResp
	17, // 32: marketing.Marketing.AvailableCoupons:output_type -> marketing.AvailableCouponsResp
	19, // 33: marketing.Marketing.UseCoupon:output_type -> marketing.UseCouponResp
	21, // 34: marketing.Marketing.UnlockCoupon:output_type -> marketing.UnlockCouponResp
	23, // 35: marketing.Marketing.GetUserCoupon:output_type -> marketing.GetUserCouponResp
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_apps_service_marketing_rpc_marketing_proto_init() }
func file_apps_service_marketing_rpc_marketing_proto_init() {
	if File_apps_service_marketing_rpc_marketing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_service_marketing_rpc_marketing_proto_rawDesc), len(file_apps_service_marketing_rpc_marketing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_service_marketing_rpc_marketing_proto_goTypes,
		DependencyIndexes: file_apps_service_marketing_rpc_marketing_proto_depIdxs,
		EnumInfos:         file_apps_service_marketing_rpc_marketing_proto_enumTypes,
		MessageInfos:      file_apps_service_marketing_rpc_marketing_proto_msgTypes,
	}.Build()
	File_apps_service_marketing_rpc_marketing_proto = out.File
	file_apps_service_marketing_rpc_marketing_proto_goTypes = nil
	file_apps_service_marketing_rpc_marketing_proto_depIdxs = nil
}
