// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/internal/logic/userinternal"
	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/types/user"
)

type UserInternalServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserInternalServer
}

func NewUserInternalServer(svcCtx *svc.ServiceContext) *UserInternalServer {
	return &UserInternalServer{
		svcCtx: svcCtx,
	}
}

// GetUserById 根据用户ID获取用户基本信息（用于订单、购物车等）
func (s *UserInternalServer) GetUserById(ctx context.Context, in *user.GetUserByIdReq) (*user.UserBasicInfo, error) {
	l := userinternallogic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

// CheckUserStatus 校验用户状态（是否被封禁/限制下单）
func (s *UserInternalServer) CheckUserStatus(ctx context.Context, in *user.CheckUserStatusReq) (*user.CheckUserStatusResp, error) {
	l := userinternallogic.NewCheckUserStatusLogic(ctx, s.svcCtx)
	return l.CheckUserStatus(in)
}

// GetAddressById 获取地址信息
func (s *UserInternalServer) GetAddressById(ctx context.Context, in *user.GetAddressReq) (*user.AddressItem, error) {
	l := userinternallogic.NewGetAddressByIdLogic(ctx, s.svcCtx)
	return l.GetAddressById(in)
}
