// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package userinternal

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAddressReq          = user.AddAddressReq
	AddressDetail          = user.AddressDetail
	AddressItem            = user.AddressItem
	AddressListReq         = user.AddressListReq
	AddressListResp        = user.AddressListResp
	AdminResetPasswordReq  = user.AdminResetPasswordReq
	BanUserReq             = user.BanUserReq
	BatchGetUserByIdReq    = user.BatchGetUserByIdReq
	BatchUserBasicInfoResp = user.BatchUserBasicInfoResp
	CaptchaReq             = user.CaptchaReq
	CheckUserStatusReq     = user.CheckUserStatusReq
	CheckUserStatusResp    = user.CheckUserStatusResp
	DailyStat              = user.DailyStat
	DeleteAccountReq       = user.DeleteAccountReq
	EmptyReq               = user.EmptyReq
	EmptyResp              = user.EmptyResp
	ErrDetail              = user.ErrDetail
	GetAddressReq          = user.GetAddressReq
	GetUserByIdReq         = user.GetUserByIdReq
	GetUserDetailReq       = user.GetUserDetailReq
	GetUserDetailResp      = user.GetUserDetailResp
	GetUserStatisticsReq   = user.GetUserStatisticsReq
	GetUserStatisticsResp  = user.GetUserStatisticsResp
	IdPathReq              = user.IdPathReq
	ListLoginLogsReq       = user.ListLoginLogsReq
	ListLoginLogsResp      = user.ListLoginLogsResp
	ListPunishLogsReq      = user.ListPunishLogsReq
	ListPunishLogsResp     = user.ListPunishLogsResp
	ListUsersReq           = user.ListUsersReq
	ListUsersResp          = user.ListUsersResp
	LoginLogItem           = user.LoginLogItem
	LoginReq               = user.LoginReq
	LoginResp              = user.LoginResp
	LogoutReq              = user.LogoutReq
	MobileLoginReq         = user.MobileLoginReq
	OssTokenReq            = user.OssTokenReq
	OssTokenResp           = user.OssTokenResp
	PunishLogItem          = user.PunishLogItem
	RefreshTokenReq        = user.RefreshTokenReq
	RegisterReq            = user.RegisterReq
	ResetPasswordReq       = user.ResetPasswordReq
	UnbanUserReq           = user.UnbanUserReq
	UpdatePasswordReq      = user.UpdatePasswordReq
	UpdatePhoneReq         = user.UpdatePhoneReq
	UpdateUserInfoReq      = user.UpdateUserInfoReq
	UserBasicInfo          = user.UserBasicInfo
	UserInfoResp           = user.UserInfoResp
	UserListItem           = user.UserListItem

	UserInternal interface {
		// GetUserById 根据用户ID获取用户基本信息（用于订单、购物车等）
		GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserBasicInfo, error)
		// CheckUserStatus 校验用户状态（是否被封禁/限制下单）
		CheckUserStatus(ctx context.Context, in *CheckUserStatusReq, opts ...grpc.CallOption) (*CheckUserStatusResp, error)
		// GetAddressById 获取地址信息
		GetAddressById(ctx context.Context, in *GetAddressReq, opts ...grpc.CallOption) (*AddressItem, error)
	}

	defaultUserInternal struct {
		cli zrpc.Client
	}
)

func NewUserInternal(cli zrpc.Client) UserInternal {
	return &defaultUserInternal{
		cli: cli,
	}
}

// GetUserById 根据用户ID获取用户基本信息（用于订单、购物车等）
func (m *defaultUserInternal) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	client := user.NewUserInternalClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

// CheckUserStatus 校验用户状态（是否被封禁/限制下单）
func (m *defaultUserInternal) CheckUserStatus(ctx context.Context, in *CheckUserStatusReq, opts ...grpc.CallOption) (*CheckUserStatusResp, error) {
	client := user.NewUserInternalClient(m.cli.Conn())
	return client.CheckUserStatus(ctx, in, opts...)
}

// GetAddressById 获取地址信息
func (m *defaultUserInternal) GetAddressById(ctx context.Context, in *GetAddressReq, opts ...grpc.CallOption) (*AddressItem, error) {
	client := user.NewUserInternalClient(m.cli.Conn())
	return client.GetAddressById(ctx, in, opts...)
}
