// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: product.proto

package product

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/product/rpc/types/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdjustStockReq           = product.AdjustStockReq
	AttrFilter               = product.AttrFilter
	AttributeItem            = product.AttributeItem
	BatchSkuResp             = product.BatchSkuResp
	BatchStockResp           = product.BatchStockResp
	CalculateFreightReq      = product.CalculateFreightReq
	CalculatePriceResp       = product.CalculatePriceResp
	Category                 = product.Category
	CategoryResp             = product.CategoryResp
	CategoryTreeResp         = product.CategoryTreeResp
	CreateCategoryReq        = product.CreateCategoryReq
	CreateFreightTemplateReq = product.CreateFreightTemplateReq
	CreateProductReq         = product.CreateProductReq
	CreateSkuReq             = product.CreateSkuReq
	Empty                    = product.Empty
	FreightTemplate          = product.FreightTemplate
	IdReq                    = product.IdReq
	ListCategoriesReq        = product.ListCategoriesReq
	ListCategoriesResp       = product.ListCategoriesResp
	ListFreightTemplatesResp = product.ListFreightTemplatesResp
	ListProductsAdminReq     = product.ListProductsAdminReq
	ListProductsAdminResp    = product.ListProductsAdminResp
	ListSkusByProductReq     = product.ListSkusByProductReq
	ListSkusResp             = product.ListSkusResp
	ListStockLogsReq         = product.ListStockLogsReq
	ListStockLogsResp        = product.ListStockLogsResp
	PageReq                  = product.PageReq
	PageResp                 = product.PageResp
	ProductAdminItem         = product.ProductAdminItem
	ProductDetailResp        = product.ProductDetailResp
	ProductItem              = product.ProductItem
	ProductListReq           = product.ProductListReq
	ProductListResp          = product.ProductListResp
	RecommendReq             = product.RecommendReq
	RecordStockLogReq        = product.RecordStockLogReq
	SkuIdsReq                = product.SkuIdsReq
	SkuItem                  = product.SkuItem
	SkuListResp              = product.SkuListResp
	SkuSimple                = product.SkuSimple
	SkuStockItem             = product.SkuStockItem
	SkuStockResult           = product.SkuStockResult
	SpecItem                 = product.SpecItem
	StockChangeResp          = product.StockChangeResp
	StockLog                 = product.StockLog
	UpdateCategoryReq        = product.UpdateCategoryReq
	UpdateFreightTemplateReq = product.UpdateFreightTemplateReq
	UpdateProductReq         = product.UpdateProductReq
	UpdateProductStatusReq   = product.UpdateProductStatusReq
	UpdateSkuReq             = product.UpdateSkuReq
	UpdateStockReq           = product.UpdateStockReq

	Product interface {
		// 分类
		CategoryTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryTreeResp, error)
		CategoryInfo(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CategoryResp, error)
		// 商品
		ListProducts(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListResp, error)
		ProductDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ProductDetailResp, error)
		// 推荐（后续可拆服务）
		Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*ProductListResp, error)
		// SKU
		BatchGetSkus(ctx context.Context, in *SkuIdsReq, opts ...grpc.CallOption) (*BatchSkuResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

// 分类
func (m *defaultProduct) CategoryTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryTreeResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CategoryTree(ctx, in, opts...)
}

func (m *defaultProduct) CategoryInfo(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CategoryResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CategoryInfo(ctx, in, opts...)
}

// 商品
func (m *defaultProduct) ListProducts(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

func (m *defaultProduct) ProductDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ProductDetailResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ProductDetail(ctx, in, opts...)
}

// 推荐（后续可拆服务）
func (m *defaultProduct) Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Recommend(ctx, in, opts...)
}

// SKU
func (m *defaultProduct) BatchGetSkus(ctx context.Context, in *SkuIdsReq, opts ...grpc.CallOption) (*BatchSkuResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.BatchGetSkus(ctx, in, opts...)
}
