// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/internal/logic/adminorder"
	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"
)

type AdminOrderServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminOrderServer
}

func NewAdminOrderServer(svcCtx *svc.ServiceContext) *AdminOrderServer {
	return &AdminOrderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminOrderServer) ListOrders(ctx context.Context, in *admin.AdminListOrdersReq) (*admin.AdminListOrdersResp, error) {
	l := adminorderlogic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *AdminOrderServer) GetOrder(ctx context.Context, in *admin.AdminGetOrderReq) (*admin.AdminOrderDetailResp, error) {
	l := adminorderlogic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *AdminOrderServer) ShipOrder(ctx context.Context, in *admin.AdminShipOrderReq) (*admin.Empty, error) {
	l := adminorderlogic.NewShipOrderLogic(ctx, s.svcCtx)
	return l.ShipOrder(in)
}
