// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package server

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/search/rpc/internal/logic/search"
	"github.com/ZY0506/PrimeMall/apps/service/search/rpc/internal/svc"
	"github.com/ZY0506/PrimeMall/apps/service/search/rpc/types/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

// ES商品搜索
func (s *SearchServer) SearchProducts(ctx context.Context, in *search.SearchProductsReq) (*search.SearchProductsResp, error) {
	l := searchlogic.NewSearchProductsLogic(ctx, s.svcCtx)
	return l.SearchProducts(in)
}

// ES商品搜索建议（补全）
func (s *SearchServer) SuggestProducts(ctx context.Context, in *search.SuggestReq) (*search.SuggestResp, error) {
	l := searchlogic.NewSuggestProductsLogic(ctx, s.svcCtx)
	return l.SuggestProducts(in)
}

// 热搜词列表
func (s *SearchServer) GetHotKeywords(ctx context.Context, in *search.Empty) (*search.HotKeywordsResp, error) {
	l := searchlogic.NewGetHotKeywordsLogic(ctx, s.svcCtx)
	return l.GetHotKeywords(in)
}

// 用户搜索历史
func (s *SearchServer) GetSearchHistory(ctx context.Context, in *search.SearchHistoryReq) (*search.SearchHistoryResp, error) {
	l := searchlogic.NewGetSearchHistoryLogic(ctx, s.svcCtx)
	return l.GetSearchHistory(in)
}

// 清除搜索历史
func (s *SearchServer) ClearSearchHistory(ctx context.Context, in *search.ClearSearchHistoryReq) (*search.Empty, error) {
	l := searchlogic.NewClearSearchHistoryLogic(ctx, s.svcCtx)
	return l.ClearSearchHistory(in)
}

// 同步商品到ES
func (s *SearchServer) SyncProductToES(ctx context.Context, in *search.SyncProductReq) (*search.Empty, error) {
	l := searchlogic.NewSyncProductToESLogic(ctx, s.svcCtx)
	return l.SyncProductToES(in)
}

// 批量同步商品到ES
func (s *SearchServer) BatchSyncProducts(ctx context.Context, in *search.BatchSyncProductsReq) (*search.Empty, error) {
	l := searchlogic.NewBatchSyncProductsLogic(ctx, s.svcCtx)
	return l.BatchSyncProducts(in)
}

// 从ES删除商品
func (s *SearchServer) DeleteProductFromES(ctx context.Context, in *search.DeleteProductReq) (*search.Empty, error) {
	l := searchlogic.NewDeleteProductFromESLogic(ctx, s.svcCtx)
	return l.DeleteProductFromES(in)
}
