// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminFieldNames          = builder.RawFieldNames(&Admin{})
	adminRows                = strings.Join(adminFieldNames, ",")
	adminRowsExpectAutoSet   = strings.Join(stringx.Remove(adminFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminRowsWithPlaceHolder = strings.Join(stringx.Remove(adminFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminModel interface {
		Insert(ctx context.Context, data *Admin) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Admin, error)
		FindOneByUsername(ctx context.Context, username string) (*Admin, error)
		Update(ctx context.Context, data *Admin) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAdminModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Admin struct {
		Id            uint64       `db:"id"`              // 管理员ID
		Username      string       `db:"username"`        // 登录用户名
		Password      string       `db:"password"`        // 登录密码（加密）
		RealName      string       `db:"real_name"`       // 真实姓名
		Avatar        string       `db:"avatar"`          // 头像URL
		RoleId        uint64       `db:"role_id"`         // 角色ID：0-无角色
		Status        int64        `db:"status"`          // 状态：1-启用，2-禁用
		LastLoginTime sql.NullTime `db:"last_login_time"` // 最后登录时间
		LastLoginIp   string       `db:"last_login_ip"`   // 最后登录IP
		CreatedAt     time.Time    `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time    `db:"updated_at"`      // 更新时间
	}
)

func newAdminModel(conn sqlx.SqlConn) *defaultAdminModel {
	return &defaultAdminModel{
		conn:  conn,
		table: "`admin`",
	}
}

func (m *defaultAdminModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminModel) FindOne(ctx context.Context, id uint64) (*Admin, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRows, m.table)
	var resp Admin
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) FindOneByUsername(ctx context.Context, username string) (*Admin, error) {
	var resp Admin
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) Insert(ctx context.Context, data *Admin) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, adminRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.Password, data.RealName, data.Avatar, data.RoleId, data.Status, data.LastLoginTime, data.LastLoginIp)
	return ret, err
}

func (m *defaultAdminModel) Update(ctx context.Context, newData *Admin) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Username, newData.Password, newData.RealName, newData.Avatar, newData.RoleId, newData.Status, newData.LastLoginTime, newData.LastLoginIp, newData.Id)
	return err
}

func (m *defaultAdminModel) tableName() string {
	return m.table
}
