// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	helpCategoryFieldNames          = builder.RawFieldNames(&HelpCategory{})
	helpCategoryRows                = strings.Join(helpCategoryFieldNames, ",")
	helpCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(helpCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	helpCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(helpCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	helpCategoryModel interface {
		Insert(ctx context.Context, data *HelpCategory) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*HelpCategory, error)
		Update(ctx context.Context, data *HelpCategory) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultHelpCategoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HelpCategory struct {
		Id        uint64    `db:"id"`         // 分类ID
		Name      string    `db:"name"`       // 分类名称
		Icon      string    `db:"icon"`       // 分类图标URL
		Sort      int64     `db:"sort"`       // 排序值：数值越小越靠前
		Status    int64     `db:"status"`     // 状态：1-启用，2-禁用
		CreatedAt time.Time `db:"created_at"` // 创建时间
	}
)

func newHelpCategoryModel(conn sqlx.SqlConn) *defaultHelpCategoryModel {
	return &defaultHelpCategoryModel{
		conn:  conn,
		table: "`help_category`",
	}
}

func (m *defaultHelpCategoryModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHelpCategoryModel) FindOne(ctx context.Context, id uint64) (*HelpCategory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", helpCategoryRows, m.table)
	var resp HelpCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHelpCategoryModel) Insert(ctx context.Context, data *HelpCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, helpCategoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Icon, data.Sort, data.Status)
	return ret, err
}

func (m *defaultHelpCategoryModel) Update(ctx context.Context, data *HelpCategory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, helpCategoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Icon, data.Sort, data.Status, data.Id)
	return err
}

func (m *defaultHelpCategoryModel) tableName() string {
	return m.table
}
