// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noticeFieldNames          = builder.RawFieldNames(&Notice{})
	noticeRows                = strings.Join(noticeFieldNames, ",")
	noticeRowsExpectAutoSet   = strings.Join(stringx.Remove(noticeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noticeRowsWithPlaceHolder = strings.Join(stringx.Remove(noticeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	noticeModel interface {
		Insert(ctx context.Context, data *Notice) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Notice, error)
		Update(ctx context.Context, data *Notice) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultNoticeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Notice struct {
		Id          uint64       `db:"id"`           // 公告ID
		Title       string       `db:"title"`        // 公告标题
		Content     string       `db:"content"`      // 公告内容（支持HTML）
		Type        int64        `db:"type"`         // 公告类型：1-系统公告，2-活动公告
		Priority    int64        `db:"priority"`     // 优先级：1-普通，2-重要，3-置顶
		Status      int64        `db:"status"`       // 状态：1-已发布，2-草稿，3-已下线
		PublishTime sql.NullTime `db:"publish_time"` // 发布时间
		CreatedBy   string       `db:"created_by"`   // 创建人（管理员用户名）
		CreatedAt   time.Time    `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time    `db:"updated_at"`   // 更新时间
	}
)

func newNoticeModel(conn sqlx.SqlConn) *defaultNoticeModel {
	return &defaultNoticeModel{
		conn:  conn,
		table: "`notice`",
	}
}

func (m *defaultNoticeModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultNoticeModel) FindOne(ctx context.Context, id uint64) (*Notice, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeRows, m.table)
	var resp Notice
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeModel) Insert(ctx context.Context, data *Notice) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, noticeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.Type, data.Priority, data.Status, data.PublishTime, data.CreatedBy)
	return ret, err
}

func (m *defaultNoticeModel) Update(ctx context.Context, data *Notice) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, noticeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.Type, data.Priority, data.Status, data.PublishTime, data.CreatedBy, data.Id)
	return err
}

func (m *defaultNoticeModel) tableName() string {
	return m.table
}
