// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: admin.proto

package adminuser

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminAdjustStockReq           = admin.AdminAdjustStockReq
	AdminAfterSaleDetailResp      = admin.AdminAfterSaleDetailResp
	AdminAfterSaleItem            = admin.AdminAfterSaleItem
	AdminBanUserReq               = admin.AdminBanUserReq
	AdminCategoryItem             = admin.AdminCategoryItem
	AdminCategoryTreeResp         = admin.AdminCategoryTreeResp
	AdminCreateCategoryReq        = admin.AdminCreateCategoryReq
	AdminCreateFreightTemplateReq = admin.AdminCreateFreightTemplateReq
	AdminCreateProductReq         = admin.AdminCreateProductReq
	AdminFreightTemplateInfo      = admin.AdminFreightTemplateInfo
	AdminGetAfterSaleReq          = admin.AdminGetAfterSaleReq
	AdminGetOrderReq              = admin.AdminGetOrderReq
	AdminGetUserDetailReq         = admin.AdminGetUserDetailReq
	AdminGetUserDetailResp        = admin.AdminGetUserDetailResp
	AdminHandleAfterSaleReq       = admin.AdminHandleAfterSaleReq
	AdminInfo                     = admin.AdminInfo
	AdminListAfterSalesReq        = admin.AdminListAfterSalesReq
	AdminListAfterSalesResp       = admin.AdminListAfterSalesResp
	AdminListFreightTemplatesResp = admin.AdminListFreightTemplatesResp
	AdminListOrdersReq            = admin.AdminListOrdersReq
	AdminListOrdersResp           = admin.AdminListOrdersResp
	AdminListProductsReq          = admin.AdminListProductsReq
	AdminListProductsResp         = admin.AdminListProductsResp
	AdminListStockLogsReq         = admin.AdminListStockLogsReq
	AdminListStockLogsResp        = admin.AdminListStockLogsResp
	AdminListUsersReq             = admin.AdminListUsersReq
	AdminListUsersResp            = admin.AdminListUsersResp
	AdminLogInfo                  = admin.AdminLogInfo
	AdminLoginReq                 = admin.AdminLoginReq
	AdminLoginResp                = admin.AdminLoginResp
	AdminOrderAddress             = admin.AdminOrderAddress
	AdminOrderDetailResp          = admin.AdminOrderDetailResp
	AdminOrderItem                = admin.AdminOrderItem
	AdminOrderProductItem         = admin.AdminOrderProductItem
	AdminPageReq                  = admin.AdminPageReq
	AdminProductDetailResp        = admin.AdminProductDetailResp
	AdminProductItem              = admin.AdminProductItem
	AdminShipOrderReq             = admin.AdminShipOrderReq
	AdminSkuDetailItem            = admin.AdminSkuDetailItem
	AdminSkuItem                  = admin.AdminSkuItem
	AdminSkuStockItem             = admin.AdminSkuStockItem
	AdminSkuStockResult           = admin.AdminSkuStockResult
	AdminSpecItem                 = admin.AdminSpecItem
	AdminStockChangeResp          = admin.AdminStockChangeResp
	AdminStockLogItem             = admin.AdminStockLogItem
	AdminUnbanUserReq             = admin.AdminUnbanUserReq
	AdminUpdateCategoryReq        = admin.AdminUpdateCategoryReq
	AdminUpdateFreightTemplateReq = admin.AdminUpdateFreightTemplateReq
	AdminUpdateProductReq         = admin.AdminUpdateProductReq
	AdminUpdateProductStatusReq   = admin.AdminUpdateProductStatusReq
	AdminUserItem                 = admin.AdminUserItem
	CreateAdminReq                = admin.CreateAdminReq
	DeleteAdminReq                = admin.DeleteAdminReq
	Empty                         = admin.Empty
	GetAdminReq                   = admin.GetAdminReq
	GetAdminResp                  = admin.GetAdminResp
	GetCurrentAdminResp           = admin.GetCurrentAdminResp
	IdReq                         = admin.IdReq
	ListAdminLogReq               = admin.ListAdminLogReq
	ListAdminLogResp              = admin.ListAdminLogResp
	ListAdminReq                  = admin.ListAdminReq
	ListAdminResp                 = admin.ListAdminResp
	ListRoleResp                  = admin.ListRoleResp
	RoleInfo                      = admin.RoleInfo
	UpdateAdminReq                = admin.UpdateAdminReq
	UpdatePasswordReq             = admin.UpdatePasswordReq

	AdminUser interface {
		ListUsers(ctx context.Context, in *AdminListUsersReq, opts ...grpc.CallOption) (*AdminListUsersResp, error)
		GetUserDetail(ctx context.Context, in *AdminGetUserDetailReq, opts ...grpc.CallOption) (*AdminGetUserDetailResp, error)
		BanUser(ctx context.Context, in *AdminBanUserReq, opts ...grpc.CallOption) (*Empty, error)
		UnbanUser(ctx context.Context, in *AdminUnbanUserReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAdminUser struct {
		cli zrpc.Client
	}
)

func NewAdminUser(cli zrpc.Client) AdminUser {
	return &defaultAdminUser{
		cli: cli,
	}
}

func (m *defaultAdminUser) ListUsers(ctx context.Context, in *AdminListUsersReq, opts ...grpc.CallOption) (*AdminListUsersResp, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultAdminUser) GetUserDetail(ctx context.Context, in *AdminGetUserDetailReq, opts ...grpc.CallOption) (*AdminGetUserDetailResp, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}

func (m *defaultAdminUser) BanUser(ctx context.Context, in *AdminBanUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.BanUser(ctx, in, opts...)
}

func (m *defaultAdminUser) UnbanUser(ctx context.Context, in *AdminUnbanUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.UnbanUser(ctx, in, opts...)
}
