// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package adminuser

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminBanUserReq        = admin.AdminBanUserReq
	AdminGetUserDetailReq  = admin.AdminGetUserDetailReq
	AdminGetUserDetailResp = admin.AdminGetUserDetailResp
	AdminListUsersReq      = admin.AdminListUsersReq
	AdminListUsersResp     = admin.AdminListUsersResp
	AdminUnbanUserReq      = admin.AdminUnbanUserReq
	Empty                  = admin.Empty

	AdminUser interface {
		ListUsers(ctx context.Context, in *AdminListUsersReq, opts ...grpc.CallOption) (*AdminListUsersResp, error)
		GetUserDetail(ctx context.Context, in *AdminGetUserDetailReq, opts ...grpc.CallOption) (*AdminGetUserDetailResp, error)
		BanUser(ctx context.Context, in *AdminBanUserReq, opts ...grpc.CallOption) (*Empty, error)
		UnbanUser(ctx context.Context, in *AdminUnbanUserReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAdminUser struct {
		cli zrpc.Client
	}
)

func NewAdminUser(cli zrpc.Client) AdminUser {
	return &defaultAdminUser{
		cli: cli,
	}
}

func (m *defaultAdminUser) ListUsers(ctx context.Context, in *AdminListUsersReq, opts ...grpc.CallOption) (*AdminListUsersResp, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultAdminUser) GetUserDetail(ctx context.Context, in *AdminGetUserDetailReq, opts ...grpc.CallOption) (*AdminGetUserDetailResp, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}

func (m *defaultAdminUser) BanUser(ctx context.Context, in *AdminBanUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.BanUser(ctx, in, opts...)
}

func (m *defaultAdminUser) UnbanUser(ctx context.Context, in *AdminUnbanUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminUserClient(m.cli.Conn())
	return client.UnbanUser(ctx, in, opts...)
}
