// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package adminproduct

import (
	"context"

	"github.com/ZY0506/PrimeMall/apps/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminAdjustStockReq           = admin.AdminAdjustStockReq
	AdminCategoryTreeResp         = admin.AdminCategoryTreeResp
	AdminCreateCategoryReq        = admin.AdminCreateCategoryReq
	AdminCreateFreightTemplateReq = admin.AdminCreateFreightTemplateReq
	AdminCreateProductReq         = admin.AdminCreateProductReq
	AdminFreightTemplateInfo      = admin.AdminFreightTemplateInfo
	AdminListFreightTemplatesResp = admin.AdminListFreightTemplatesResp
	AdminListProductsReq          = admin.AdminListProductsReq
	AdminListProductsResp         = admin.AdminListProductsResp
	AdminListStockLogsReq         = admin.AdminListStockLogsReq
	AdminListStockLogsResp        = admin.AdminListStockLogsResp
	AdminPageReq                  = admin.AdminPageReq
	AdminProductDetailResp        = admin.AdminProductDetailResp
	AdminStockChangeResp          = admin.AdminStockChangeResp
	AdminUpdateCategoryReq        = admin.AdminUpdateCategoryReq
	AdminUpdateFreightTemplateReq = admin.AdminUpdateFreightTemplateReq
	AdminUpdateProductReq         = admin.AdminUpdateProductReq
	AdminUpdateProductStatusReq   = admin.AdminUpdateProductStatusReq
	Empty                         = admin.Empty
	IdReq                         = admin.IdReq

	AdminProduct interface {
		// 分类管理
		CategoryTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AdminCategoryTreeResp, error)
		CreateCategory(ctx context.Context, in *AdminCreateCategoryReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateCategory(ctx context.Context, in *AdminUpdateCategoryReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteCategory(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		// 商品管理（SPU + SKU 一起创建/更新，全量提交 SKU）
		CreateProduct(ctx context.Context, in *AdminCreateProductReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateProduct(ctx context.Context, in *AdminUpdateProductReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		GetProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminProductDetailResp, error)
		ListProducts(ctx context.Context, in *AdminListProductsReq, opts ...grpc.CallOption) (*AdminListProductsResp, error)
		UpdateProductStatus(ctx context.Context, in *AdminUpdateProductStatusReq, opts ...grpc.CallOption) (*Empty, error)
		// 运费模板管理
		CreateFreightTemplate(ctx context.Context, in *AdminCreateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateFreightTemplate(ctx context.Context, in *AdminUpdateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		ListFreightTemplates(ctx context.Context, in *AdminPageReq, opts ...grpc.CallOption) (*AdminListFreightTemplatesResp, error)
		GetFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminFreightTemplateInfo, error)
		// 库存管理
		AdjustStock(ctx context.Context, in *AdminAdjustStockReq, opts ...grpc.CallOption) (*AdminStockChangeResp, error)
		ListStockLogs(ctx context.Context, in *AdminListStockLogsReq, opts ...grpc.CallOption) (*AdminListStockLogsResp, error)
	}

	defaultAdminProduct struct {
		cli zrpc.Client
	}
)

func NewAdminProduct(cli zrpc.Client) AdminProduct {
	return &defaultAdminProduct{
		cli: cli,
	}
}

// 分类管理
func (m *defaultAdminProduct) CategoryTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AdminCategoryTreeResp, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.CategoryTree(ctx, in, opts...)
}

func (m *defaultAdminProduct) CreateCategory(ctx context.Context, in *AdminCreateCategoryReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultAdminProduct) UpdateCategory(ctx context.Context, in *AdminUpdateCategoryReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultAdminProduct) DeleteCategory(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

// 商品管理（SPU + SKU 一起创建/更新，全量提交 SKU）
func (m *defaultAdminProduct) CreateProduct(ctx context.Context, in *AdminCreateProductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

func (m *defaultAdminProduct) UpdateProduct(ctx context.Context, in *AdminUpdateProductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

func (m *defaultAdminProduct) DeleteProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}

func (m *defaultAdminProduct) GetProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminProductDetailResp, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

func (m *defaultAdminProduct) ListProducts(ctx context.Context, in *AdminListProductsReq, opts ...grpc.CallOption) (*AdminListProductsResp, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

func (m *defaultAdminProduct) UpdateProductStatus(ctx context.Context, in *AdminUpdateProductStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.UpdateProductStatus(ctx, in, opts...)
}

// 运费模板管理
func (m *defaultAdminProduct) CreateFreightTemplate(ctx context.Context, in *AdminCreateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.CreateFreightTemplate(ctx, in, opts...)
}

func (m *defaultAdminProduct) UpdateFreightTemplate(ctx context.Context, in *AdminUpdateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.UpdateFreightTemplate(ctx, in, opts...)
}

func (m *defaultAdminProduct) DeleteFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.DeleteFreightTemplate(ctx, in, opts...)
}

func (m *defaultAdminProduct) ListFreightTemplates(ctx context.Context, in *AdminPageReq, opts ...grpc.CallOption) (*AdminListFreightTemplatesResp, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.ListFreightTemplates(ctx, in, opts...)
}

func (m *defaultAdminProduct) GetFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminFreightTemplateInfo, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.GetFreightTemplate(ctx, in, opts...)
}

// 库存管理
func (m *defaultAdminProduct) AdjustStock(ctx context.Context, in *AdminAdjustStockReq, opts ...grpc.CallOption) (*AdminStockChangeResp, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.AdjustStock(ctx, in, opts...)
}

func (m *defaultAdminProduct) ListStockLogs(ctx context.Context, in *AdminListStockLogsReq, opts ...grpc.CallOption) (*AdminListStockLogsResp, error) {
	client := admin.NewAdminProductClient(m.cli.Conn())
	return client.ListStockLogs(ctx, in, opts...)
}
