// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: apps/service/admin/rpc/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_AdminLogin_FullMethodName      = "/admin.Admin/AdminLogin"
	Admin_GetCurrentAdmin_FullMethodName = "/admin.Admin/GetCurrentAdmin"
	Admin_UpdatePassword_FullMethodName  = "/admin.Admin/UpdatePassword"
	Admin_CreateAdmin_FullMethodName     = "/admin.Admin/CreateAdmin"
	Admin_UpdateAdmin_FullMethodName     = "/admin.Admin/UpdateAdmin"
	Admin_DeleteAdmin_FullMethodName     = "/admin.Admin/DeleteAdmin"
	Admin_GetAdmin_FullMethodName        = "/admin.Admin/GetAdmin"
	Admin_ListAdmin_FullMethodName       = "/admin.Admin/ListAdmin"
	Admin_ListRole_FullMethodName        = "/admin.Admin/ListRole"
	Admin_ListAdminLog_FullMethodName    = "/admin.Admin/ListAdminLog"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Admin ====================
// 管理员自身管理 + 角色/权限只读查询
type AdminClient interface {
	// 登录认证
	AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error)
	GetCurrentAdmin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCurrentAdminResp, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*Empty, error)
	// 管理员 CRUD
	CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*Empty, error)
	UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*Empty, error)
	DeleteAdmin(ctx context.Context, in *DeleteAdminReq, opts ...grpc.CallOption) (*Empty, error)
	GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*GetAdminResp, error)
	ListAdmin(ctx context.Context, in *ListAdminReq, opts ...grpc.CallOption) (*ListAdminResp, error)
	// 角色查询（只读，角色由系统初始化预置）
	ListRole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListRoleResp, error)
	// 操作日志
	ListAdminLog(ctx context.Context, in *ListAdminLogReq, opts ...grpc.CallOption) (*ListAdminLogResp, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminLoginResp)
	err := c.cc.Invoke(ctx, Admin_AdminLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetCurrentAdmin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCurrentAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentAdminResp)
	err := c.cc.Invoke(ctx, Admin_GetCurrentAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Admin_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Admin_CreateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Admin_UpdateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdmin(ctx context.Context, in *DeleteAdminReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Admin_DeleteAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*GetAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminResp)
	err := c.cc.Invoke(ctx, Admin_GetAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdmin(ctx context.Context, in *ListAdminReq, opts ...grpc.CallOption) (*ListAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminResp)
	err := c.cc.Invoke(ctx, Admin_ListAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListRole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleResp)
	err := c.cc.Invoke(ctx, Admin_ListRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminLog(ctx context.Context, in *ListAdminLogReq, opts ...grpc.CallOption) (*ListAdminLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminLogResp)
	err := c.cc.Invoke(ctx, Admin_ListAdminLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// ==================== Admin ====================
// 管理员自身管理 + 角色/权限只读查询
type AdminServer interface {
	// 登录认证
	AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error)
	GetCurrentAdmin(context.Context, *Empty) (*GetCurrentAdminResp, error)
	UpdatePassword(context.Context, *UpdatePasswordReq) (*Empty, error)
	// 管理员 CRUD
	CreateAdmin(context.Context, *CreateAdminReq) (*Empty, error)
	UpdateAdmin(context.Context, *UpdateAdminReq) (*Empty, error)
	DeleteAdmin(context.Context, *DeleteAdminReq) (*Empty, error)
	GetAdmin(context.Context, *GetAdminReq) (*GetAdminResp, error)
	ListAdmin(context.Context, *ListAdminReq) (*ListAdminResp, error)
	// 角色查询（只读，角色由系统初始化预置）
	ListRole(context.Context, *Empty) (*ListRoleResp, error)
	// 操作日志
	ListAdminLog(context.Context, *ListAdminLogReq) (*ListAdminLogResp, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAdminServer) GetCurrentAdmin(context.Context, *Empty) (*GetCurrentAdminResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentAdmin not implemented")
}
func (UnimplementedAdminServer) UpdatePassword(context.Context, *UpdatePasswordReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedAdminServer) CreateAdmin(context.Context, *CreateAdminReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdmin not implemented")
}
func (UnimplementedAdminServer) UpdateAdmin(context.Context, *UpdateAdminReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdmin not implemented")
}
func (UnimplementedAdminServer) DeleteAdmin(context.Context, *DeleteAdminReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdmin not implemented")
}
func (UnimplementedAdminServer) GetAdmin(context.Context, *GetAdminReq) (*GetAdminResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdmin not implemented")
}
func (UnimplementedAdminServer) ListAdmin(context.Context, *ListAdminReq) (*ListAdminResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdmin not implemented")
}
func (UnimplementedAdminServer) ListRole(context.Context, *Empty) (*ListRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRole not implemented")
}
func (UnimplementedAdminServer) ListAdminLog(context.Context, *ListAdminLogReq) (*ListAdminLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminLog not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call pancis, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminLogin(ctx, req.(*AdminLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetCurrentAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetCurrentAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetCurrentAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetCurrentAdmin(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdatePassword(ctx, req.(*UpdatePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdmin(ctx, req.(*CreateAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdmin(ctx, req.(*UpdateAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdmin(ctx, req.(*DeleteAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdmin(ctx, req.(*GetAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdmin(ctx, req.(*ListAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListRole(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminLog(ctx, req.(*ListAdminLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _Admin_AdminLogin_Handler,
		},
		{
			MethodName: "GetCurrentAdmin",
			Handler:    _Admin_GetCurrentAdmin_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Admin_UpdatePassword_Handler,
		},
		{
			MethodName: "CreateAdmin",
			Handler:    _Admin_CreateAdmin_Handler,
		},
		{
			MethodName: "UpdateAdmin",
			Handler:    _Admin_UpdateAdmin_Handler,
		},
		{
			MethodName: "DeleteAdmin",
			Handler:    _Admin_DeleteAdmin_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _Admin_GetAdmin_Handler,
		},
		{
			MethodName: "ListAdmin",
			Handler:    _Admin_ListAdmin_Handler,
		},
		{
			MethodName: "ListRole",
			Handler:    _Admin_ListRole_Handler,
		},
		{
			MethodName: "ListAdminLog",
			Handler:    _Admin_ListAdminLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/admin/rpc/admin.proto",
}

const (
	AdminUser_ListUsers_FullMethodName     = "/admin.AdminUser/ListUsers"
	AdminUser_GetUserDetail_FullMethodName = "/admin.AdminUser/GetUserDetail"
	AdminUser_BanUser_FullMethodName       = "/admin.AdminUser/BanUser"
	AdminUser_UnbanUser_FullMethodName     = "/admin.AdminUser/UnbanUser"
)

// AdminUserClient is the client API for AdminUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== AdminUser ====================
// 用户管理（聚合 UserRpc）
type AdminUserClient interface {
	ListUsers(ctx context.Context, in *AdminListUsersReq, opts ...grpc.CallOption) (*AdminListUsersResp, error)
	GetUserDetail(ctx context.Context, in *AdminGetUserDetailReq, opts ...grpc.CallOption) (*AdminGetUserDetailResp, error)
	BanUser(ctx context.Context, in *AdminBanUserReq, opts ...grpc.CallOption) (*Empty, error)
	UnbanUser(ctx context.Context, in *AdminUnbanUserReq, opts ...grpc.CallOption) (*Empty, error)
}

type adminUserClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminUserClient(cc grpc.ClientConnInterface) AdminUserClient {
	return &adminUserClient{cc}
}

func (c *adminUserClient) ListUsers(ctx context.Context, in *AdminListUsersReq, opts ...grpc.CallOption) (*AdminListUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListUsersResp)
	err := c.cc.Invoke(ctx, AdminUser_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) GetUserDetail(ctx context.Context, in *AdminGetUserDetailReq, opts ...grpc.CallOption) (*AdminGetUserDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGetUserDetailResp)
	err := c.cc.Invoke(ctx, AdminUser_GetUserDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) BanUser(ctx context.Context, in *AdminBanUserReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminUser_BanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) UnbanUser(ctx context.Context, in *AdminUnbanUserReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminUser_UnbanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminUserServer is the server API for AdminUser service.
// All implementations must embed UnimplementedAdminUserServer
// for forward compatibility.
//
// ==================== AdminUser ====================
// 用户管理（聚合 UserRpc）
type AdminUserServer interface {
	ListUsers(context.Context, *AdminListUsersReq) (*AdminListUsersResp, error)
	GetUserDetail(context.Context, *AdminGetUserDetailReq) (*AdminGetUserDetailResp, error)
	BanUser(context.Context, *AdminBanUserReq) (*Empty, error)
	UnbanUser(context.Context, *AdminUnbanUserReq) (*Empty, error)
	mustEmbedUnimplementedAdminUserServer()
}

// UnimplementedAdminUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminUserServer struct{}

func (UnimplementedAdminUserServer) ListUsers(context.Context, *AdminListUsersReq) (*AdminListUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAdminUserServer) GetUserDetail(context.Context, *AdminGetUserDetailReq) (*AdminGetUserDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (UnimplementedAdminUserServer) BanUser(context.Context, *AdminBanUserReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BanUser not implemented")
}
func (UnimplementedAdminUserServer) UnbanUser(context.Context, *AdminUnbanUserReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbanUser not implemented")
}
func (UnimplementedAdminUserServer) mustEmbedUnimplementedAdminUserServer() {}
func (UnimplementedAdminUserServer) testEmbeddedByValue()                   {}

// UnsafeAdminUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminUserServer will
// result in compilation errors.
type UnsafeAdminUserServer interface {
	mustEmbedUnimplementedAdminUserServer()
}

func RegisterAdminUserServer(s grpc.ServiceRegistrar, srv AdminUserServer) {
	// If the following call pancis, it indicates UnimplementedAdminUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminUser_ServiceDesc, srv)
}

func _AdminUser_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).ListUsers(ctx, req.(*AdminListUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetUserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_GetUserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).GetUserDetail(ctx, req.(*AdminGetUserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_BanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminBanUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).BanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_BanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).BanUser(ctx, req.(*AdminBanUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_UnbanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUnbanUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).UnbanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_UnbanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).UnbanUser(ctx, req.(*AdminUnbanUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminUser_ServiceDesc is the grpc.ServiceDesc for AdminUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminUser",
	HandlerType: (*AdminUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _AdminUser_ListUsers_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _AdminUser_GetUserDetail_Handler,
		},
		{
			MethodName: "BanUser",
			Handler:    _AdminUser_BanUser_Handler,
		},
		{
			MethodName: "UnbanUser",
			Handler:    _AdminUser_UnbanUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/admin/rpc/admin.proto",
}

const (
	AdminProduct_CategoryTree_FullMethodName          = "/admin.AdminProduct/CategoryTree"
	AdminProduct_CreateCategory_FullMethodName        = "/admin.AdminProduct/CreateCategory"
	AdminProduct_UpdateCategory_FullMethodName        = "/admin.AdminProduct/UpdateCategory"
	AdminProduct_DeleteCategory_FullMethodName        = "/admin.AdminProduct/DeleteCategory"
	AdminProduct_CreateProduct_FullMethodName         = "/admin.AdminProduct/CreateProduct"
	AdminProduct_UpdateProduct_FullMethodName         = "/admin.AdminProduct/UpdateProduct"
	AdminProduct_DeleteProduct_FullMethodName         = "/admin.AdminProduct/DeleteProduct"
	AdminProduct_GetProduct_FullMethodName            = "/admin.AdminProduct/GetProduct"
	AdminProduct_ListProducts_FullMethodName          = "/admin.AdminProduct/ListProducts"
	AdminProduct_UpdateProductStatus_FullMethodName   = "/admin.AdminProduct/UpdateProductStatus"
	AdminProduct_CreateFreightTemplate_FullMethodName = "/admin.AdminProduct/CreateFreightTemplate"
	AdminProduct_UpdateFreightTemplate_FullMethodName = "/admin.AdminProduct/UpdateFreightTemplate"
	AdminProduct_DeleteFreightTemplate_FullMethodName = "/admin.AdminProduct/DeleteFreightTemplate"
	AdminProduct_ListFreightTemplates_FullMethodName  = "/admin.AdminProduct/ListFreightTemplates"
	AdminProduct_GetFreightTemplate_FullMethodName    = "/admin.AdminProduct/GetFreightTemplate"
	AdminProduct_AdjustStock_FullMethodName           = "/admin.AdminProduct/AdjustStock"
	AdminProduct_ListStockLogs_FullMethodName         = "/admin.AdminProduct/ListStockLogs"
)

// AdminProductClient is the client API for AdminProduct service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== AdminProduct ====================
// 商品管理（聚合 ProductRpc）
type AdminProductClient interface {
	// 分类管理
	CategoryTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AdminCategoryTreeResp, error)
	CreateCategory(ctx context.Context, in *AdminCreateCategoryReq, opts ...grpc.CallOption) (*Empty, error)
	UpdateCategory(ctx context.Context, in *AdminUpdateCategoryReq, opts ...grpc.CallOption) (*Empty, error)
	DeleteCategory(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	// 商品管理（SPU + SKU 一起创建/更新，全量提交 SKU）
	CreateProduct(ctx context.Context, in *AdminCreateProductReq, opts ...grpc.CallOption) (*Empty, error)
	UpdateProduct(ctx context.Context, in *AdminUpdateProductReq, opts ...grpc.CallOption) (*Empty, error)
	DeleteProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	GetProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminProductDetailResp, error)
	ListProducts(ctx context.Context, in *AdminListProductsReq, opts ...grpc.CallOption) (*AdminListProductsResp, error)
	UpdateProductStatus(ctx context.Context, in *AdminUpdateProductStatusReq, opts ...grpc.CallOption) (*Empty, error)
	// 运费模板管理
	CreateFreightTemplate(ctx context.Context, in *AdminCreateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error)
	UpdateFreightTemplate(ctx context.Context, in *AdminUpdateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error)
	DeleteFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	ListFreightTemplates(ctx context.Context, in *AdminPageReq, opts ...grpc.CallOption) (*AdminListFreightTemplatesResp, error)
	GetFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminFreightTemplateInfo, error)
	// 库存管理
	AdjustStock(ctx context.Context, in *AdminAdjustStockReq, opts ...grpc.CallOption) (*AdminStockChangeResp, error)
	ListStockLogs(ctx context.Context, in *AdminListStockLogsReq, opts ...grpc.CallOption) (*AdminListStockLogsResp, error)
}

type adminProductClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminProductClient(cc grpc.ClientConnInterface) AdminProductClient {
	return &adminProductClient{cc}
}

func (c *adminProductClient) CategoryTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AdminCategoryTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCategoryTreeResp)
	err := c.cc.Invoke(ctx, AdminProduct_CategoryTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) CreateCategory(ctx context.Context, in *AdminCreateCategoryReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) UpdateCategory(ctx context.Context, in *AdminUpdateCategoryReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) DeleteCategory(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) CreateProduct(ctx context.Context, in *AdminCreateProductReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) UpdateProduct(ctx context.Context, in *AdminUpdateProductReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) DeleteProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) GetProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminProductDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProductDetailResp)
	err := c.cc.Invoke(ctx, AdminProduct_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) ListProducts(ctx context.Context, in *AdminListProductsReq, opts ...grpc.CallOption) (*AdminListProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListProductsResp)
	err := c.cc.Invoke(ctx, AdminProduct_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) UpdateProductStatus(ctx context.Context, in *AdminUpdateProductStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_UpdateProductStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) CreateFreightTemplate(ctx context.Context, in *AdminCreateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_CreateFreightTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) UpdateFreightTemplate(ctx context.Context, in *AdminUpdateFreightTemplateReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_UpdateFreightTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) DeleteFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminProduct_DeleteFreightTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) ListFreightTemplates(ctx context.Context, in *AdminPageReq, opts ...grpc.CallOption) (*AdminListFreightTemplatesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListFreightTemplatesResp)
	err := c.cc.Invoke(ctx, AdminProduct_ListFreightTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) GetFreightTemplate(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*AdminFreightTemplateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminFreightTemplateInfo)
	err := c.cc.Invoke(ctx, AdminProduct_GetFreightTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) AdjustStock(ctx context.Context, in *AdminAdjustStockReq, opts ...grpc.CallOption) (*AdminStockChangeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminStockChangeResp)
	err := c.cc.Invoke(ctx, AdminProduct_AdjustStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProductClient) ListStockLogs(ctx context.Context, in *AdminListStockLogsReq, opts ...grpc.CallOption) (*AdminListStockLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListStockLogsResp)
	err := c.cc.Invoke(ctx, AdminProduct_ListStockLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminProductServer is the server API for AdminProduct service.
// All implementations must embed UnimplementedAdminProductServer
// for forward compatibility.
//
// ==================== AdminProduct ====================
// 商品管理（聚合 ProductRpc）
type AdminProductServer interface {
	// 分类管理
	CategoryTree(context.Context, *Empty) (*AdminCategoryTreeResp, error)
	CreateCategory(context.Context, *AdminCreateCategoryReq) (*Empty, error)
	UpdateCategory(context.Context, *AdminUpdateCategoryReq) (*Empty, error)
	DeleteCategory(context.Context, *IdReq) (*Empty, error)
	// 商品管理（SPU + SKU 一起创建/更新，全量提交 SKU）
	CreateProduct(context.Context, *AdminCreateProductReq) (*Empty, error)
	UpdateProduct(context.Context, *AdminUpdateProductReq) (*Empty, error)
	DeleteProduct(context.Context, *IdReq) (*Empty, error)
	GetProduct(context.Context, *IdReq) (*AdminProductDetailResp, error)
	ListProducts(context.Context, *AdminListProductsReq) (*AdminListProductsResp, error)
	UpdateProductStatus(context.Context, *AdminUpdateProductStatusReq) (*Empty, error)
	// 运费模板管理
	CreateFreightTemplate(context.Context, *AdminCreateFreightTemplateReq) (*Empty, error)
	UpdateFreightTemplate(context.Context, *AdminUpdateFreightTemplateReq) (*Empty, error)
	DeleteFreightTemplate(context.Context, *IdReq) (*Empty, error)
	ListFreightTemplates(context.Context, *AdminPageReq) (*AdminListFreightTemplatesResp, error)
	GetFreightTemplate(context.Context, *IdReq) (*AdminFreightTemplateInfo, error)
	// 库存管理
	AdjustStock(context.Context, *AdminAdjustStockReq) (*AdminStockChangeResp, error)
	ListStockLogs(context.Context, *AdminListStockLogsReq) (*AdminListStockLogsResp, error)
	mustEmbedUnimplementedAdminProductServer()
}

// UnimplementedAdminProductServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminProductServer struct{}

func (UnimplementedAdminProductServer) CategoryTree(context.Context, *Empty) (*AdminCategoryTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryTree not implemented")
}
func (UnimplementedAdminProductServer) CreateCategory(context.Context, *AdminCreateCategoryReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedAdminProductServer) UpdateCategory(context.Context, *AdminUpdateCategoryReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedAdminProductServer) DeleteCategory(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedAdminProductServer) CreateProduct(context.Context, *AdminCreateProductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedAdminProductServer) UpdateProduct(context.Context, *AdminUpdateProductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedAdminProductServer) DeleteProduct(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedAdminProductServer) GetProduct(context.Context, *IdReq) (*AdminProductDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedAdminProductServer) ListProducts(context.Context, *AdminListProductsReq) (*AdminListProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedAdminProductServer) UpdateProductStatus(context.Context, *AdminUpdateProductStatusReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductStatus not implemented")
}
func (UnimplementedAdminProductServer) CreateFreightTemplate(context.Context, *AdminCreateFreightTemplateReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFreightTemplate not implemented")
}
func (UnimplementedAdminProductServer) UpdateFreightTemplate(context.Context, *AdminUpdateFreightTemplateReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFreightTemplate not implemented")
}
func (UnimplementedAdminProductServer) DeleteFreightTemplate(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFreightTemplate not implemented")
}
func (UnimplementedAdminProductServer) ListFreightTemplates(context.Context, *AdminPageReq) (*AdminListFreightTemplatesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFreightTemplates not implemented")
}
func (UnimplementedAdminProductServer) GetFreightTemplate(context.Context, *IdReq) (*AdminFreightTemplateInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFreightTemplate not implemented")
}
func (UnimplementedAdminProductServer) AdjustStock(context.Context, *AdminAdjustStockReq) (*AdminStockChangeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustStock not implemented")
}
func (UnimplementedAdminProductServer) ListStockLogs(context.Context, *AdminListStockLogsReq) (*AdminListStockLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStockLogs not implemented")
}
func (UnimplementedAdminProductServer) mustEmbedUnimplementedAdminProductServer() {}
func (UnimplementedAdminProductServer) testEmbeddedByValue()                      {}

// UnsafeAdminProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminProductServer will
// result in compilation errors.
type UnsafeAdminProductServer interface {
	mustEmbedUnimplementedAdminProductServer()
}

func RegisterAdminProductServer(s grpc.ServiceRegistrar, srv AdminProductServer) {
	// If the following call pancis, it indicates UnimplementedAdminProductServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminProduct_ServiceDesc, srv)
}

func _AdminProduct_CategoryTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).CategoryTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_CategoryTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).CategoryTree(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).CreateCategory(ctx, req.(*AdminCreateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).UpdateCategory(ctx, req.(*AdminUpdateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).DeleteCategory(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).CreateProduct(ctx, req.(*AdminCreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).UpdateProduct(ctx, req.(*AdminUpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).DeleteProduct(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).GetProduct(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).ListProducts(ctx, req.(*AdminListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_UpdateProductStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateProductStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).UpdateProductStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_UpdateProductStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).UpdateProductStatus(ctx, req.(*AdminUpdateProductStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_CreateFreightTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateFreightTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).CreateFreightTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_CreateFreightTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).CreateFreightTemplate(ctx, req.(*AdminCreateFreightTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_UpdateFreightTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateFreightTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).UpdateFreightTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_UpdateFreightTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).UpdateFreightTemplate(ctx, req.(*AdminUpdateFreightTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_DeleteFreightTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).DeleteFreightTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_DeleteFreightTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).DeleteFreightTemplate(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_ListFreightTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).ListFreightTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_ListFreightTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).ListFreightTemplates(ctx, req.(*AdminPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_GetFreightTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).GetFreightTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_GetFreightTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).GetFreightTemplate(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_AdjustStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAdjustStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).AdjustStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_AdjustStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).AdjustStock(ctx, req.(*AdminAdjustStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProduct_ListStockLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListStockLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProductServer).ListStockLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProduct_ListStockLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProductServer).ListStockLogs(ctx, req.(*AdminListStockLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminProduct_ServiceDesc is the grpc.ServiceDesc for AdminProduct service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminProduct_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminProduct",
	HandlerType: (*AdminProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CategoryTree",
			Handler:    _AdminProduct_CategoryTree_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _AdminProduct_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _AdminProduct_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _AdminProduct_DeleteCategory_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _AdminProduct_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _AdminProduct_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _AdminProduct_DeleteProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _AdminProduct_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _AdminProduct_ListProducts_Handler,
		},
		{
			MethodName: "UpdateProductStatus",
			Handler:    _AdminProduct_UpdateProductStatus_Handler,
		},
		{
			MethodName: "CreateFreightTemplate",
			Handler:    _AdminProduct_CreateFreightTemplate_Handler,
		},
		{
			MethodName: "UpdateFreightTemplate",
			Handler:    _AdminProduct_UpdateFreightTemplate_Handler,
		},
		{
			MethodName: "DeleteFreightTemplate",
			Handler:    _AdminProduct_DeleteFreightTemplate_Handler,
		},
		{
			MethodName: "ListFreightTemplates",
			Handler:    _AdminProduct_ListFreightTemplates_Handler,
		},
		{
			MethodName: "GetFreightTemplate",
			Handler:    _AdminProduct_GetFreightTemplate_Handler,
		},
		{
			MethodName: "AdjustStock",
			Handler:    _AdminProduct_AdjustStock_Handler,
		},
		{
			MethodName: "ListStockLogs",
			Handler:    _AdminProduct_ListStockLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/admin/rpc/admin.proto",
}

const (
	AdminOrder_ListOrders_FullMethodName = "/admin.AdminOrder/ListOrders"
	AdminOrder_GetOrder_FullMethodName   = "/admin.AdminOrder/GetOrder"
	AdminOrder_ShipOrder_FullMethodName  = "/admin.AdminOrder/ShipOrder"
)

// AdminOrderClient is the client API for AdminOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== AdminOrder ====================
// 订单管理（聚合 OrderRpc）
type AdminOrderClient interface {
	ListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*AdminListOrdersResp, error)
	GetOrder(ctx context.Context, in *AdminGetOrderReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error)
	ShipOrder(ctx context.Context, in *AdminShipOrderReq, opts ...grpc.CallOption) (*Empty, error)
}

type adminOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminOrderClient(cc grpc.ClientConnInterface) AdminOrderClient {
	return &adminOrderClient{cc}
}

func (c *adminOrderClient) ListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*AdminListOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListOrdersResp)
	err := c.cc.Invoke(ctx, AdminOrder_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminOrderClient) GetOrder(ctx context.Context, in *AdminGetOrderReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOrderDetailResp)
	err := c.cc.Invoke(ctx, AdminOrder_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminOrderClient) ShipOrder(ctx context.Context, in *AdminShipOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminOrder_ShipOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminOrderServer is the server API for AdminOrder service.
// All implementations must embed UnimplementedAdminOrderServer
// for forward compatibility.
//
// ==================== AdminOrder ====================
// 订单管理（聚合 OrderRpc）
type AdminOrderServer interface {
	ListOrders(context.Context, *AdminListOrdersReq) (*AdminListOrdersResp, error)
	GetOrder(context.Context, *AdminGetOrderReq) (*AdminOrderDetailResp, error)
	ShipOrder(context.Context, *AdminShipOrderReq) (*Empty, error)
	mustEmbedUnimplementedAdminOrderServer()
}

// UnimplementedAdminOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminOrderServer struct{}

func (UnimplementedAdminOrderServer) ListOrders(context.Context, *AdminListOrdersReq) (*AdminListOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedAdminOrderServer) GetOrder(context.Context, *AdminGetOrderReq) (*AdminOrderDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedAdminOrderServer) ShipOrder(context.Context, *AdminShipOrderReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipOrder not implemented")
}
func (UnimplementedAdminOrderServer) mustEmbedUnimplementedAdminOrderServer() {}
func (UnimplementedAdminOrderServer) testEmbeddedByValue()                    {}

// UnsafeAdminOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminOrderServer will
// result in compilation errors.
type UnsafeAdminOrderServer interface {
	mustEmbedUnimplementedAdminOrderServer()
}

func RegisterAdminOrderServer(s grpc.ServiceRegistrar, srv AdminOrderServer) {
	// If the following call pancis, it indicates UnimplementedAdminOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminOrder_ServiceDesc, srv)
}

func _AdminOrder_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminOrderServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminOrder_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminOrderServer).ListOrders(ctx, req.(*AdminListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminOrder_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminOrderServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminOrder_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminOrderServer).GetOrder(ctx, req.(*AdminGetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminOrder_ShipOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminShipOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminOrderServer).ShipOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminOrder_ShipOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminOrderServer).ShipOrder(ctx, req.(*AdminShipOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminOrder_ServiceDesc is the grpc.ServiceDesc for AdminOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminOrder",
	HandlerType: (*AdminOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOrders",
			Handler:    _AdminOrder_ListOrders_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _AdminOrder_GetOrder_Handler,
		},
		{
			MethodName: "ShipOrder",
			Handler:    _AdminOrder_ShipOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/admin/rpc/admin.proto",
}

const (
	AdminAfterSale_ListAfterSales_FullMethodName  = "/admin.AdminAfterSale/ListAfterSales"
	AdminAfterSale_GetAfterSale_FullMethodName    = "/admin.AdminAfterSale/GetAfterSale"
	AdminAfterSale_HandleAfterSale_FullMethodName = "/admin.AdminAfterSale/HandleAfterSale"
)

// AdminAfterSaleClient is the client API for AdminAfterSale service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== AdminAfterSale ====================
// 售后管理（聚合 OrderRpc）
type AdminAfterSaleClient interface {
	ListAfterSales(ctx context.Context, in *AdminListAfterSalesReq, opts ...grpc.CallOption) (*AdminListAfterSalesResp, error)
	GetAfterSale(ctx context.Context, in *AdminGetAfterSaleReq, opts ...grpc.CallOption) (*AdminAfterSaleDetailResp, error)
	HandleAfterSale(ctx context.Context, in *AdminHandleAfterSaleReq, opts ...grpc.CallOption) (*Empty, error)
}

type adminAfterSaleClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAfterSaleClient(cc grpc.ClientConnInterface) AdminAfterSaleClient {
	return &adminAfterSaleClient{cc}
}

func (c *adminAfterSaleClient) ListAfterSales(ctx context.Context, in *AdminListAfterSalesReq, opts ...grpc.CallOption) (*AdminListAfterSalesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListAfterSalesResp)
	err := c.cc.Invoke(ctx, AdminAfterSale_ListAfterSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAfterSaleClient) GetAfterSale(ctx context.Context, in *AdminGetAfterSaleReq, opts ...grpc.CallOption) (*AdminAfterSaleDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAfterSaleDetailResp)
	err := c.cc.Invoke(ctx, AdminAfterSale_GetAfterSale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAfterSaleClient) HandleAfterSale(ctx context.Context, in *AdminHandleAfterSaleReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAfterSale_HandleAfterSale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAfterSaleServer is the server API for AdminAfterSale service.
// All implementations must embed UnimplementedAdminAfterSaleServer
// for forward compatibility.
//
// ==================== AdminAfterSale ====================
// 售后管理（聚合 OrderRpc）
type AdminAfterSaleServer interface {
	ListAfterSales(context.Context, *AdminListAfterSalesReq) (*AdminListAfterSalesResp, error)
	GetAfterSale(context.Context, *AdminGetAfterSaleReq) (*AdminAfterSaleDetailResp, error)
	HandleAfterSale(context.Context, *AdminHandleAfterSaleReq) (*Empty, error)
	mustEmbedUnimplementedAdminAfterSaleServer()
}

// UnimplementedAdminAfterSaleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminAfterSaleServer struct{}

func (UnimplementedAdminAfterSaleServer) ListAfterSales(context.Context, *AdminListAfterSalesReq) (*AdminListAfterSalesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAfterSales not implemented")
}
func (UnimplementedAdminAfterSaleServer) GetAfterSale(context.Context, *AdminGetAfterSaleReq) (*AdminAfterSaleDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAfterSale not implemented")
}
func (UnimplementedAdminAfterSaleServer) HandleAfterSale(context.Context, *AdminHandleAfterSaleReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAfterSale not implemented")
}
func (UnimplementedAdminAfterSaleServer) mustEmbedUnimplementedAdminAfterSaleServer() {}
func (UnimplementedAdminAfterSaleServer) testEmbeddedByValue()                        {}

// UnsafeAdminAfterSaleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAfterSaleServer will
// result in compilation errors.
type UnsafeAdminAfterSaleServer interface {
	mustEmbedUnimplementedAdminAfterSaleServer()
}

func RegisterAdminAfterSaleServer(s grpc.ServiceRegistrar, srv AdminAfterSaleServer) {
	// If the following call pancis, it indicates UnimplementedAdminAfterSaleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminAfterSale_ServiceDesc, srv)
}

func _AdminAfterSale_ListAfterSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListAfterSalesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAfterSaleServer).ListAfterSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAfterSale_ListAfterSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAfterSaleServer).ListAfterSales(ctx, req.(*AdminListAfterSalesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAfterSale_GetAfterSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetAfterSaleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAfterSaleServer).GetAfterSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAfterSale_GetAfterSale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAfterSaleServer).GetAfterSale(ctx, req.(*AdminGetAfterSaleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAfterSale_HandleAfterSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminHandleAfterSaleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAfterSaleServer).HandleAfterSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAfterSale_HandleAfterSale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAfterSaleServer).HandleAfterSale(ctx, req.(*AdminHandleAfterSaleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminAfterSale_ServiceDesc is the grpc.ServiceDesc for AdminAfterSale service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminAfterSale_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminAfterSale",
	HandlerType: (*AdminAfterSaleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAfterSales",
			Handler:    _AdminAfterSale_ListAfterSales_Handler,
		},
		{
			MethodName: "GetAfterSale",
			Handler:    _AdminAfterSale_GetAfterSale_Handler,
		},
		{
			MethodName: "HandleAfterSale",
			Handler:    _AdminAfterSale_HandleAfterSale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/admin/rpc/admin.proto",
}

const (
	AdminCoupon_GetCouponDetail_FullMethodName = "/admin.AdminCoupon/GetCouponDetail"
)

// AdminCouponClient is the client API for AdminCoupon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== AdminCoupon ====================
// 优惠券管理（聚合 MarketingRpc）
type AdminCouponClient interface {
	GetCouponDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CouponDetailResp, error)
}

type adminCouponClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminCouponClient(cc grpc.ClientConnInterface) AdminCouponClient {
	return &adminCouponClient{cc}
}

func (c *adminCouponClient) GetCouponDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CouponDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponDetailResp)
	err := c.cc.Invoke(ctx, AdminCoupon_GetCouponDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminCouponServer is the server API for AdminCoupon service.
// All implementations must embed UnimplementedAdminCouponServer
// for forward compatibility.
//
// ==================== AdminCoupon ====================
// 优惠券管理（聚合 MarketingRpc）
type AdminCouponServer interface {
	GetCouponDetail(context.Context, *IdReq) (*CouponDetailResp, error)
	mustEmbedUnimplementedAdminCouponServer()
}

// UnimplementedAdminCouponServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminCouponServer struct{}

func (UnimplementedAdminCouponServer) GetCouponDetail(context.Context, *IdReq) (*CouponDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCouponDetail not implemented")
}
func (UnimplementedAdminCouponServer) mustEmbedUnimplementedAdminCouponServer() {}
func (UnimplementedAdminCouponServer) testEmbeddedByValue()                     {}

// UnsafeAdminCouponServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminCouponServer will
// result in compilation errors.
type UnsafeAdminCouponServer interface {
	mustEmbedUnimplementedAdminCouponServer()
}

func RegisterAdminCouponServer(s grpc.ServiceRegistrar, srv AdminCouponServer) {
	// If the following call pancis, it indicates UnimplementedAdminCouponServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminCoupon_ServiceDesc, srv)
}

func _AdminCoupon_GetCouponDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCouponServer).GetCouponDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCoupon_GetCouponDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCouponServer).GetCouponDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminCoupon_ServiceDesc is the grpc.ServiceDesc for AdminCoupon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminCoupon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminCoupon",
	HandlerType: (*AdminCouponServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCouponDetail",
			Handler:    _AdminCoupon_GetCouponDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/service/admin/rpc/admin.proto",
}
